### ISSUE TITLE
iATS and WooCommerce date format rejection

### ISSUE THREAD

**Issue by mbHope** [iATSPayments/com.iatspayments.civicrm#101]
When our WooCommerce installation submits a credit card for processing by iATS, cards that expire in January through September are rejected because iATS only receives a single digit month (format m/yy) rather than the required mm/yy.  We are using the WooCommerce Authorize.net AIM Gateway plugin.

**Comment by adixon** [comment]
Yes, that won't work, iATS doesn't use the Auth.net AIM gateway. I'll bet there's a lot more than just the expiry that's a problem.

**Comment by adixon** [comment]
Okay, I'm learning something new today, thanks Stephen! In case anyone else finds this case ... the authorize.net AIM emulator is not part of this project, please post any such requests over at the main iATS support page.

**Comment by mbHope** [comment]
Is there something better to use to connect iATS with WooCommerce?



Michelle Baylor
IT Director

Get-HOPE-Global.org
www.facebook.com/GetHOPEGlobal

**Comment by adixon** [comment]
That's a great question, but the short answer is, this project is only about connnecting iATS to CiviCRM. So I can recommend CiviCRM, but that's a different beast than WooCommerce. It maybe better than what you're using WooCommerce for, or it may not, depending on the specifics of your needs.

**Comment by mbHope** [comment]
I understand.  Thanks for the clarification.



Michelle Baylor
IT Director

Get-HOPE-Global.org
www.facebook.com/GetHOPEGlobal

**Comment by stephenbiats** [comment]
The ideal would be for Woocommerce to build iATS in as a payment processor.  We have approached them before without luck, will try again.  If you have a contact at WooCommerce we can contact please let me know.
