### ISSUE TITLE
Calls to drupal-only watchdog function

### ISSUE THREAD

**Issue by colemanw** [iATSPayments/com.iatspayments.civicrm#105]
iATSService.php is full of calls to the drupal `watchdog` function, which would crash any non-drupal system.

**Comment by adixon** [comment]
Agreed that it's full of drupal watchdog calls but:
1. The only ones that aren't commented out are in CRM/iATS/iATSService.php
2. Those are only invoked if the function exists and userFrameworkLogging is on (line 66)

So it's safe to use with non-drupal systems.

Happy to ditch them altogether if you have a better approach.
