### ISSUE TITLE
Use civicrm_api3 instead of civicrm_api (when not checking the result)

### ISSUE THREAD

**Issue by mlutfy** [iATSPayments/com.iatspayments.civicrm#108]
In the iats jobs, there are two places where the API is used and the error handling is a bit weird.

- in one case, using a try/catch, but not civicrm_api3().
- in another case, not using civicrm_api3, and not checking the result.

Since I ran into issues on a site where other hooks/extensions where causing a contribution to fail, I tweaked the civicrm_api usage a bit to make sure we catch errors more easily. (will open PR)

**Comment by adixon** [comment]
Thanks, this change is in (this bit of the code now resides in the iats.php file).
