### ISSUE TITLE
Invalid API Key provided

### ISSUE THREAD

**Issue by joshgowans** [iATSPayments/com.iatspayments.civicrm#110]
Recent implementation of iATS payments extension on CiviCRM 4.6.10 + Joomla 3.4.8 works on public contribution forms but fails in the admin area when attempting to process a donation with the following error:

Payment Error Response:
Error: Invalid API Key provided: **********

Original set up included same password for both 80 & 01 accounts, however that's been corrected and it's still throwing this error.

**Comment by KarinG** [comment]
when selecting your Passwords - please note that special characters can cause issues in PHP applications, like this extension. 

It's ok to have the same passwords for 80 and 01 - but not recommended - typical setup is: 

01 [your master account] - no webservices access [so only use the 01 to log into iatspayments.com]; set the 01 up to have refund capability/permissions [contact iATS customer service to do that]; the 01 does not appear anywhere in your CiviCRM

80 [81, 82, 83 etc] - use that in your CiviCRM to connect to iATS. If you like set this account up without refund capability [so when/if your CiviCRM gets hacked no-one can refund all]. 

Does that help?

**Comment by KarinG** [comment]
Have you created a test88 payment processor in your CiviCRM? See the Readme and Wiki for details on setting this up.

**Comment by joshgowans** [comment]
I'll check on that today... not sure they've done that.

Josh

On Sun, Jan 3, 2016 at 8:09 PM, Karin Gerritsen <notifications@github.com>
wrote:

> Have you created a test88 payment processor in your CiviCRM? See the
> Readme and Wiki for details on setting this up.
>
> —
> Reply to this email directly or view it on GitHub
> <https://github.com/iATSPayments/com.iatspayments.civicrm/issues/110#issuecomment-168570512>
> .
>



-- 
Josh Gowans
CiviCRM <http://civicrm.org/>, LLC
803.258.0277 | p
joshua.gowans | skype

*How you can help support CiviCRM today...*
Join the conversation on Twitter <https://twitter.com/civicrm>, LinkedIn
<https://www.linkedin.com/groups/CiviCRM-1418647>, Google +
<https://plus.google.com/u/1/communities/114972789429616596475>, and
Facebook <https://www.facebook.com/civicrm>.
Provide feedback on popular review sites such as G2
<https://www.g2crowd.com/products/civicrm/reviews>, Software Advice
<http://www.softwareadvice.com/nonprofit/civicrm-profile/> and Capterra
<http://www.capterra.com/fundraising-software/spotlight/79192/CiviCRM/CiviCRM>
.

**Comment by KarinG** [comment]
Update: a disabled Stripe payment processor was running interference; solved by deleting that payment processor
