### ISSUE TITLE
ability to alter recurring payment date

### ISSUE THREAD

**Issue by lcdservices** [iATSPayments/com.iatspayments.civicrm#112]
One of the nice features of how this iATS extension handles recurring payments is that the recurrence is triggered from the Civi side, which means you can alter the amount, number of recurrences, etc. However, you cannot currently alter the date of recurrence. For example, if we want recurrences triggered on the 1st and 16th of the month for membership renewals, we can't alter that (if, for example, the initial signup was completed on the 9th).

What I'd like to know is whether that limitation was intentional, and if we were to build functionality to allow the ability to change the date, what concerns or issues should we have? It's clearly not as trivial as just changing the receive date, since we need to actually set the future date for the next recurrence and then know that future recurrences beyond that will use that value as the baseline. For example, if my next recurrence is scheduled for 2016-01-09 and I reset it to 2016-01-16, I want the next date to be 2016-02-16 (for a monthly recurring schedule).

Anyway, I'm just curious about what I may need to take into consideration if we try to provide this functionality (or if you've given thought to adding it).

**Comment by KarinG** [comment]
Right now you would need to update the next_sched_contribution_date in the civicrm_contribution_recur table to achieve this.

Alan actually just added a bunch of work that will let an organization pick the future date/fixed schedule - as a setting. Then when a contact starts a recurring contribution - the first payment will be on the 'next possible allowed' date. 

Check it out / give it a test drive: branch: https://github.com/iATSPayments/com.iatspayments.civicrm/tree/fixed-schedule-monthly - or hang in there as we merge this - run our test matrix - and prepare a new release.

**Comment by lcdservices** [comment]
Interesting -- so with that setting, you would do something like say... recurring contributions should only be run on the 1st and 15th of the month. If someone triggers a new recurrence on the 12th, it will be run on the 15th; if they trigger it on the 20th, it would be triggered on the 1st? Or is the setting recurring-contribution-specific -- I set the next recurring date for a specific day?

**Comment by KarinG** [comment]
It's an (optional) organization specific setting - if you set it to 01 and 15 then indeed you'd get all recurring contributions processed on the next possible allowed date. Technically: the credit card is tokenized at the time a contribution is created [e.g. 10] - a recurring series record is created - the recurring series is populated with the next_sched_contribution_date (closest next possible allowed date) [that would be 15 in this case].

**Comment by adixon** [comment]
re: editing the next scheduled recurrance date - that's possible with this extension: https://github.com/adixon/ca.civicrm.contributionrecur

I'm planning to copy that specific functionality into the iats extension for the next release.

But this is separate from the new functionality of setting specific next schedule dates. That new functionality work using a pre hook that just pushes the next scheduled date forward to the next allowable date [okay, it's a bit more complicated than that, but I'll leave the full details to the wiki posting].

**Comment by lcdservices** [comment]
cool, I'll check it out.
do you by chance have ballpark for when the version that includes this feature will be released?

**Comment by adixon** [comment]
Couple of weeks? Still futzing with code, then we've got a fair amount of testing to run through.
