### ISSUE TITLE
Recurring processing bug on the UK processor (for AUD)

### ISSUE THREAD

**Issue by mlutfy** [iATSPayments/com.iatspayments.civicrm#117]
As a visitor, when using the online contribution form to process a recurring contrib with credit card on a site using the AUD currency (against www.uk.iatspayments.com), I run into "Invalid currency selection: AUD for domain www.uk.iatspayment.com".

Looking at the code, the error seems to come from CRM/iATS/iATSService.php :

        case 'www.uk.iatspayments.com':
           if ('cc' == substr($method,0,2)) {
             if (in_array($options['currencyID'], array('AUD','USD','EUR','GBP','IEE','CHF','HKD','JPY','SGD','MXN'))) {
               $valid = TRUE;
             }
           }

When the error happens, the value of $method is "create_credit_card_customer".

That value seems to come from CRM/Core/Payment/iATSService.php, where it sets the method to either "cc" for a normal contribution, or "create_credit_card_customer" for recurring contributions:

    $method = $isRecur ? 'create_credit_card_customer' : 'cc';

I'm not too familiar with iATS internals, but seems safe to assume it is valid if $method is create_credit_card_customer?

(I will send a PR with a patch)

**Comment by adixon** [comment]
Yes, that was my lazy code and the methods don't always follow that convention. Thanks.

**Comment by mlutfy** [comment]
I forgot to link the PR: https://github.com/iATSPayments/com.iatspayments.civicrm/pull/118 (:

**Comment by adixon** [comment]
Done, sorry for dropping that.
