### ISSUE TITLE
Error with swipe processor

### ISSUE THREAD

**Issue by joshgowans** [iATSPayments/com.iatspayments.civicrm#119]
Just implemented the iATS Swipe processor (set to default) and tested on an iATS Magtek swiper. Running Joomla 3.4.8 and Civi 4.6.11 and received the following error on both a live and a test transaction in the CiviCRM admin:

Payment Processor Error message9002: Error happened when decrypting credit card: Index was outside the bounds of the array.

Any  help would be much appreciated.

**Comment by KarinG** [comment]
Hi Josh - I have an encrypted iATS swiper here and a physical card representing 4222222222222220 - I can try reproduce this on your instance tonight if you like.

**Comment by joshgowans** [comment]
Sounds great, thank you.

Josh

On Wed, Jan 20, 2016 at 4:21 PM, Karin Gerritsen <notifications@github.com>
wrote:

> Hi Josh - I have an encrypted iATS swiper here and a physical card
> representing 4222222222222220 - I can try reproduce this on your instance
> tonight if you like.
>
> —
> Reply to this email directly or view it on GitHub
> <https://github.com/iATSPayments/com.iatspayments.civicrm/issues/119#issuecomment-173397849>
> .
>



-- 
Josh Gowans
CiviCRM <http://civicrm.org/>, LLC
803.258.0277 | p
joshua.gowans | skype

*How you can help support CiviCRM today...*
Join the conversation on Twitter <https://twitter.com/civicrm>, LinkedIn
<https://www.linkedin.com/groups/CiviCRM-1418647>, Google +
<https://plus.google.com/u/1/communities/114972789429616596475>, and
Facebook <https://www.facebook.com/civicrm>.
Provide feedback on popular review sites such as G2
<https://www.g2crowd.com/products/civicrm/reviews>, Software Advice
<http://www.softwareadvice.com/nonprofit/civicrm-profile/> and Capterra
<http://www.capterra.com/fundraising-software/spotlight/79192/CiviCRM/CiviCRM>
.

**Comment by KarinG** [comment]
Ok - I've set your SWIPE processor to TEST88 (for LIVE). One of the advantages of iATS Payments is that you can test live pathways in CiviCRM with TEST88. I've also set up a iATS TEST88 contribution page - and I'm able to use my iATS sourced swiper with my 4222222222222220 (white) card - which when swiped looks like this for an IDTECH:

02B701801F422300039B%*4222********2220^PAYMENTSTESTCARD/IATS^***********************?*;4222********2220=***************?*BD76D88AA305F08F5C2E6634204DE5C8C089E8FC1E1083551675FD19FFA3847F1A49ABC18F1DB6002ED0FE851544DB0A10C174BE92589BEFC3EEF7810906C85B103E40966886E05DD200E10987B6A2F918A6087138858434C9BE01DE0D54EF4D0D6A1A5F8A34A1E194D885414895953B72ECC0405546DCF6035E78D7BDCC3A43A5EED1CD223A07AB70232D8A3FC073D3C8170736F266783AFFFF738139000420023A512903

And I was able to successfully complete the contribution. This is a live transaction - so I'm in your recent contributions for $1.11 - before I delete it - you can have a look at it. Errors decrypting the card may be the result of 1) a partial swipe or 2) swiping a real credit card into a test88 account [that will not work]. I don't have an encrypted MagTek handy here - but if you can process the string above but are consistently getting errors with the MagTek - we will start looking into that direction.

**Comment by stephenbiats** [comment]
This is a secure message.

**Comment by joshgowans** [comment]
Test transaction in admin using TEST88 and using stephenbiats' test data above worked. Using a live card on a test of live transaction yields much different data. Example of such here:

%B4270820030598896^GOWANS/JOSHUA             ^18062010000400301000000?;4270820030598896=18062011617130104?

Seems like something is missing compared to what's been posted above.

**Comment by KarinG** [comment]
I've edited your comment - looks to me like you don't have an encrypted MagTek - this only works if the MagTek or IDTech is purchased from iATS Payments.

**Comment by KarinG** [comment]
Of course if you think this is not resolved - please feel free to re-open.
