### ISSUE TITLE
Double * required (on 3 of the ACH/EFT fields)

### ISSUE THREAD

**Issue by KarinG** [iATSPayments/com.iatspayments.civicrm#122]

**Comment by adixon** [comment]
Can we get a couple more details? Which form?

**Comment by KarinG** [comment]
All public contribution ACH/EFT forms

**Comment by KarinG** [comment]
![acheft](https://cloud.githubusercontent.com/assets/5340555/12554862/b356f45c-c33b-11e5-8753-06986882015c.png)

**Comment by adixon** [comment]
Ah, now I understand, fascinating. Looks like some of the bits in my form modifications are now in core!

**Comment by adixon** [comment]
Fixed in 5bb6190d8147e1effb01eae15e24d8828c2d1b22
