### ISSUE TITLE
LineItems not copied - for next recurring contribution - 4.6

### ISSUE THREAD

**Issue by KarinG** [iATSPayments/com.iatspayments.civicrm#123]
I thought this was working... - but on 4.6 - semper-it.com - master branch
$1: consisting of three LineItems: $0.25; $0.35 and $0.40 - Net Amount = $1
recurring contribution: next contribution:
$1: consisting of one LineItems: $0.40 - Net Amount = $1

![lineitems](https://cloud.githubusercontent.com/assets/5340555/12760586/50273aee-c9a4-11e5-904b-c84597238beb.png)

**Comment by adixon** [comment]
Hmm, i think it does sometimes work, or has in the past.

The method for picking a template for a recurring contribution is a bit arbitrary, and it seems likely it doesn't work well in some circumstances.

In this case, it appears that when the contribution is created, either it's not finding all the line items of the original template, or else it's not writing them all.

I could imagine this is related to a change in the api, but we'd have to put in some break points (in the recurring job) to see where it goes wrong.

**Comment by adixon** [comment]
So far, it looks like a plain old bug. When I'm getting a template and find line items, instead of creating an array of them, I only end up with the last one. Fix being committed now.

**Comment by KarinG** [comment]
Merci!
