### ISSUE TITLE
SOAP-ERROR: Parsing WSDL

### ISSUE THREAD

**Issue by JoeMurray** [iATSPayments/com.iatspayments.civicrm#125]
A client starting having trouble yesterday suddenly putting through charges to IATS due to the following errors on their donation pages and event registration pages both front office and back office (site changed to 'example' in the following):
Thu Feb 04 10:18:43 2016] [warn] [client 70.70.161.158] mod_fcgid: stderr: PHP Fatal error:  SOAP-ERROR: Parsing WSDL: Couldn't load from 'https://www.iatspayments.com/NetGate/ProcessLink.asmx?WSDL' : failed to load external entity "https://www.iatspayments.com/NetGate/ProcessLink.asmx?WSDL", referer: https://www.example.com/civicrm/event/register?_qf_Confirm_display=true&qfKey=5c8149e03b13592993f2586fa97035ee_8431
[Thu Feb 04 10:18:43 2016] [warn] [client 70.70.161.158] mod_fcgid: stderr:  in /home/example/public_html/sites/all/civicrm_ext/com.iatspayments.civicrm/CRM/iATS/iATSService.php on line 142, referer: https://www.example.com/civicrm/event/register?_qf_Confirm_display=true&qfKey=5c8149e03b13592993f2586fa97035ee_8431
[Thu Feb 04 10:18:43 2016] [warn] [client 70.70.161.158] mod_fcgid: stderr: PHP Fatal error:  Call to a member function __getLastResponseHeaders() on a non-object in /home/example/public_html/sites/all/civicrm_ext/com.iatspayments.civicrm/CRM/iATS/iATSService.php on line 182, referer: https://www.example.com/civicrm/event/register?_qf_Confirm_display=true&qfKey=5c8149e03b13592993f2586fa97035ee_8431

I see someone in Drupal started having similar error messages with their very different wrapper communicating with IATS a couple of days ago: https://www.drupal.org/node/2660586#comment-10823668

**Comment by JoeMurray** [comment]
The line running into the problem is:
```
    try {
      /* until iATS fixes it's box verify, we need to have trace on to make the hack below work */
      $soapClient = new SoapClient($this->_wsdl_url, array('trace' => 1,'soap_version' => SOAP_1_2));
```

**Comment by adixon** [comment]
Fascinating ... that wsdl is actually now replaced by a new one (as of a Nov 22 commit), but I can see it's not yet in a release. 

On the other hand, it would surprise me that iATS would have stopped supporting it, so I suspect it's related to their change in the certificate, as per
http://home.iatspayments.com/Relaunch-SHA256

Can you check their host and make sure that's not the issue? It's likely related to a php and/or openssl version.

**Comment by stephenbiats** [comment]
iATS has not retired the original WSDL.  The problem is as per Alan, iATS retired TLS1.0 and moved to TLS1.1/1.2 and SHA-2.  Please have a look at the link http://home.iatspayments.com/Relaunch-SHA256 and check if your environment is compatible.

**Comment by JoeMurray** [comment]
The sysadmin is compiling openssl and PHP right now. The client's server was running openssl 0.98 on a conservative stable Linux that is due for upgrade this month. I'll reopen if that doesn't fix things.

**Comment by JoeMurray** [comment]
Odd there were no log entries when code specified TLS 1.2 on that line but system only supported 1.0.

**Comment by adixon** [comment]
Is this a request? The soap/ssl layer is outside of the scope of this extension (it's kind of a separate dimension ...). The new requirement was in a communication from iATS to all existing clients. And the reason the requirement changed was because no one should be using those older protocols anymore.

**Comment by JoeMurray** [comment]
Oh, I'm fully in favour of the upgrade, and someone at my client's missed the communication. I was just disappointed in the php call not generating an error when asked to use an unavailable protocol. I didn't mean to reopen, just add a comment. No feature request, as it is a bit moot at this point.

**Comment by KarinG** [comment]
For the record - there were a number of communications by iATS Payments on this to both existing iATS clients and iATS partners. I hope your client wasn't experiencing too much inconvenience - but there was plenty of notice re: this security upgrade.

**Comment by adixon** [comment]
Ahh, okay. Good error reporting at the right place is an ongoing battle all the way up the stack it appears. In the old days I think 'conservative stable' was often a good idea, but in the fast moving world of security and new abilities to break old protocols, it's no longer enough. Perhaps something similar befell Stephen Harper?

**Comment by JoeMurray** [comment]
I've asked Stephen about what is involved in becoming an IATS partner. Not
sure what happened in my client's internal systems.
