### ISSUE TITLE
Duplicate transactions

### ISSUE THREAD

**Issue by jamesgaede** [iATSPayments/com.iatspayments.civicrm#126]
Using Drupal 7.42, CiviCRM 4.5.6, Extension version 1.4.2.  We often get duplicate transactions, and this problem has been occurring for over a year and across various different versions of drupal, civicrm and the extension.  There is no duplication in CiviCRM's records, but on iATS side there is.  The transactions maybe close together in time (i.e., a second), but have been separated by larger intervals.  

Not sure what information would help assess this problem further, so please let me know.  Thanks!

**Comment by stephenbiats** [comment]
Do you have a duplicate test environment?  We have had a few partners create duplicate test environments where the cron jobs and the account details are still live, causing duplicate transactions.

**Comment by jamesgaede** [comment]
How do you mean test environment?  Like a whole separate development version of the site?

**Comment by stephenbiats** [comment]
Yes.  Even a sandbox where testing is done before made live on production server.

**Comment by jamesgaede** [comment]
Ok.  Yes, I do have one.  But how could it be causing a duplicate transaction?  The two sites are not on the same server, don't have the same databases, and are thus not in sync in so far as the transactions are coming in on the live site.    More to the point, if this is the problem, what should I do to fix it?  

Thanks for your assistance, by the way.

**Comment by stephenbiats** [comment]
Stop all payment processing cron jobs or disable all Payment processors should do the trick.  Check your processing section and see if there are any login credentials in the iATS processor setup – if there are, that could be the problem.

**Comment by jamesgaede** [comment]
Ok, will do.  The problem was intermittent, so I won't be able to verify for some time.  I'll mark the problem closed for now, and come back to it if need be.  Thanks again.

**Comment by KarinG** [comment]
Hi James - the other way to get duplicate transactions intermittently is: a) with older CiviCRM versions -> double clicking the Make Contribution button is not disabled with JavaScript (in 4.6.x it is). and b) even in newer versions of CiviCRM if a donor has JavaScript disabled - AND - double clicks the Make Contribution button. I've filed an issue with CiviCRM Core on that: https://issues.civicrm.org/jira/browse/CRM-17769

**Comment by jamesgaede** [comment]
I strongly suspect this is the cause for me, as I do have an older version of CiviCRM installed at present and often the transactions are basically simultaneous.  I'll update asap, and keep an eye on the issue too.  I suspect most users who have disabled their javascript will not be double-clicking, but who knows.


On 2/17/2016 3:36:53 PM, Karin Gerritsen <notifications@github.com> wrote:
Hi James - the other way to get duplicate transactions intermittently is: a) with older CiviCRM versions -> double clicking the Make Contribution button is not disabled with JavaScript (in 4.6.x it is). and b) even in newer versions of CiviCRM if a donor has JavaScript disabled - AND - double clicks the Make Contribution button. I've filed an issue with CiviCRM Core on that: https://issues.civicrm.org/jira/browse/CRM-17769 [https://issues.civicrm.org/jira/browse/CRM-17769]
