### ISSUE TITLE
Scheduled jobs get re-enabled on Civicrm menu rebuild

### ISSUE THREAD

**Issue by lolas-freeform** [iATSPayments/com.iatspayments.civicrm#127]
One client wants to manage the recurring payments in the IATS backend and turn off the polling from CiviCRM. This is not working because the jobs are getting re-enabled.

To reproduce: Disable the two managed scheduled jobs then run civicrm/menu/rebuild&reset=1. They are re-enabled.

According to these references we should be able to modify the hook_civicrm_managed definition and add the 'update' key to the entity array for the job, setting it to 'never' so that local changes (in this case disabling the jobs) are not overwritten.
https://forum.civicrm.org/index.php?topic=35466.0
https://wiki.civicrm.org/confluence/display/CRMDOC/hook_civicrm_managed

This does seem to work:
`
     return array (
      0 =>
  
      array (

        'name' => 'Cron:Job.Iatsacheftverify',

        'entity' => 'Job',

        'params' =>

        array (

          'version' => 3,

          'name' => 'iATS Payments Verification',

          'description' => 'Call into iATS for approvals, etc.',

          'run_frequency' => 'Hourly',

          'api_entity' => 'Job',

          'api_action' => 'iatsacheftverify',

         'parameters' => '',

        ),

        'update' => 'never', // This is the new line

      ),

    );

`

**Comment by lolas-freeform** [comment]
Sorry for the multiple edit updates. The code markdown doesn't seem to want to work for me.

**Comment by adixon** [comment]
Yeah, I've been annoyed with this as well, I didn't know about that update option, that's excellent, thanks.

Also - re: managing recurring contributions from civi - we're hoping to get more support for that into the extension in the near future. It's not the verification script that you want to turn off though, it's the one that generates the contributions. In fact, the updates in planning would expand the verification script to pull in from iATS all the recurring contributions that are being generated from them (i.e. the verification script pulls data from iats, the recurring script is the one that pushes new contributions).

**Comment by adixon** [comment]
Done,  06021e0
