### ISSUE TITLE
Recurring Contributions Scheduled Job occasionally re-activates even when manually disabled by admin

### ISSUE THREAD

**Issue by highfalutin** [iATSPayments/com.iatspayments.civicrm#129]
Version: 1.5.0
CiviCRM: 4.6.10

The extension automatically adds two Scheduled Jobs to the civicrm/admin/job screen. We wanted to disable one of these jobs - Iatsrecurringcontributions. (In our case, it was because we wanted to invoke the specific job directly from cron, on a different schedule from the rest. But other users may simply want to turn off recurring payment processing temporarily while leaving the extension otherwise active.)

However, whenever I disabled the recurring job on the civicrm/admin/job screen, it magically re-enabled itself after awhile. This has caused a headache for us, and could be quite a nasty surprise for others.

I believe this is because the jobs are constructed as "managed entities". I patched the code as follows and am hoping it will fix the problem:

```
--- api/v3/Job/Iatsrecurringcontributions.mgd.php	2016-02-19 09:44:12.000000000 -0700
+++ api/v3/Job/Iatsrecurringcontributions.mgd.php	2016-03-21 23:07:22.000000000 -0700
@@ -18,5 +18,6 @@
       'api_action' => 'iatsrecurringcontributions',
       'parameters' => '',
     ),
+    'update' => 'never',
   ),
 );
```

Is there any reason not to include `'update' => 'never'` in the managed entity configurations for both of the extension's jobs?

**Comment by adixon** [comment]
Yes, that's the correct solution (for 4.5+). See the duplicate issue here:
https://github.com/iATSPayments/com.iatspayments.civicrm/issues/127

**Comment by highfalutin** [comment]
Thanks, and sorry for not finding that duplicate issue myself.​
