### ISSUE TITLE
Incorrect job name on wiki page

### ISSUE THREAD

**Issue by highfalutin** [iATSPayments/com.iatspayments.civicrm#132]
Under documentation for how to [Run the Recurring Job at a Specific Time](https://github.com/iATSPayments/com.iatspayments.civicrm/wiki/Recurring-Contribution-Job#run-the-recurring-job-at-a-specific-time), shouldn't the job be `job.iatsrecurringcontributions`, not `job.recurringgenerate`?

**Comment by adixon** [comment]
Yes, thanks, fixed.

**Comment by shaneonabike** [comment]
This still caught me can you change the wiki to reflect the changes. Thanks!

**Comment by adixon** [comment]
Ah, you're right, there were multiple places that needed to be updated. Now done, and thanks.
