### ISSUE TITLE
Ready for CiviCRM 4.7?

### ISSUE THREAD

**Issue by alifrumin** [iATSPayments/com.iatspayments.civicrm#137]
When do you think this extension will be ready for use with civicrm 4.7?

We tried to install it for a client with a fresh wordpress and civicrm set up and it wasn't working our current operating theory is that this is because of how the folders were reorganized for civi for 4.7.

**Comment by KarinG** [comment]
There are still too many issues with 4.7 core - like it's not sending out proper transaction/credit card receipts. I should have a better idea on whether we can move forward on this at/after the upcoming Sprint at CiviCON next month. 

PS - note: I don't think folder structure has changed between 4.6 and 4.7

**Comment by KarinG** [comment]
Actively working on this now. Stay tuned. If you have a develoment/staging environment - you can have a sneak peak/test master branch.
