### ISSUE TITLE
can't access civicrm/admin/contribute/iatssettings unless admin user (drupal uid 1)

### ISSUE THREAD

**Issue by jmcclelland** [iATSPayments/com.iatspayments.civicrm#142]
This maybe a core bug instead of an IATS bug... but I noticed that I can fix the problem by changing:

```
-<access_arguments>access CiviContribute, administer CiviCRM</access_arguments>
+<access_arguments>access CiviContribute,administer CiviCRM</access_arguments>
```
I think the core code should probably trim out extra spaces.

**Comment by adixon** [comment]
Ah, this feels like a familiar mystery, thanks for fixing [committed, 69c82b2]. I suspect the access CiviContribute is probably redundant anyway.

**Comment by jmcclelland** [comment]
Thanks  - so quick!
