### ISSUE TITLE
$receive_date

### ISSUE THREAD

**Issue by KarinG** [iATSPayments/com.iatspayments.civicrm#144]
I think this is also a notice that has been outstanding - I could be wrong but I don't think this is the result of the repeattransaction refactoring. 

Notice: Undefined variable: receive_date in _iats_process_contribution_payment() (line 1214 of /Applications/MAMP/htdocs/buildkit/build/dmaster/sites/default/files/civicrm/ext/com.iatspayments.civicrm/iats.php).

line 1214:
$complete = array('id' => $contribution_id, 'trxn_id' => $trxn_id, 'receive_date' => $receive_date);

$receive_date is not in scope here - can't evaluate that. There are $params['receive_date'] in the UKDD section earlier on (lines 494-508) - perhaps these are the ones that need to be sent over to completetransaction API?

**Comment by adixon** [comment]
Yeah, that should be $contribution['receive_date'].

I'd guess it's not a necessary parameter - the receive date was set earlier when the contribution was created. I probably originally included it to make sure the completetransaction call didn't change it. Probably worth reviewing the completetransaction api call to see if that value is expected or processed.

**Comment by KarinG** [comment]
Yes it's not necessary - [receive date is properly populated without it].

completetransaction does not need it - here's what Eileen sends over:

      civicrm_api3('Contribution', 'completetransaction', array(
        'id' => $pending['id'],
        'trxn_id' => $payment['trxn_id'],
      ));

Shall we remove it?

**Comment by adixon** [comment]
No, there are cases where the extension prefers an earlier receive date (i.e. 'catchup' mode). Fixed in commit dde0bb14c8ff9ac50557951e857d15bd7539e95c
