### ISSUE TITLE
Notice re: $contributionResult

### ISSUE THREAD

**Issue by KarinG** [iATSPayments/com.iatspayments.civicrm#146]
Notice: Undefined variable: contributionResult in civicrm_api3_job_iatsrecurringcontributions() (line 384 of /Applications/MAMP/htdocs/buildkit/build/dmaster/sites/default/files/civicrm/ext/com.iatspayments.civicrm/api/v3/Job/Iatsrecurringcontributions.php).

In the activity create section:
        'source_record_id' => CRM_Utils_Array::value('id', $contributionResult),
Problem is that $contributionResult only gets created further up if:

   if (count($errors)) {
      ++$error_count;
      ++$counter;
      /* create a failed contribution record, don't bother talking to iats */
      $contribution['contribution_status_id'] = 4;
      $contributionResult = civicrm_api('contribution', 'create', $contribution);
      if ($contributionResult['is_error']) {
        $errors[] = $contributionResult['error_message'];
      }
      if ($email_failure_report) {
        $failure_report_text .= "\n Unexpected Errors: ".implode(' ',$errors);
      }
      continue;
    }

**Comment by adixon** [comment]
Fixed with commit e32c40d8dee5f6d48edf4dd792cf0f54cf8f9be1
