### ISSUE TITLE
Activity records don't link through to corresponding contribution

### ISSUE THREAD

**Issue by jake-mw** [iATSPayments/com.iatspayments.civicrm#148]
Activity records created by the extension, "Attempted iATS Payments Recurring Contribution for $X," don't set the source record ID correctly. So when clicking "view", the user is taken to an arbitrary unrelated contribution record, rather than the corresponding failed/completed contribution record for that activity.

This can be traced to the following code in api/v3/Job/Iatsrecurringcontributions.php:

```
    civicrm_api('ContributionRecur', 'create', $contribution_recur_set);
    $result = civicrm_api('activity', 'create',
      array(
        'version'       => 3,
        'activity_type_id'  => 6,
        'source_contact_id'   => $contact_id,
        'source_record_id' => CRM_Utils_Array::value('id', $contributionResult),
        'assignee_contact_id' => $contact_id,
        'subject'       => "Attempted iATS Payments $subtype Recurring Contribution for " . $total_amount,
        'status_id'       => 2,
        'activity_date_time'  => date("YmdHis"),
      )
    );
```

The $contributionResult doesn't exist within the scope of this function. I assume this once lived together with iats.php:: _iats_process_contribution_payment, where that $contributionResult is set?

**Comment by jake-mw** [comment]
Related to #146

**Comment by adixon** [comment]
Your analysis and diagnosis correct, thanks.

**Comment by adixon** [comment]
Fixed, thanks.
