### ISSUE TITLE
Cannot edit/view card on file due to fatal errors

### ISSUE THREAD

**Issue by konadave** [iATSPayments/com.iatspayments.civicrm#153]
When viewing a recurring contribution, clicking the view link for card on file results in

> Fatal error: Call to a member function attributes() on a non-object in /.../com.iatspayments.civicrm/CRM/iATS/Page/IATSCustomerLink.php on line 23

Clicking the edit link for card on file results in
> Fatal error: Unsupported operand types in /.../com.iatspayments.civicrm/CRM/iATS/Form/IATSCustomerLink.php on line 69

On production server results in WSoD.

Found this is happening due to the customer code not existing. Don't know why but the oldest 200-300 recurring contributions are being reported this way, while the remaining 2000ish newer ones work fine.

The extension should probably handle this situation better. This is what I find in Drupal watchdog.

```
a:2:{s:8:"!request";s:350:"<pre>stdClass Object
(
    [GetCustomerCodeDetailResult] => stdClass Object
        (
            [any] => <IATSRESPONSE xmlns=""><STATUS>Success</STATUS><ERRORS/><PROCESSRESULT><AUTHORIZATIONRESULT>Error : The customer code doesn't exist!</AUTHORIZATIONRESULT><CUSTOMERCODE>A12345678</CUSTOMERCODE></PROCESSRESULT></IATSRESPONSE>
        )

)
</pre>";i:0;i:7;}
```

CiviCRM 4.6.19.0
iATS Payments 1.5.3
Drupal 6.38

**Comment by KarinG** [comment]
Thanks for the detailed report - agreed. Will get onto the list.

**Comment by adixon** [comment]
Fixed in branch master, also for one-time cc charge attempts.

You now get an alert and empty form/page.
