### ISSUE TITLE
Box Journal v2 - not pulling data in properly - re: ACHEFT verification

### ISSUE THREAD

**Issue by KarinG** [iATSPayments/com.iatspayments.civicrm#155]
Daily journal pulls (-1, -2 etc.) are working properly - but anything that would be pulled in the date-range box so -5 days ago (or further back) can not be verified/completed at the moment in 1.5.3

**Comment by KarinG** [comment]
Marking this 4.6 and 4.7

**Comment by tamarmeir** [comment]
Hi Guys,

Sent a direct message to Karin G on mattermost but she must be busy with other things - however, we have a situation where now the iats_verify table isn't populating at all, not just 5 days back - is this due to the same issue?

We are on civi 4.7.12 and iATS v1.5.4-alpha

If there has been a patch made to master since Sep. 19 - please let us know so that I can have Mathieu go in and grab it and update our client environments....

**Comment by adixon** [comment]
Yes, we have a new release from last week which I'd recommend.

I'm not sure if what you're experiencing is related to what Karin posted here or not, it sounds like it might be a different issue. If it's been an issue since your last iats extension update, then I'd suspect that before anything else.

**Comment by tamarmeir** [comment]
Thanks for getting back to me Allen - I will let Mathieu know and have him look into things and will get back to you as to the outcome....

**Comment by tamarmeir** [comment]
Hi Allen,

Well, updating our environments doesn't seem to have resolved the issue, but it does sound different from the one reported here - I will open a separate ticket for you to review and determine if otherwise.

Thanks as always for your time!

**Comment by adixon** [comment]
I believe the original issue here has been resolved with 9b3bd95778e9b1e5179d4b5b270beb92af1003f7

The csv file from iATS was a bit erratic - some headers had extra spaces before them, so that patch strips them out and a long list of notices has now disappeared.

**Comment by adixon** [comment]
Okay, figured it out - perhaps from when we switched to reportlinkv2 back a year ago, it looks like the ach box journal and box journal rejects now requires a start and end index or else they default to 0 and they only give you one record.

Patch forthcoming.

**Comment by adixon** [comment]
Done, the key code is in this commit: ce8ed16d98c330d40ed56cad3dc32c516c46a32f
I also set defaults for those methods in the core service object in this commit: 1a0c192c8135785e9e5ebfef7fff4707d5a4239e

**Comment by tamarmeir** [comment]
Hi again,

So, Mathieu updated the extension with the commit you provided - can we expect the verification job to verify contributions from the prior 30 days or is it only contributions moving forward? We ran the verification in a client environment and nothing was verified from the previous 30 days (even though contributions are pending from Oct. 27), so not sure if this is the 5 day issue that has yet to be fixed or if it signals that the verification is still not working?

Not sure how to speed up the testing process on our end without having to wait 24 hours to see if the transaction is verified?

Thanks again for all the time you are spending on this!

**Comment by tamarmeir** [comment]
Just noticed in another client environment that we now have contact names populating the iats payments admin table in the GUI, so I think we are good, although it looks like the update to older contributions is still limited - a particular client had contributions updated back to Nov. 8, but not before even though they are still within the 30 day period - is that still an issue then?

**Comment by adixon** [comment]
Tamar - this is not your issue, it's an iATS-specific issue and the patch will fix things retroactively.
