### ISSUE TITLE
in 4.7 - Email notifications for recurring are sent out by default (unlike in 4.6)

### ISSUE THREAD

**Issue by KarinG** [iATSPayments/com.iatspayments.civicrm#157]
So we need to adjust the settings /civicrm/admin/contribute/iatssettings - Not checking Enable email receipting for each recurring contribution - no longer means that emails will not be sent.

**Comment by KarinG** [comment]
Will add this to my todo list.

**Comment by adixon** [comment]
This used to just get passed on to the complete contribution api call. Now that we're using a different api call, we'll have to figure out whether it's being supported. There might be a different design for suppressing/enabling receipt emails.

**Comment by KarinG** [comment]
This is a blocker I think for 4.7?

**Comment by adixon** [comment]
Easy enough, repeattransaction api accepts the same is_email_receipt parameter. I'm now passing it in with  f21c0ce9328f101df3c8ba18bc82659783687fda and just tested it and it appears to be working.
