### ISSUE TITLE
"Error Fetching HTTP headers" on Recurring Contributions

### ISSUE THREAD

**Issue by allenthehusband** [iATSPayments/com.iatspayments.civicrm#158]
We are setup with iATS for credit/debit card and ACH transactions and are in the last stages of testing. One time card and ACH contributions are working. For the sake of testing, we are doing daily recurring contributions to make sure the mechanism works. We haven't yet tested recurring ACH. Recurring credit card transactions are going through, but with mixed results.

**Issue**: Within the last week, we've gotten intermittent errors during the recurring contribution scheduled job that prevents the contribution from being marked Complete in Civi. The error is "Error Fetching HTTP Headers."

**Symptoms**: Two transactions with through perfectly (Aug 17 12:00am; Aug 23 12:00am) and emailed automatic receipts. The other transactions, however, are processing (visible in iATS' journal and with my bank), but marked Pending (Incomplete Transaction) in Civi. The Civi source reads: iATS Payments Recurring Contribution (id=2) Unexpected Server Error, please see your logs. Emails for these Pending transactions did not send.

**Details**:

In the Job Log for iatsrecurringcontributions: The job last night started at 2016-08-24 00:00:04 and then finished at 2016-08-24 00:01:07 with these details:

> Parameters parsed (and passed to API method): a:1:{s:7:"version";i:3;}
> 
> Full message: Finished execution of iATS Payments Recurring Contributions with result: Success (1 contribution record(s) were processed.
> 
> Failed to process recurring contribution id 2: Unexpected Server Error, please see your logs 
> Created activity record for contact id 203)

In looking at the Drupal logs, I have two relevant records for last night's Pending (Incomplete Transaction), an error and a notice, both from hostname 127.0.0.1.

**The error**:

```
SoapFault: SoapFault Object (
[message:protected] => Error Fetching http headers
[...a long list of arrays detailing the transaction, our iATS information, API calls and drush commands]
[previous:Exception:private] => 
[faultstring] => Error Fetching http headers
[faultcode] => HTTP
)
```

**The notice**:

```
Raw Response:
HEADER:
BODY:
BODYEND:
```

Attempted Resolution: From initial searches in Stackexchange and Google at large, it might be a server setting, perhaps? After a couple days of trouble initially, I increased two settings in my /etc/my.cnf file just to test and then restarted httpd and nginx:

```
max_allowed_packet = 128M (was 16M)
wait_timeout = 300 (was 60)
```

Since I still had the issue two nights ago and last night, it must be something else. **Any ideas on how to resolve the "Error Fetching http headers"?**

Yesterday, I also tried increasing the default_socket_timeout from 120 to 300 in my php.ini file just for the sake of trying a different setting, but no luck there either.  The next thing to try is perhaps making keep-alive: false for the soap call somehow, or scheduling the daily SOAP call for the recurring contributions job to happen at a different time (perhaps 12:30am) so it doesn't get lumped in with the iATS payment verification job (which happens on the hour).

Civi 4.6.14 (will be updating to 4.6.20 before go-live); Drupal 7.44; iATS Payments extension 1.5.3; CentOS Linux 7.2.1511; Plesk 12.5.3; PHP 5.6.24 on website; PHP 5.4.16 on command line; nginx 1.11.1; Apache 2.4.6

Initially posted at SE (http://civicrm.stackexchange.com/q/14544/105), then KarinG suggested I post on the issue queue here.

**Comment by adixon** [comment]
Cool ...

I don't think the mysql or socket timeouts are going to make a difference. I can confirm that your versions of civi/drupal/centos look close enough to some known working versions, I think it's probably something outside of that.

It's curious that it was successful for the first two and then started failing. There is a separate job for the recurring contributions that get initiated from CiviCRM compared with the ACH/EFT verification job. Can you identify the difference between the first two successful ones vs. the failing ones?

The flow of creating an contribution via the recurring job is:
1. Create a pending contribution.
2. Try and submit it to IATS.
3. Complete or Fail according to the response from iATS. Actually, if the response from iATS is indeterminate, then leave it as pending, because for all we know, it might have gone through.

**Comment by allenthehusband** [comment]
Hi Alan, I'll dig in today what made the one on the 17th and 23rd go through but the others haven't.  I tried yesterday turning off the iATSrecurring scheduled job in Civi and using a server based drush/cron run at 00:30.  The server based drush/cron run overnight did nothing (not even signaling a contribution in Civi at all), but when I got to work this morning, I ran the same exact drush command manually.  Went through with flying colors, transaction in Civi marked as complete, email sent, everything.  The command I used was:

`drush -r [ROOT LOCATION ON SERVER] -l [SITE URL] civicrm-api -u [USERNAME] job.iatsrecurringcontributions --quiet`

If I manually 'Execute Now' the scheduled job in Civi, I get success as well.  Any ideas why the manual runs are working, but the automatic ones either fail completely (automated drush) or only get halfway (Scheduled job)?

Thanks for any and all help, and I'll see if I can find some helpful logs for the 17th and 23rd.

**Comment by KarinG** [comment]
Perhaps the automatic ones are not run as -u your webuser but as another user - different env - different drush? 

My favourite/most stable/like clockwork (no drift) way to run the recurring contributions job is:

to switch it OFF in the scheduled jobs GUI

and then to:

# apache crontab for drupal/civicrm
0 2 * * * /usr/bin/php /usr/local/bin/drush.php --root='/var/www/platform/site/' --uri='https://site.org' -u 1 civicrm-api job.iatsrecurringcontributions auth=0 -y

# and then run the scheduled jobs that are switched ON:
3 * * * * /usr/bin/php /usr/local/bin/drush.php --root='/var/www/platform/site/' --uri='https://site.org' -u 1 civicrm-api job.execute auth=0 -y

**Comment by allenthehusband** [comment]
Thank you Karin, I'll give that a shot and we'll see what it does tonight.

**Comment by allenthehusband** [comment]
Alan, I'm afraid my logs didn't show much of anything regarding why the two charges on the 17th and 23rd went through and the others didn't.

However, Karin, you got things working (with slight alterations)!  The cron jobs worked (with an amendment to where drush was installed on my server) when used in conjunction with the scheduled job enabled.  With the scheduled job on, and your cron command for job.execute running at 6 * * * *, the contributions have been working as planned.  Then, with the specific cron you had for job.iatsrecurringcontributions, last Sunday when it tried to run (and it seemed to hit iATS server being down for maintenance or something), the cron job kicked in somehow and worked for that.  So, all told, I'm not sure of the full reason why things are working, but with my server configuration and your recommendations, I'm going to take it!  Thank you so much!

**Comment by allenthehusband** [comment]
Karin, if you did a copy/paste on to the SE question for this, I'd gladly mark your answer as accepted.

**Comment by KarinG** [comment]
Hey - glad you got things going! :-) I'll copy my answer to SE and will also add it to our README.md -
