### ISSUE TITLE
Email links to edit or cancel recurring contributions not working

### ISSUE THREAD

**Issue by mikaweinstein** [iATSPayments/com.iatspayments.civicrm#160]
We recently set up iATS for Civi 4.6.16. When we process a test recurring payment, there are links in the confirmation email that should allow you to edit or cancel your contribution. When you click on either of those links, it brings you ([here](https://www.iatspayments.com/NetGate/ProcessLinkv2.asmx?WSDL)). Screenshot also attached. 

![editrecurring](https://cloud.githubusercontent.com/assets/21317523/18063012/3e2d7cfc-6df7-11e6-915e-2c1d88da2775.jpg)

**Comment by KarinG** [comment]
Ah yes - you'll need to hit edit on the message template and replace that section with text like: "To make edits to your recurring contribution please contact our office at: ..."

From within CiviCRM - staff will be able to edit $amount, next_scheduled_date, installments, update credit card (and/or expiry date).
