### ISSUE TITLE
Cancel recurring ACH/EFT contribution broken? Receive Network Error message 

### ISSUE THREAD

**Issue by joemcl** [iATSPayments/com.iatspayments.civicrm#161]
We're on Civi 4.6.21, Drupal 7 and I've just updated to iATS extension version 1.5.3. 
I'm attempting to cancel a long-running (over a year) recurring iATS ACH/EFT contribution using Cancel under Recurring Contributions in my own user record. 
I'm getting the error message "Network Error - Unable to reach the server. Please refresh this page in your browser and try again." 
I've cleaned up the cache using Administer -> System Settings -> Cleanup Caches.

**Comment by adixon** [comment]
You'll want to check your server logs for this, sounds like a php or apache error. Pretty sure it's unrelated to the iATS extension, though.

I have had occasional issues with the Cancel link, an easy work around is to just edit it instead and change the status to Cancelled.

**Comment by joemcl** [comment]
Alan - not sure where I "edit it instead and change the status to Cancelled". And will that actually cancel the recurring ACH/EFT? 

Here's the sceenshot of the error message when I right click the Cancel link and open in another browser tab - 
![iatscancelerror](https://cloud.githubusercontent.com/assets/3912434/18601342/52a93a30-7c30-11e6-8c0c-c88e69dc525d.png)

**Comment by joemcl** [comment]
So I changed the recurring contribution status in the civicrm_contribution_recur table, added a cancel date, set auto recur = 0 .

**Comment by adixon** [comment]
There should be an edit link beside the cancel link when you're looking at the contribution tab, down at the bottom where the recurring contribution list is.

That error makes it look like it couldn't find the right payment processor for that recurring contribution (it was testing whether the payment processor supported cancelling via civicrm.

Your manual adjustment sounds right.

**Comment by joemcl** [comment]
Alan, thanks - yeah I'm running both Authorize and iATS, and I had *disabled* iATS processing to try to kill that recurring contribution, so duh on me. Editing in the table seems to have done the trick to cancel the recurring.
