### ISSUE TITLE
4.7 .12 RepeatTransaction API -> defaults to payment_instrument_id = 4 (i.e. check)

### ISSUE THREAD

**Issue by KarinG** [iATSPayments/com.iatspayments.civicrm#162]
Will log issue in JIRA - but have found a way to address this - by using a combination of our own template and repeattransaction API.

**Comment by KarinG** [comment]
No - forget that - passing it (determined from our own templating) on to repeattransaction API is not sticking - payment method remains 'Check' - in view contribution e.g. 
https://www.semper-it.com/civicrm/contact/view/contribution?reset=1&action=update&id=3452&cid=2&context=dashboard

```
+        // KG repeattransaction defaults to payment_instrument_id = 4 so grab this from our $contribution:
+        'payment_instrument_id' => $contribution['payment_instrument_id']

```

**Comment by adixon** [comment]
Curiously, this isn't happening on my test site.

On the other hand, I am seeing some fascinating notices that repeattransaction is doubtful about where to find the payment processor, so I wonder if this is something funky about your civi install.

**Comment by adixon** [comment]
Okay, got it - see my note here: https://issues.civicrm.org/jira/browse/CRM-16923

Short version, it's an issue with the repeattransaction api, I'll file a PR shortly.

In the meantime, I'm also working around it in the extension. It's only affecting recurring payments attached to payment pages that have more than one payment processor, I'm not sure if we should be bumping up the version that we should use the repeattransaction api with or not.

**Comment by twomice** [comment]
@KarinG or @adixon I'm trying to track down this issue as we're hitting it on a client site now. Do you recall a JIRA issue for this problem "RepeatTransaction API -> defaults to payment_instrument_id = 4"? The one Alan mentions (CRM-16923) seems to be about payment_processor_id, not payment_instrument_id.

**Comment by KarinG** [comment]
What version are you on Allen?

**Comment by twomice** [comment]
I'm on 4.7.16, @KarinG

**Comment by adixon** [comment]
Yes, there have been a couple of related issues about selecting the right processor id and payment instrument id in the last few months, since the issue you found.
