### ISSUE TITLE
4.7 repeatransaction workflow: 2 emails per 1 completed recurring contribution

### ISSUE THREAD

**Issue by KarinG** [iATSPayments/com.iatspayments.civicrm#163]
One Email without Transaction ID + Total Amount + date 12:00 (generic)
Second Email with Transaction ID + the rest is identical other that date/timestamp is correct [does not just default to 12:00]

We need to find a way to stop the first email from going out.

**Comment by adixon** [comment]
So this is about how the repeattransaction works - it assumes the actual transaction has happenned and CiviCRM just needs to record it (i.e. it's still go the IPN workflow/process baked in), and there's no way to tell it the status (or various other things, e.g. the receive date).

Which means we need a slightly different flow inside the _iats_process_contribution_payment() function..

**Comment by adixon** [comment]
Okay, the function has been refactored and now it only sends out one email on success, but the bad news is it's the one without the transaction or date and it's being triggered within the repeattransaction api so we have no way of controlling that from the iATS extension. I still need to test that I haven't messed up 4.6.

**Comment by adixon** [comment]
Actually, it's worse than that - the contribution itself is messed up. The omnipay code follows the pattern of creating as pending via repeattransaction and then completing it via the api, so I went back to that model and it started resending multiple emails again. So - I'll swap it back to just doing it once and then clean up afterwards.

**Comment by adixon** [comment]
Aha, now that I know how to suppress email receipts when using repeattransaction, this can be fixed up and my flow can go back to the right way (create as pending, then complete). Testing this now ...

**Comment by adixon** [comment]
Success, closing, commit here: f21c0ce9328f101df3c8ba18bc82659783687fda
