### ISSUE TITLE
1st credit card contribution in a recurring series not completed

### ISSUE THREAD

**Issue by waddyvic** [iATSPayments/com.iatspayments.civicrm#165]
Hi,

When using this extension to create recurring credit card contribution, if the allow date is set to today only, the 1st contribution is always set to pending, and the receive_date is set to 3am in the morning today. Looking at iATS journal, there was no transaction posted in either approved or rejected. It seemed like the contribution was never posted to iATS server.

If the allow date is disabled (i.e. recurring contribution can be processed on any day), the 1st contribution will be processed correctly and has a "completed" status.

Reading the source code in iats.php, line 520 stated that "when creating a recurring contribution record via a civicrm contribution form we've already taken the first payment, so calculate the next one (core assumes the intial contribution is pending)". For my situation, since current date falls under the allowed date for recurring contribution, I was expecting the first contribution to be processed right away instead of pending. Unfortunately I have limited knowledge in CiviCRM's hook system, so I don't know how to fix that. Also I could not find in CiviCRM's backend GUI to trigger processing these pending contributions. Any tip is appreciated.

**Comment by adixon** [comment]
If you set restricted dates for the recurring transaction, the first one won't actually be transacted, and Civi will create a pending record as a placeholder.

Then every actual transaction will run, leaving that initial pending record as a ghost.

What should happen is that the first actual transaction contribution in the series should pick up and use that pending record, but it doesn't (yet), so you can just delete those old pending records for now (but not until one has actually gone through, because Civi really wants at least one contribution per recurring series.

For your case - if you want that recurring series to transact on the day it's created, you'll have to make sure that you run the recurring transaction job at the end of the day to pick it up. You can run it multiple times at a day, safely (assuming it's all working properly, of course ...).

It would be smarter for the code to recognize that it can run the normal way if the current day is an allowed day.

**Comment by waddyvic** [comment]
Thx for your clarification Alan. I now have a better understanding of how CiviCRM designed its recurring contribution system.

I tried your suggestion to run the job on the same day, and noticed a potential bug. When the recurring contribution is created via "Submit Credit Card Contribution" page, if the current date is within the restricted date setting, the recurring contribution record in "civicrm_contribution_recur" table will not have a "next_sched_contribution_date" value; instead, it's null. As a result, running Job.iatsrecurringcontributions does not pick up any recurring contribution to process. If I manually set the "next_sched_contribution_date" to current date, but an earlier time, the job will pick up the recurring contribution and properly processed it. We're still using civicrm 4.5.5 and don't have the luxury to upgrade at the moment. Do you think this is a bug in CiviCRM's core, or something in the extension itself?

Beside this, when running Job.iatsrecurringcontributions and it successfully process a recurring contribution, CiviCRM sends out a receipt email even though the setting in the extension for auto-email receipt was not turned on. Do you have any insight into this, too?

Thx a bunch.

**Comment by adixon** [comment]
Most of this recurring functionality is handled by the iATS extension, not core, and the next_sched_contribution_date should be set by the extension.

I'm not sure why it isn't - what version of the extension are you using? It could be a bug.

re: receipts - yes, there are some versions of extension+core where the extensions' attempt to suppress the receipts fails. A simple work around is to set the field in the recurring record that controls this (i.e. set it to 0).

**Comment by waddyvic** [comment]
I'm using v1.5.3. I'll try and find out as well. Thx.

Victor Huang - sent from my iPad

? 2016?9?27????3:02?Alan Dixon <notifications@github.com<mailto:notifications@github.com>> ???


Most of this recurring functionality is handled by the iATS extension, not core, and the next_sched_contribution_date should be set by the extension.

I'm not sure why it isn't - what version of the extension are you using? It could be a bug.

re: receipts - yes, there are some versions of extension+core where the extensions' attempt to suppress the receipts fails. A simple work around is to set the field in the recurring record that controls this (i.e. set it to 0).

-

**Comment by waddyvic** [comment]
Found this pull request:

https://github.com/iATSPayments/com.iatspayments.civicrm/pull/103

Is this related to the next_sched_contribution_date issue I encountered?

**Comment by waddyvic** [comment]
I found out why next_sched_contribution_date wasn't set. In iats.php line 519 - 527:

if ($type != 'iATSServiceUKDD' && !empty($params['next_sched_contribution_date'])) {
        $settings = CRM_Core_BAO_Setting::getItem('iATS Payments Extension', 'iats_settings');
        $allow_days = empty($settings['days']) ? array('-1') : $settings['days'];
        if (0 < max($allow_days)) { // force one of the fixed days, and set the cycle_day at the same time
          $init_time = ('create' == $op) ? time() : strtotime($params['next_sched_contribution_date']);
          $from_time = _iats_contributionrecur_next($init_time,$allow_days);
          $params['next_sched_contribution_date'] = date('YmdHis', $from_time);
          $params['cycle_day'] = date('j', $from_time); // day of month without leading 0
        }

The code only sets next_sched_contribution_date and cycle_day when next_sched_contribution_date is not empty. However, in my situation, next_sched_contribution_date is empty, so this block of code didn't get executed. Is this check put in for a particular reason? If not, will taking out the check affect other code that I'm not aware of?

I tried taking out the "&& !empty($params['next_sched_contribution_date'])" part, and it worked for me.

**Comment by adixon** [comment]
Hmm, fascinating. I think something else might break if you take that out.

That code should only be running for an existing recurring record, not on the initial creation.

The problem is earlier, that it's not getting created with the initial record.
