### ISSUE TITLE
Receive Date is being changed to a future date for non-recurring contribution

### ISSUE THREAD

**Issue by jmcclelland** [iATSPayments/com.iatspayments.civicrm#168]
We have the "Restrict allowable days of the month for recurring contributions." configured to just the 1st of the month.

However, when a non-recurring contribution is made, it seems to be processed on the day it was received, a receipt is sent out (all good so far) however, in CiviCRM, the receive date is changed to the 1st of the following month at 3:00 am.

I am under the impression from the label of the "Restrict" field that it would only apply to recurring contributions.

Also, I'm not sure what the purpose of changing the receive date would be in this situation.

**Comment by adixon** [comment]
You are correct, this would be a bug. Looks like this line in iats.php, it should be testing if it's from a recurring series.

```
 if ($type != 'iATSServiceUKDD' && $objectName == 'Contribution') {
        // new, non-UKDD contribution records in a schedule are forced to comply with any restrictions
        if (0 < max($allow_days)) {
          $from_time = _iats_contributionrecur_next(strtotime($params['receive_date']),$allow_days);
          $params['receive_date'] = date('Ymd', $from_time).'030000';
        }
}
```

**Comment by jmcclelland** [comment]
Thanks Alan for the response. I can work on a PR, but wanted to clarify how this feature is supposed to work.

If my site is restricted to processing recurring contributions on the first of the month and someone makes a recurring contribution on October 15th, what exactly happens? For example:

 * The contribution is processed with received date set to October 15th and next scheduled contribution is set to November 1st.
 * The contribution is processed with received date set to October 15th and next scheduled contribution is set to December 1st.
 * The contribution is not processed now. It's received date is set to November 1 (and it is processed on November 1). Then the next scheduled date is December 1st.

I'm still not sure I quite understand this feature.

**Comment by adixon** [comment]
The original design spec (driven by a specific client) was that it wouldn't be processed until the 1st (i.e. your option 3). The other options don't seem unreasonable, though part of the logic for them is to make sure the cc is actually valid, so I think option 3 is probably the best option as a default.

On the other hand, there is now some support for this function in core that I haven't looked at, and at some point the two options should get merged I think.

**Comment by jmcclelland** [comment]
Hi Alan - Right, that makes sense. I think option three is the best option of all of them (and honestly the only option worth supporting).

I'm not sure the first option should even be allowed (if you made a contribution on October 31st, your card would be billed on October 31st and the next day on November 1 for a once a month contribution).

Also, I just realized that a number of fixes to recurring contributions have been made to the code since I last updated it on our production servers (1.5.3) that explains some of my additional confusions (specifically, an abandoned pending contribution was created on recur that now seems fixed).

**Comment by jmcclelland** [comment]
This PR seems to fix the problem I identified. Thanks for all your work on this extension!

**Comment by adixon** [comment]
Perfect, thank you.
