### ISSUE TITLE
recurring receipts sent from the wrong address (when cron job executed on drupal site via drush)

### ISSUE THREAD

**Issue by jmcclelland** [iATSPayments/com.iatspayments.civicrm#170]
Receipts that are sent when a recurring contribution is triggered are sent from the email address of the CiviCRM contact associated with the drupal user id that is passed to drush. For example:

`drush -u 1 -r /var/www/powerbase civicrm-api job.execute -y`

This command specifies that it should be run as the Drupal uid 1, which corresponds to a CiviCRM contact.

It seems to be present in the current 4.7 version of CiviCRM and the current version of the iATS extension.

It was also reported in #98, but that issue was closed as being fixed with an upgrade.

I think it might be a CiviCRM issue, but it especially affects iATS because recurring contributions are triggered by a cron job.

- The `_iats_process_contribution_payment()` calls the completetransaction API, and it properly tells it whether or not to send a receipt. I think that's it for the iATS code's responsibility.
- `civicrm_api3_contribution_completetransaction` calls `_ipn_process_transaction()`
- `_ipn_process_transaction` calls `CRM_Contribute_BAO_Contribution::completeOrder`
- `CRM_Contribute_BAO_Contribution::completeOrder` calls 'sendconfirmation' API, but it only sends the contribution_id and the payment_processor_id - no additional parameters.
- `civicrm_api3_contribution_sendconfirmation` allows you to pass in the from email and from name, it then calls `CRM_Contribute_BAO_Contribution::sendMail`, passing on the from name and email if it was given that info.
- `CRM_Contribute_BAO_Contribution::sendMail` in turn will set the from name and email to the current logged in user if they are not set.

It seems like the problem is with CRM_Contribute_BAO_Contribution::sendMail. It perhaps should try to use a a default from name/address rather than use the currently logged in person.

**Comment by adixon** [comment]
I would guess that the logic of using the logged in user as the from address would be for backend contribution receipts being sent from whoever input the contribution.

One flavour of workaround would be to run the recurring contribution job separately from your regular system jobs and specify a more appropriate Drupal user.

But yes, the completetransaction and repeattransaction api still have some wrinkles like this that we're working on before we're happy with a 4.7 release.

**Comment by jmcclelland** [comment]
I just opened an issue upstream:

https://issues.civicrm.org/jira/browse/CRM-19657

I have a PR that tries to use the default site-wide from address rather than the logged in user. Let's see if that makes it in.

**Comment by adixon** [comment]
Great. There's also an issue and PR for fixing the issue that triggers this one, here:
https://issues.civicrm.org/jira/browse/CRM-19601

**Comment by axon-obriend** [comment]
I just got hit with this at a client. Glad to know it's been addressed. Thanks so much.

I've looked at the referenced core issues and PRs and it's not clear to me what happens after the fix. When a receipt goes out for a payment after the first one in a recurring series, will the system default email be used, or the "From" email address that's configured on the contribution page?

**Comment by adixon** [comment]
CRM-19601 allows this extension to prevent the email from going out.

If you are sending out email receipts with every recurring contribution, then I think there is still a challenge related to the from address it comes from.

**Comment by axon-obriend** [comment]
We noticed the problem after we turned on the configuration to generate receipts for subsequent recurring contributions (which seems like it should be the default, but that's another issue).

I'll have to dig in a little deeper. In the short term, I'll change the email address associated with the cron user. This client is on 4.7.9 and due an upgrade.

**Comment by adixon** [comment]
Default email receipt behaviour for recurring contributions - yes, it's off, and that's our experience with most organizations. I know that all the organizations to which I make a monthly donation don't send me a receipt for each one. But maybe we're a bit backwards up here in Canada ...
