### ISSUE TITLE
MasterCard expands their BIN range

### ISSUE THREAD

**Issue by herbdool** [iATSPayments/com.iatspayments.civicrm#171]
A client got this email from iATS and asked us if anything needs to be done. Anything need to be done in this extension?

> Take action to accept MasterCard’s expanded BIN range
> Dear Client:
> MasterCard® is expanding their bank identification number (BIN) range to meet the growing needs of the payment processing market. You may need to make changes to your processing system in order to process these new cards.
> Here’s what you need to know about this change
> What is a BIN?
> BINs are the first six digits of the card number. They identify the issuing institution for each customer account and enable transactions to be routed.
> What’s changing?
> MasterCard currently uses the BIN range of 510000–559999. Beginning June 30, 2017, anyone accepting MasterCard payments will also need to accept the new “2 series BIN” of 222100–272099. The new BIN range will be used in the same way as the existing range.
> We’ll be able to test, accept, route and process the new BINs by November 14, 2016. We’re here to help you prepare for this change.
> Here’s what you need to do
> If you purchased software from a third-party software provider, contact your vendor to determine whether a patch or version upgrade is required to process the new account numbers.
> If you have coded to one of our formats, your developers must determine whether the code has any dependency on identifying cards as MasterCard by looking at the BIN range or the first digit of the card for a “5”. If there is such a dependency, adjust your code to also identify cards in the 222100–272099 BIN range as MasterCard. You can run unattended testing with us to test these transactions.
> If you have coded to one of our formats and process EMV transactions, you’ll need cards with chip data. To obtain EMV test cards, contact your EMV test tool vendor, likely either ICC Solutions or UL Brand Test Tools (Collis).

**Comment by KarinG** [comment]
Hi Herb - I can assure you iATS is ready for this - and when I checked on this in CiviCRM core - one of our CiviCRM Partners had already put in a PR [ https://issues.civicrm.org/jira/browse/CRM-19283 ] for this as well (CiviCRM core also does some credit card validation as people are entering credit card numbers and it there is some javascript which determines the card type ]

**Comment by adixon** [comment]
Yeah, it's a good question.

The easy answer is that it's warning you of a change that won't happen until next June 30, and there's nothing we can even do to test until Nov 14, so the short answer is, no action is required.

The longer answer is what Karin just said, that it's not an iATS specific issue at all, but a change that will be required in Civi core, and someone has already done it.

**Comment by herbdool** [comment]
Is it being back ported to 4.6?

**Comment by KarinG** [comment]
Already done: 

Fix Version/s:
4.6.22, 4.7.12
