### ISSUE TITLE
iATS_verify table not populating for 4.7

### ISSUE THREAD

**Issue by tamarmeir** [iATSPayments/com.iatspayments.civicrm#173]
Civi 4.7.12
iATS master branch as of Nov. 10, 2016

ACH contributions are being created and communicated to iATS, iATS is processing those contributions successfully, but those contributions are not being updated in Civi. This started immediately after update to Civi v. 4.7.12 on Oct. 27, 2016 and while still using iATS v. 1.5.4-alpha. We are not sure how to test without having to wait 24 hours for ACH to settle - perhaps you have that capability? 

This is what Mathieu Lutfy during troubleshooting (no further detail available):

1) Schedule a recurring ACH contribution, after the first installment, the civicrm_contribution.invoice_id is NULL ?

2)  iATS-ACH transactions are not logged in civicrm_iats_verify but are visible in the UI (Contributions > iATS Payments Admin), the admin UI uses data from civicrm_iats_request_log / civicrm_iats_response_log 

[From Tamar: until the update, the UI showed contact names, after update, no contact names appear next tot he transactions) - see screen shot.
![iats_verification_issues](https://cloud.githubusercontent.com/assets/14094020/20194712/c566e9e6-a750-11e6-9563-30ef6f2ba731.png)

3) If I search for the invoice_id (6b2ce23cb37926dc8aac7449cbf95a27), I don't find a contribution. but if I search for the amount+date, I find the contribution

4) Will add debug statements and check back in tomorrow

Hoping you can look into this as well - for us it's a really big haystack and an ever bigger issue for our clients.

Thanks!

**Comment by adixon** [comment]
Right, so the verify script was broken due to other changes in the 4.7 update. Try with master and see if it's fixed now.

**Comment by tamarmeir** [comment]
Hi Alan,

This with master as of this afternoon (I had Mathieu install it before opening the ticket to see if that resolved the issue). Could you add him as a participant to this ticket so that he can respond to you directly?

Thanks!

**Comment by adixon** [comment]
Ah, got it. It appears that in 4.7 there's a new assumption that we only have trxn_id for a contribution when complete, which is not true for ACH/EFT (at least not using iATS - they give you a trxn_id before any kind of completion).

**Comment by adixon** [comment]
This issue is resolved with this patch: ca6bc8ba4b6e8c29058098558f1a31b363ef8c88

It doesn't work retroactively. It only affected 4.7.12+ (i.e. it was the use of the new repeattransaction api).

You'll want to use master to fix some other verify script issues.

**Comment by adixon** [comment]
You could possibly fix it retroactively by populating the trxn_id field of the contribution table for these contributions.

Tomorrow I'll try and see if we match them up using the invoice id instead, that might fix it retroactively.

**Comment by adixon** [comment]
Unfortunately, the invoice id was also not being saved, so you'll have to manually patch things up.

Fortunately, this exercise identified another bug.

re: missing invoice id - transactions affected were the same group as the ones not getting their trxn_id, i.e. subsequent (non-initial) contribution in a recurring schedule. It only affects the recent 4.7 sites that are using this pre-production code.

**Comment by tamarmeir** [comment]
Oh, great that another issue was identified, I guess??? Well, off to go fix
a bunch of contributions.....

Kind regards,

Tamar Meir
Forest CRM Consulting
www.forestcrmc.com
*Helping organizations see the forest through the trees*

**Comment by adixon** [comment]
Actually, the invoice id is stored in an custom iats table (and so is the beginning of the trxn_id for that matter). You might try this if you have a lot of transactions to fix, it'll restore the invoice_id at least for those contributions that have a unique amount/date combination (i.e. most of them).

`update ignore civicrm_contribution c inner join civicrm_iats_request_log l on c.receive_date = l.request_datetime and c.total_amount = l.total set c.invoice_id = l.invoice_num where isnull(c.invoice_id) AND request_datetime > '2016-09-01';`

I've just tested this on my test setup, I'd recommend you test it on yours before doing it on a live copy.

**Comment by tamarmeir** [comment]
Thanks so much, Alan! Will send to Mathieu for implementation!


Thanks, 
Tamar

**Comment by KarinG** [comment]
@mlutfy @tamarmeir - if you git pull master - you also need: https://github.com/civicrm/civicrm-core/pull/9353 - IF you want CiviCRM core to respect do not email receipts for all contributions in a series setting.

**Comment by tamarmeir** [comment]
Thanks Karin - I actually had a ticket open with Mathieu for that :-) Thought it was something on our end....

**Comment by tamarmeir** [comment]
Hi Alan,

@mlutfy updated everything and all names are now appearing retroactively on the UI iATS Payments Admin screen, but verify table has not yet been populated - I believe this is what you were referring to regarding the "next patch I'm about to push out" - will you let us know when available so we can update and see if all is now good?

Thanks again to both!

**Comment by adixon** [comment]
I'm not sure what is now appearing retroactively, but:
1. The sql above restores the invoice id for ACH/EFT recurring transactions that were missing.
2. The current master uses this invoice for the ach/eft verify script.

So running the sql, updating to the latest master, and running the verify script should verify all your ach/eft and in the process will populate that verify table.

**Comment by tamarmeir** [comment]
Hi Alan,

Having Mathieu check that he did indeed install the latest master - the sql
you provided indeed restored what it needed to restore, we just need to get
the verification working which in whatever Mathieu installed this morning
is not yet working (we checked after manually executing the verification
job).  Will let you know once done....

Kind regards,

Tamar Meir
Forest CRM Consulting
www.forestcrmc.com
*Helping organizations see the forest through the trees*

**Comment by adixon** [comment]
Did you check the job system log? It's pretty verbose at reporting what it does - how many records on iATS it downloads, how many pending contributions in CiviCRM it's looking for, and how many match up.

**Comment by tamarmeir** [comment]
Yes - I checked, but none of the contributions that were created after Oct.
27 (when we updated from 4.7.9 to 4.7.12) were updated even though I know
for a fact from the clients that they settled successfully. I've got a
question in to Mathieu now - will keep you posted.

Kind regards,

Tamar Meir
Forest CRM Consulting
www.forestcrmc.com
*Helping organizations see the forest through the trees*

**Comment by tamarmeir** [comment]
Hi Alan - just wanted to let you know that we updated to the latest latest master, used the script, ran the scheduled job and all is now beautiful! Thanks so much for your help!!!!

**Comment by adixon** [comment]
Great, happy days.
