### ISSUE TITLE
Request for Status Update on iATS extension for CiviCRM 4.7

### ISSUE THREAD

**Issue by shaigluskin** [iATSPayments/com.iatspayments.civicrm#178]
Hay folks,

My client needs a bunch of the features in 4.7 but is being held back by the lack of an iATS extension. Any news on when there will be a 4.7 version?

Thanks,

Shai

**Comment by adixon** [comment]
It's in final testing this weekend. If you want to grab the latest version and test it on a 4.7 install it should be very close, if not identical, to what we release next week. You really want to be on the latest 4.7 - some of our hold up as been in fixing the financial stuff in core.

**Comment by shaigluskin** [comment]
Thanks.
