### ISSUE TITLE
Membership Auto renewal receipt not showing on behalf of profile

### ISSUE THREAD

**Issue by anumgoel** [iATSPayments/com.iatspayments.civicrm#180]
Hi,

We are using iATS processor for an online membership page with 'on behalf of' profile turned on. When user signs up for one time membership, the email receipt looks fine and has 'on behalf of' organization details. But if user opts for auto renewal membership, then the receipt has membership info and fee section but nothing about 'on behalf of' organization. Do you know of anything that might be causing this?

We are using CiviCRM 4.6.20 and Drupal 7. 

Thanks,
Anum

**Comment by adixon** [comment]
Ah, that sounds like an unexpected complexity for the code. But definitely a core code issue, unrelated to this extension.

You could try posting to stackexchange: http://civicrm.stackexchange.com/
