### ISSUE TITLE
Status Update for 1.5.4

### ISSUE THREAD

**Issue by shaigluskin** [iATSPayments/com.iatspayments.civicrm#181]
Hmm, last I heard 1.5.4 was coming out any minute. That was about a month ago. Is there a problem?

Thanks, Shai

**Comment by adixon** [comment]
Yes, but with Civi Core - a series of contribution related regressions over the past few releases. My blog post explains our choice here: https://civicrm.org/blog/alan-dixon/diagnosing-payment-issues-with-iats-payments-and-what-about-47

The short version is - there's an rc available that we recommend if you're on 4.7.
