### ISSUE TITLE
missing upgrade_1_5_003.sql

### ISSUE THREAD

**Issue by jmcclelland** [iATSPayments/com.iatspayments.civicrm#183]
I just tried the most recent RC and got an error when upgrading:

file_get_contents(/var/www/powerbase/sites/all/extensions/iats/sql/upgrade_1_5_003.sql):  [warning]
failed to open stream: No such file or directory File.php:337

It looks like an upgrade file is defined in CRM/iATS/Upgrader.php but was not git added

**Comment by adixon** [comment]
Exactly right. I just added it and rolled a new rc-2, https://github.com/iATSPayments/com.iatspayments.civicrm/releases/tag/1.5.4-rc-2

Thank you.
