### ISSUE TITLE
Submit CC Info through GUI for Event Registrations

### ISSUE THREAD

**Issue by kngs** [iATSPayments/com.iatspayments.civicrm#185]
Is it possible to register participants through the backend GUI and enter their credit card info immediately so it is attached to the registration?  I only get the option to enter cc info for contributions, not events.

**Comment by adixon** [comment]
Yes you can, but the workflow isn't obvious. Go to the contact's summary page, then their Events tab, and there's you'll see the button you're looking for. This is unrelated to the extension, it's just how CiviEvents works.

**Comment by kngs** [comment]
Thanks - I realized after I asked it was probably Civi in general, not iATS.  I never noticed that option on Events before.  Thanks as always! Karen
