### ISSUE TITLE
Mismatch contact ID <--> 2 contacts w/ same recur_id in iats_customer_codes table

### ISSUE THREAD

**Issue by kngs** [iATSPayments/com.iatspayments.civicrm#187]
I have a recurring monthly transaction that Fails (iATS Payments Recurring Contribution (id=18) Errors: Recur id 18 is has a mismatched contact id for the customer code) and then Completes within in the same minute every month.  iATS has no record of the Failed transaction since Civi initiates the transactions.  When I went to verify the iATS customer code, I noticed two entries in the iats_customer_code table with the same recur_id, the same recur_id that is failing then completing monthly.  The erroneous contact has never had a recurring transaction, so I don't know how they got in the table to begin with.  I'm assuming this two issues are related. Can I safely delete this row from the table?

Side note: I thought I had to put the iATS customer code in the processor_ID field of the contribution_recur_id?

**Comment by adixon** [comment]
Sounds like something/someone might have been manually mucking about with your iats_customer_code table? You should definitely only have one per iats recurring contribution, and your diagnosis sounds correct. I wonder if it's related to some dedupe operation ...

In any case - yes, it's grabbing the matching entry in the customer code table based on the recur id and noticing that the customer id does not match the one that the civicrm recurring contribution table has recorded and stopping - it's a sanity check thing. If you've got two entries in the iats customer code table for the same recurring contribution id and the other one has the correct contact id, then go ahead and remove the duplicate.

re: the processor_id field and iats - no, that processor_id field is not used by the iats extension. If you imported recurring contributions id into CiviCRM from iATS, you might have populated that field as a temporary holding field.
