### ISSUE TITLE
Send recurring cancellation request to payment processors removed by iATS Payments extension

### ISSUE THREAD

**Issue by tamarmeir** [iATSPayments/com.iatspayments.civicrm#188]
Hi guys,

As weird as it sounds, this has been confirmed by Allen Shaw who wrote the following in response to an issue we had him working on:

"My examination shows that this problem is caused by the "iATS Payments" extension, which is removing the "Send cancellation request to Authorize.net [and PayPal] ?" field from the "Cancel Recurring Contribution" form; this change, in turn, causes CiviCRM to treat the cancelation as if that field were set to "No", meaning it doesn't even try to communicate with Authorize.net (or paypal) about the cancelation."

His recommendation is to disable iATS payments processor which will work for those of our clients who don't have iATS accounts, but many of the clients who have iATS accounts also have active Authorize.net or PayPal accounts, so this is an issue that should be resolved from within the extension if your findings are the same as Allen's.

Thanks as always for your time,
Tamar

**Comment by adixon** [comment]
You're right, that form modification is not playing well with others, it should be checking first that the corresponding schedule is for an iATS-managed recurring sequence.

**Comment by adixon** [comment]
Okay, this is fixed with commit a92dd620a8975469e65372b3e34c812e5130faa1
It'll be in the next release, thanks for your report and diagnosis.

**Comment by tamarmeir** [comment]
Excellent - thanks for the speedy response - will have Mathieu update our dev environment and test and let you know the outcome.

Kind regards,
Tamar
