### ISSUE TITLE
ACH/EFT Recurring Contribution Failed

### ISSUE THREAD

**Issue by kevintsimpson** [iATSPayments/com.iatspayments.civicrm#193]
ACH/EFT recurring contributions are coming back with contribution status "Failed".   This happened for 2 different contacts on the same day.

Have other people had problems with this in the past, or is it supposed to be working?

On March 15, iATS Payments Recurring Contributions scheduled job ran and "Successfully processed pending recurring contribution id <###>: OK: 555555"
On March 16, iATS Payments Verification scheduled job ran and "Cancelled iATS Payments ACH/EFT contribution id <###> for contact id <#####>".
Membership was set to grace or expired for the contact.

The contributions show up properly in iATS as successful.
The contribution worked for the first month (back in February), but the second payment (the first time it recurs) doesn't seem to be working.
Other recurring payments are working, for those using credit cards.

Versions we're using:
CiviCRM 4.6.24
 iATS Payments (com.iatspayments.civicrm) 1.4.2
Also have installed: Recurring Contributions (ca.civicrm.contributionrecur) 1.0
Drupal 7

**Comment by KarinG** [comment]
Hi - you will want to upgrade the iATS extension to 1.5.3

**Comment by kevintsimpson** [comment]
We'd actually been on 1.5.3 before, but were having the same problem, except that it was going to "Pending" rather than "Failed"; and not working for the first transaction rather than for subsequent transactions.  We'd downgraded to 1.4.2 for that reason, and thought that was working, but now we've found that it isn't for us.

We hadn't found a solution to our original problem with 1.5.3, except for downgrading.  I know you'd said that major organizations have this working with 1.5.3 - 4.6.x, so I'm guessing there's something peculiar about our setup.

The other issue we've had -- in case it's related -- is that we aren't able to do recurring transactions on the back end, using "Submit Credit Card Contribution".  We just get the spinning triangle, it processes payments in iATS, but the contribution doesn't show up in CiviCRM, and we get the error "One of parameters (value: ) is not of the type Integer".

If there's anything else you think we could check into, that could be causing this behaviour (in 1.4.2 or 1.5.3), let me know.  Thanks!

**Comment by adixon** [comment]
Yeah, you definitely want to be on 1.5.3 (hey neighbour!).

ACH/EFT is confusing compared with cc for a few reasons, so you want to understand the full flow to diagnose what's going on.

Your extra issue of the spinning triangle when doing backend recurring contributions does sound like it might be a useful clue - it sounds kind of like there's a partial communication issue between your server and iATS (perhaps php related? firewall?).

Feel free to drop me a direct line with more details if you think it'll be helpful.
