### ISSUE TITLE
It does not Ver 2.9 does not record the correct financial_type_id of recurring contributions in the civicrm_line_item table

### ISSUE THREAD

**Issue by IowaBoy1** [iATSPayments/com.iatspayments.civicrm#198]
On 5/6 I updated to ver 2.9. Since then recurring donations no longer are recording the correct financial_type_id. They are receiving the contribution financial type instead of the line item financial type.

I have attached a screen shot of an Extended Report that shows the change on Sat. I think it is only impacting recurring donations.  It does not correctly record the financial_type_id of recurring contributions in the civicrm_line_item table.  
![screenshot 2017-05-08 22 22 54](https://cloud.githubusercontent.com/assets/28285267/25852890/bc222a50-347f-11e7-8f4e-9298f3ef4b61.png)

I have also attached a spreadsheet from the civicrm_line_item table of a recurring contribution. The contribution schedule is every other week. This is the last 3. You can see in the highlighted column (which is financial_type_id column) that the last one got a different Financial Type.
[civicrm_line_item export.xlsx](https://github.com/iATSPayments/com.iatspayments.civicrm/files/986714/civicrm_line_item.export.xlsx)

I checked and my Price Sets still have the correct Financial Type associated with them. This would explain why new contributions process correctly.

**Comment by adixon** [comment]
Can you be a little clearer about versions? Of CiviCRM and of the extension? And which one you upgraded?

**Comment by IowaBoy1** [comment]
Civi 4.7.17
iATS 2.9 

On 5/6 (3 days ago) I upgraded the iATS extension to 2.9

**Comment by KarinG** [comment]
Sorry - I'm very confused about 2.9 and what that is? We released 1.6.0 last week - before that stable was 1.5.3;

**Comment by IowaBoy1** [comment]
Opps. It is iATS Extension 1.6 
2.9 is the version for Extended reports.

**Comment by adixon** [comment]
Okay, thanks. Can you also tell us what you mean by 5/6?

I should note that line items on recurring contributions are inherently tricky. Recurring contributions are generated by 'cloning' the 'original' contribution, including it's line items. It looks like that process might be failing in some way, and you're getting a fallback, simplified donation.

By "failing" - I mean it's unable to find an appropriate match, so it's likely there is some change to the recurring schedule that has happened to prevent that match. What you can do is edit the most recent recurring contribution in a series and it will use that as the template for the next time it generates a recurring contribution.

Why this happened with the upgrade - the process of generating the details of the recurring contribution is now in CiviCRM core, so the extension is now using that where possible, I expect that's why it changed.

**Comment by IowaBoy1** [comment]
5/6 was the date I did the update of the extension

**Comment by IowaBoy1** [comment]
So you are saying that this is a Civi bug?

**Comment by adixon** [comment]
No, not necessarily. Did you understand my explanation of what might be different with this version from the previous version you had installed? Basically - there's no obvious canonical way to create a recurring contribution's line items if the amount gets modified. How this is done changed in the latest version. If you're not getting what you want, you can just edit the most recent one and the next one should use that as a template.

**Comment by IowaBoy1** [comment]
These are not modified recurring donations. They are just run of the mill
recurring donations that have been happily recurring until now.

I will edit them and see if the next time around they process correctly.

**Comment by IowaBoy1** [comment]
Update:
As adixon suggested, I have been editing the recurring donations with the correct Line Item Financial Type. We had the first one reprocess since being edited. It still recorded the wrong Line Item Financial Type. 

Just to clarify the problem since there seems to be some misunderstandings:
Using: WordPress 4.7.5
CiviCRM 4.7.17
iATS Payments 1.6

Since updating to iATS 1.6, Recurring Contribution no longer record the correct Line Item Financial Type. They are receiving the Financial Type of the Contribution rather than the Line Item. These recurring donations had been processing correctly before the update to 1.6. No one edited the amount, date schedule, frequency, etc. which would throw of the "template." 
I have attached a spreadheet that shows which column in the line_item table is not correctly populating.
[civicrm_line_item.export.xlsx](https://github.com/iATSPayments/com.iatspayments.civicrm/files/1030439/civicrm_line_item.export.xlsx)


I'm not sure if this is a CiviCore problem or an iATS  Payment extension problem since adixon says Core is now handling some of this.

**Comment by KarinG** [comment]
Checking that the financial types are recorded properly for recurring contributions is part of our test-matrix. And that has been working properly in iATS Payments Extension 1.6.x and CiviCRM Core 4.7.x

It simply models the recurring contributions after the initiating contribution which was made online and with a priceset that has three options and a different financial type for each of those options.

Here's a test series: $4 - Main Financial Type = Donation but the amount is split over 3 different line-items, each with their own Financial Type: Fund1 - Financial Type,Fund2 - Financial Type,Fund3 - Financial Type

![image](https://cloud.githubusercontent.com/assets/5340555/26475443/3114c0c8-4175-11e7-98c0-c5401681259a.png)

![image](https://cloud.githubusercontent.com/assets/5340555/26475428/1d413932-4175-11e7-8b32-fababd8a2b00.png)

**Comment by KarinG** [comment]
I don't have Extended Reports installed on my test site - but as you can see in my screenshot above - the LineItems all have the Financial Types - so it would very unlikely that if I look at it with Extended Reports I'd be seeing something different.

**Comment by KarinG** [comment]
I hope you get to the bottom of why this isn't working for you. Please keep us posted. Unless you can tell us how to reproduce this - there really isn't anything we do to help (either with the iATS Extension or w/ Core).

**Comment by IowaBoy1** [comment]
This has nothing to do with Extended Reports. Extended reports does not populate the tables. that comes from CiviCore or iATS Payments. Look at the spreadsheet I attached. It is exported straight from the database civicrm_line_item table. The table civicrm_line_item column financial_type_id is not getting the line item financial type, it is getting the contribution financial type. As I already said, these are recurring contributions that have been corrctly processing until I updated to iATS Payments 1.6

I have attached some view contributions screenshots to match what you are looking at in your screenshot. They are from the same recurring contribution. The one has the correct line_item financial type and the the other has what we get since the update. This contribution has been recurring for months without issue. It processes every two weeks.
![screenshot 2017-05-25 17 31 42](https://cloud.githubusercontent.com/assets/28285267/26476175/cb4dcbd4-4171-11e7-9575-62337352fc07.png)
![screenshot 2017-05-25 17 31 59](https://cloud.githubusercontent.com/assets/28285267/26476176/cb4f295c-4171-11e7-926d-0b55dda3d758.png)

Ihave no idea how to tell you to duplicate the problem. I have set up a price set group with Financial Types with each one and then contribution page that uses that price set. I think it is just a normal use of price sets. If you do not have a real world setup to test line item contributions on,  would be happy to do a chat/screenshare with you so you can see it in person.

**Comment by IowaBoy1** [comment]
KarinG, Is your screenshot showing the first donation? The first one does it correct. It is the consecutive recurring contributions that are wrong.

**Comment by KarinG** [comment]
No - it's not the initiating contribution - you can tell by the Source field -> it has the recurring series ID in it. 

I don't doubt that this is what you're observing but I'm unable to reproduce this with an even more complex priceset. 

As adixon tried to explain above previously we were templating in the iATS Extension - but now we have CiviCRM core do this b/c it's repeattransaction API is now getting the bookkeeping bits right. So whether it grabs the first one, or the last one, or the first successful one after a failed attempt - those decisions are now made by CiviCRM Core. 

If you start a new series -> and look at the first recurring contribution in that series - same issue? What other Extensions (besides Extended Reports and the iATS Extension) do you have installed? You're on 4.7.17 -> CiviCRM 4.7 core still has financial bug fixes - so I suggest you upgrade to 4.7.19

PS - my tests are full live real world - and even the pricesets are far more complicated that they would be in most real live scenarios. And I have over a dozen client/sites using our iATS Payments Extension.

**Comment by adixon** [comment]
The "Donation" financial type is often a default, so my guess is that the generation of line items in your case is failing to match the original ones for some special reason. There are a few places in core where the logic is like this.

Can you check your logs for helpful messages? If it is doing some kind of hail-mary guess, core sometimes leaves a helpful notice behind that may only show up in your CiviCRM server logs.
You can try out my new log viewer here if it's helpful: https://github.com/adixon/ca.civicrm.logviewer

Am I understanding that the label on the line item is correct? That seems to indicate that most of the process of generating line items is correct, it's just the financial type of the line items that is the problem.

**Comment by IowaBoy1** [comment]
I do not see View Log. Under Administer -> Administration Console -> I see   System Status & Configuration Check List. Do I not have it in the right place? wp-content/plugins/files/civicrm/ConfigAndLog

**Comment by adixon** [comment]
No, the log viewer is an extension, it goes in your extension directory.

**Comment by IowaBoy1** [comment]
So put it here? wp-content/plugins/civicrm/civicrm/CRM/Extension  
Previously, I just followed the Readme.md path.

**Comment by adixon** [comment]
No, you'll need to read the instructions, here: https://wiki.civicrm.org/confluence/display/CRMDOC/Extensions
The short version - there's no single place where you always store your extensions, they can be in different places, and you'll start by configuring the default place via the web interface, in the CiviCRM admin pages. Then you drop the extension into the place you've configured.
If you already have working extensions installed, then you can just go into your CiviCRM admin pages to find out the location you need to drop new ones.

**Comment by IowaBoy1** [comment]
Thanks adixon, I have it installed.

**Comment by IowaBoy1** [comment]
KarinG or adixon, have either of you tested a single item recurring contribution? Did you get the same results that I do?

**Comment by KarinG** [comment]
Confirming that I've reproduced this issue. Will open a CiviCRM Core JIRA ticket for it.

**Comment by IowaBoy1** [comment]
Glad to have it narrowed down. Hope the fix comes soon. It is a pain in the a-- to edit all the recurring donations.

**Comment by KarinG** [comment]
LineItem - screenshot - initiating transaction is ok; subsequent recurring transaction is not. 

financial_type = 1 should be = 5

![image](https://cloud.githubusercontent.com/assets/5340555/26812974/492b22e4-4a38-11e7-8e72-3336be0394cb.png)

Again this is a CiviCRM Core issue - and have opened a JIRA ticket: https://issues.civicrm.org/jira/projects/CRM/issues/CRM-20685 - please comment on the Issue/Ticket there - hopefully it will get some attention soon. You can help speed along CiviCRM Core bug fixes if you are in a position to be able to help fund the fix.

**Comment by IowaBoy1** [comment]
What does funding for something like this generally run?



                      <https://radiusinternational.org/>
<https://www.facebook.com/Radius-International-196452240407903/>
<https://twitter.com/radiusint>  Cell: 619-874-6855

**Comment by IowaBoy1** [comment]
What does funding for something like this generally cost?



                      <https://radiusinternational.org/>
<https://www.facebook.com/Radius-International-196452240407903/>
<https://twitter.com/radiusint>  Cell: 619-874-6855
