### ISSUE TITLE
Problem with TEST88 user?

### ISSUE THREAD

**Issue by jmcclelland** [iATSPayments/com.iatspayments.civicrm#200]
Although it has worked in the past... when I try to do a test-drive contribution, I get the following:

Payment Processor Error message :9002: Agent code has not been set up on the authorization system. Please call iATS at 1-888-955-5455.

My test account is set to:

User: TEST88
Password: TEST88

Site url: https://www.iatspayments.com/NetGate/ProcessLink.asmx?WSDL
Recurring payments url: https://www.iatspayments.com/NetGate/ProcessLink.asmx?WSDL

Any ideas?

**Comment by KarinG** [comment]
Hi Jamie - I've had that happen too - where TEST88 has been down for bit. If this persists - please let me know and I'll check in with iATS - Partner Support.

**Comment by shaunagm** [comment]
I'm experiencing this problem as well, when attempting to make a donation at https://connect.lawyerscommittee.org/make-a-donation-to-election-protection/.  The footer and the query string in the URL both say they use civicrm.

**Comment by KarinG** [comment]
They would not be using TEST88 though - I mean that looks like a live site; if you get Payment Processor Error message :9002: Agent code has not been set up on the authorization system there - then they may not have configured the Contribution page correctly;

**Comment by shaunagm** [comment]
Right, sorry.  

I sent iATS and the host site messages through more traditional channels as well.  But I had thought there might be a deeper seated issue with iATS/civicrm, since you wouldn't expect this kind of response to be user-facing.  Definitely the wrong issue, though!

**Comment by KarinG** [comment]
No worries.
