### ISSUE TITLE
Refunded CC Contributions "Reverified" and Marked as Completed with Different Transaction ID

### ISSUE THREAD

**Issue by tamarmeir** [iATSPayments/com.iatspayments.civicrm#209]
Hi guys,

this is a weird one that I am hoping you can she light on - it seems like this behavior started right when we updated to 1.6.1-beta on civi 4.7.16. 

The first time this happened, it impacted an online contribution that was part of a recurring series that had the following activity:
1. Contribution recorded on June 9
2. Said contribution refunded on June 30
3. Said contribution re-verified on July 3rd, new transaction ID, status updated from refunded to completed, still grayed out as if refunded, (new civi financial items created on July 3)

My thinking is that the reason that other refunded contributions were NOT impacted was because they were more than 30 days in the past? The most recent refunded contribution before the impacted contribution is dated May 7.

The second contribution impacted was a one-time online contribution in the same client environment and had the following activity:
1. Contribution recorded on July 8
2. Said contribution refunded on July 29
3. Said contribution re-verified on July 20th, new transaction ID, status updated from refunded to completed, still grayed out as if refunded

Not sure if the issue can be narrowed down just to online contributions, but those are the only two cases we have thus far - not seeing any open issues on this so again not sure if this is something to do with our custom payment processing. 

Let me know if you need any more info in an attempt to reproduce.

Thanks in advance for your time,
Tamar

**Comment by KarinG** [comment]
Hi Tamar! Sorry for the delay in responding. How are you recording the refund in CiviCRM? I suspect by editing the status of the original completed Contribution?

Under the new reconciliation method in 1.6.1-beta - If the contribution is completed in iATS - it will be completed in CiviCRM; As you know in iATS - there are two transactions for a refund: the initial - completed transaction and then there is a second transaction with a negative amount - it has its own date - and it's own transaction ID;

So I'm not surprised that the original transactions are re-completed [after all they are completed in iATS] - I'll talk to Alan this week about how we should handle that. One thing you may want to consider is to add the refund like it appears in iATS: that is a Contribution of a negative amount - status completed - as oppose to toggling the status of the original contribution to refunded.

**Comment by adixon** [comment]
Yes, Karin's diagnosis sounds likely. Tamar - did you take a peek at this? https://github.com/iATSPayments/com.iatspayments.civicrm/wiki/Verification-and-the-Journal
The verification logs might clarify what is going on. We will need to think through cases like you're describing so we can document the right process and/or modify the verification code to consider exceptions.

**Comment by tamarmeir** [comment]
Hi guys,

Thanks for the responses - yes, the refund is done by editing the contribution and changing the contribution status from "Completed" to "Refunded". The separate, negative contribution is actually my preference, but since Civi offers the former option, then I believe Civi specific extensions should support it or override the "Refunded" capability. 

Not sure what piece of information would link the refund to the original contribution, but assuming there is a link between the two transactions, perhaps adding an exception to the verification that won't update contributions in statuses of "Cancelled" or "Refunded"? 

Similarly - if a contribution is marked as "Failed" by verification, is there ever a chance of that status changing? If not, I include "Failed" in the exception as well. 

Or, to make things more complicated, allow refunds to be processed directly through Civi and communicated to iATS when a contribution status is changed from "Completed" to "Refunded" - this should create a very clear audit trail and perhaps eliminate the need for verification? If a contribution is changed to "Cancelled", that wouldn't automatically suggest a refund as the amount paid may be applied to something different as opposed to actually being refunded. 

I manually cleaned up the transactions in the database for the client so I didn't think I would see anything of use but I ran the "iATS Payments - Journal" report anyway, I did find the original positive contribution and then the negative contribution, but not without difficulty - it seems like the original contribution was updated with the transaction and invoice ID of the refund transaction, so what it looks like in the GUI is that those IDs correspond to the original positive contribution as opposed to the refunded transaction.  Without expanding the contribution to get the original transaction details to use for search options, it is difficult to find reference to what users would see in the GUI - it would greatly facilitate reconciliation if the contact name, contribution ID, financial type, amount, etc. were referenced in the report. 

Hope this helps - let me know if you have any more questions...

Thanks,
Tamar

**Comment by IowaBoy1** [comment]
Over the weekend (10/21), I updated the iATS extension to 1.6.1. We have two contributions that we had refunded (one refunded on Oct 9th the other was refunded on Oct 16th) that changed back to completed. We have changed them back to Refunded twice and they revert back to completed.  

The original refunds were completed via the iATS dashboard then we manually edited the Status in Civi. But in 1.5 there was no communication back from iATS so we had to do it manually. I do not see a negative donation as you describe above.

We refunded another donation the first of Sept and it is not impacted.

Any ideas on what we need to do?

**Comment by KarinG** [comment]
Hi - I just double checked with Alan and we don't think there is a mechanism for this from our end; iATS 1.6.1 is for CiviCRM 4.7 (only) - are you on 4.7? The verification job only considers ACHEFT that have status = pending; I will try to reproduce this on my 4.7.25/1.6 master - can you give me some more specifics:

credit card - for sure - these are not ACHEFT?
contribution, membership or event?
one time or recurring?
front page or backend?

**Comment by IowaBoy1** [comment]
We are on CiviCRM 4.7.25
WP 4.8.2

Both donations are Recurring
One is ACH, the other is CC
Both were originally set up from a front page 

The one donation is for $250
Looking at the donor dashboard I do not see a -$250 donation. The refunded one is greyed out but says Completed and it shows up in Contribution Reports.
In civicrm_iats_journal I can see a +$250 and  -$250 entry
In civicrm_iats_verify I have 4 entries for this donation. The first one has a auth_result of Null on 10/2 (when we changed it to Refunded), The next entry has a auth_result of OK:BankAccpt on 10/20 and two more identical entries on 10/24 (the first one being the day I upgraded to 1.6.1 and the other two being after we manually changed it back to Refunded) 
![screenshot 2017-10-25 10 18 31](https://user-images.githubusercontent.com/28285267/32012836-1d421b56-b96e-11e7-9a9f-9efa6a087e2c.png)
![screenshot 2017-10-25 10 18 49](https://user-images.githubusercontent.com/28285267/32012837-1d62c856-b96e-11e7-8372-01cb833a3e4c.png)
![screenshot 2017-10-25 10 19 32](https://user-images.githubusercontent.com/28285267/32012838-1d7ff494-b96e-11e7-841c-15544c08a44f.png)

**Comment by IowaBoy1** [comment]
Myra just gave me a new piece of info. There was a third one that had been refunded that changed back to completed after the update. But is has stayed Refunded. 

It was a CC, one-time, given through an online contribution page on 9/20  
Tamar mentions a 30 day window??? This would have been at day 30 when I updated to 1.6.1 and it changed to Completed. However, on the morning of the 24th when she changed it back to Refunded, it would have been outside of the 30 day window.

For this contribution, the donor dashboard just shows the one contribution and it still says Refunded

civicrm_iats_journal just has one entry for this contribution but is it dated for 9/20. The .rst is OK:034822:Y  The .cm is CiviCRM: 4.7.22 + iATS Extension: 1.6.0

civicrm_verify has one entry for this invoice id or CID. It is only a +$25. There is not a negative entry. The .auth_result is OK:034822:Y It has a .verify_datetime of 2017-10-20 17:54:36 This is full month after the original transaction and it matches the civicrm_iats_verify.verify_datetime of the above two contributions.

FYI, in civicrm_iats_journal it is not populating the fields .financial_trxn_id .cid .contribution_id .recur_id  That just leaves .inv for search options.  And civicrm_iats_journal.verify_datetime is not populating either.

**Comment by KarinG** [comment]
I'll dive in and figure out what's core here and what's iATS Extension; 

PS "`Looking at the donor dashboard I do not see a -$250 donation. The refunded one is greyed out but says Completed and it shows up in Contribution Reports.`" 

That's definitively a core bug - I have noted this myself as well - I advise all my clients will always handle refunds as two separate transactions - just like at the payment processor level: 

- a) a completed initial transaction with a transaction ID; 
- b) a completed transaction of a negative $ amount on a different day and with a transaction ID;

It's far easier to reconcile that way;

**Comment by IowaBoy1** [comment]
I think this will only be an issue as people update and only IF they have Refunds in the last 30 days. 

From here on, everything probably will process as you expect it to.

**Comment by adixon** [comment]
Hey, thanks for this report. The verification job is trying to match up with a variety of potential status values and I was trying to be as complete as possible by only excluding Completed and Failed contributions, but I'll add in Refunded to that list as well.

And yes, you're correct that it's only looking back at contributions in the previous 30 days to do completion on.

**Comment by KarinG** [comment]
Thanks Alan - let me know when that's in.

**Comment by dinalondon** [comment]
Hi all,
Tamar was working for Jvillage when she opened this ticket on July 24th.  Other than the work around that Karin suggested:  **I advise all my clients to handle refunds as two separate transactions - just like at the payment processor level:

a) a completed initial transaction with a transaction ID;
b) a completed transaction of a negative $ amount on a different day and with a transaction ID;**

Are there any plans for resolution?  Thanks so much for an update.

**Comment by KarinG** [comment]
I just pushed a fix for this: https://github.com/iATSPayments/com.iatspayments.civicrm/commit/5f5ed32e01360e557252d8ea92b151b4fb4d7b60

Give it a try and feel free to re-open if needed;

**Comment by dinalondon** [comment]
Thanks so much!

**Comment by IowaBoy1** [comment]
Can someone give us the proper sequence for handling refunds? We had several contributions that double processed. We refunded the one within iATS. But it has not shown up in Civi as Refunded. And if we change the status of the original it changes back to completed. Do we have to manually enter the refund in Civi? It does not automatically come over from iATS?

**Comment by KarinG** [comment]
You’ll need to refund the Contribution in iATS and record it in CiviCRM manually with status = Refunded; this patch to ensure once marked Refunded remains Refunded is fairly new - so it’s likely not in your Extension yet (unless you’re on master branch);
