### ISSUE TITLE
Returned ACH: Status not updated in CiviCRM

### ISSUE THREAD

**Issue by cmmadmin** [iATSPayments/com.iatspayments.civicrm#218]
During our testing, we tested an ACH transaction with a valid routing number and an invalid account number. As expected, this transaction initially was listed as "pending" in CiviCRM and then "complete", which indicates that iATS verified the valid routing number and sent the transaction to the that bank for processing. 

However, 7 days later the bank notified iATS that the account number was invalid. At this point the transaction was registered as "returned" in iATS, however, this donation remained classified as "completed" in CiviCRM. 

We spoke with the iATS customer care team and they confirmed the returned status of the contribution should be communicated from iATS to civi and automatically updated.

Can you help us get this issue fixed?

CiviCRM v4.6.14
iATS Payments extension v1.5.3
Drupal 7.43

**Comment by KarinG** [comment]
Right so when the status in iATSPayments.com toggles to O:BankAccept (as oppsed to OK:Reject) -> the Extension will mark the Contributions as status = completed; 

Returns can occur later though -> up to a month even - so when that happens we indeed do not have an automated way to update the Contribution status of a Returned item.

Right now (as described here - http://home.iatspayments.com/developer-info/developer-faq/what-are-the-steps-involved-for-processing-live-ach-transactions/ - the org will receive an Email - notifying them of the Return; You can then go in and manually update the Status  - I've described why that is - on the README.md page of this extension: https://github.com/iATSPayments/com.iatspayments.civicrm/blob/master/README.md

Please note that ACH Returns require manually processing. iATS Payments will notify an organization by Email in case such ACH Returns occur - the reason (e.g. NSF) is included. It is up to CiviCRM administrators to handle this in CiviCRM according to your organization's procedures (e.g. if these were monies re: Event registration -> should that registration be canceled as well or will you ask participant to bring cash; if and the amount of NSF fees should be charged to the participant etc).

Other scenarios may include: revoking of Charitable Tax Receipts already issued (if the Return occurs late). 

So even though we could automated the status toggle; it will still require lots of decision making.
