### ISSUE TITLE
Card Type

### ISSUE THREAD

**Issue by cmmadmin** [iATSPayments/com.iatspayments.civicrm#220]
When a contribution is submitted, does the iATS extension capture and store the Credit Card Type (e.g., Visa, MasterCard, Amex, Discover) somewhere in the CiviCRM database?

**Comment by KarinG** [comment]
No - it does not. CiviCRM Core 4.7 does this natively (so no need for us to reproduce that). I just confirmed this for a project - it was added a couple of versions ago - and appears to be working well.

**Comment by adixon** [comment]
iATS does store the card type information, but the extension doesn't. So if upgrading to the most recent version isn't an option yet, you can pull the card type from iATS. I've been doing that for a client report for about a year now.
