### ISSUE TITLE
What is proper method to stop a recurring contribution

### ISSUE THREAD

**Issue by cmmadmin** [iATSPayments/com.iatspayments.civicrm#224]
CiviCRM 4.6.14, Drupal 7.43, iATS Payments extension 1.5.3

We are trying to figure out the best way to stop a recurring contribution. In the past, we have selected the "Cancel" link in the Recurring Contributions section as shown in Capture1. But it has been suggested to us that cancelling the contribution this way might mess up things in the background and that we should instead select Edit then set Status = "Completed", as shown in Capture2. There is also a "Cancelled" option in the Status dropdown so we aren't sure if we should use that instead. What's the best practice for stopping a recurring contribution using CiviCRM/iATS?

![capture1](https://user-images.githubusercontent.com/6864440/31566649-2e4685a4-b031-11e7-8ba5-20ef480d1cd8.PNG)
![capture2](https://user-images.githubusercontent.com/6864440/31566650-2e5cff82-b031-11e7-8b21-78798e5c143f.PNG)

**Comment by adixon** [comment]
Yeah, that's a good question. I've seen cases where cancelling did other unexpected things, so I generally recommend the edit option, though it could be the more recent 4.7 CiviCRM is more predicatable here.
