### ISSUE TITLE
Time in Next Scheduled Date slowly advancing

### ISSUE THREAD

**Issue by waddyvic** [iATSPayments/com.iatspayments.civicrm#231]
The following linke of code that calculates next collection date uses the receive date of current iteration:

https://github.com/iATSPayments/com.iatspayments.civicrm/blob/5f5ed32e01360e557252d8ea92b151b4fb4d7b60/api/v3/Job/Iatsrecurringcontributions.php#L363

This causes the time value in the next scheduled date slowly advancing each time it ran. For a small set of recurring contributions it would be fine, but if that list gets big, given enough cycles, the next scheduled date will advance to next day, and even next month. Can this logic changed to using the old next scheduled date instead of the new receive date?

**Comment by adixon** [comment]
Your best bet to prevent creep and have a predictable deposit time is to set up a dedicated cron, as per
https://github.com/iATSPayments/com.iatspayments.civicrm/wiki/Recurring-Contribution-Job

The issue with your proposal is about how it handle temporary failures. The default behaviour tries to be as nice as possible to the donor, to prevent what could end up being two donations in one month if an end of the month recurring donation didn't get processed for a few days for whatever reason. 

Catchup mode on that wiki page was designed for the kind of behaviour you want.
