### ISSUE TITLE
Two separate iATS accounts both using ACH/EFT and Credit Card

### ISSUE THREAD

**Issue by cmmadmin** [iATSPayments/com.iatspayments.civicrm#239]
We would like to use two separate iATS accounts with this Civi extension. We will have two different Agent Codes and Passwords.

Currently, we have two payment processors setup in Civi - one for ACH/EFT and one for Credit Card. They both use the Agent Code of our first iATS account.

iATS has told us we can setup a second account. We would like to use this account for all of our Event Registrations and Membership forms.

We would like add two more payment processors in Civi using the new Agent Code of our new iATS account. One for ACH/EFT and the other for Credit Card. I suspect we will need to create two more Financial Accounts in Civi as well.

Is there any reason why this shouldn't work? Is there anything we need to be sure to do in order for them not to conflict in any way? Has anyone ever used this extension with two different iATS accounts?

The reason we want to do this is so that we get separate deposits in our bank account for our Event Registration & Membership income and our Contribution income. We need separate deposits so that our reconciliation process with Quickbooks works efficiently.

**Comment by KarinG** [comment]
That will work just fine; I run a couple of projects where we do just that (mostly for purposes of separately National office vs Provincial level monies) - but technically: multiple iATS accounts within one CiviCRM instance; Keep up posted - and if you do run into any issues - do let us know.

**Comment by adixon** [comment]
Yes, definitely part of the design, though not as thoroughly tested. One tricky bit is stuff like recurring contributions and verification, that's where I'd keep my eyes peeled.
