### ISSUE TITLE
Cancel a recurring contribution / Contribution status no longer on Update Recurring Contribution page in CiviCRM 5.0.0

### ISSUE THREAD

**Issue by cmmadmin** [iATSPayments/com.iatspayments.civicrm#246]
We no longer see the Status field (In Progress, Completed, Pending, etc) on the Update Recurring Contribution page.

In Civi 4.6.x to cancel a recurring contribution we would set Status = "Completed" and remove the "Next Contribution" date. However, we noticed that the Status often reverted to "In Progress" after a short period of time. We were hoping this issue was resolved with the upgrade, but it appears the Status field is no longer shown.

What is the proper method we should use to cancel a recurring contribution? Should we use the Cancel link on the Contribution tab? Or, should we remove the Next Schedule Contribution date on the Update Recurring Contribution page? Or both?

CiviCRM 5.0.0, iATS 1.6.1

This is what we see in Civi 5.0.0:
![civi 5-0-0](https://user-images.githubusercontent.com/6864440/41165907-71885cc8-6b04-11e8-8277-3b3ea2cc2588.png)

This is what we see in Civi 4.6.x:
![civi 4-6](https://user-images.githubusercontent.com/6864440/41165870-557b143a-6b04-11e8-8767-fb96c5b1b181.png)

**Comment by KarinG** [comment]
Confirming this on 5.2.0 - we're checking into why -> but to Cancel a series -> hit More -> Cancel; Completed -> there are some checks/counts that are run to ensure a series really has been completed; Anything set to Cancel will remain Canceled;

**Comment by adixon** [comment]
The iATS extension modifies this form when it identifies the corresponding payment processor as an iATS one. The method the code uses to do this seems to have stopped working on recent releases, we will have to find out why and also check where else the code might be impacted.

**Comment by cmmadmin** [comment]
Do you feel confident that using "More -> Cancel" works to cancel a recurring contribution in Civi 5.2.1?

We are planning to upgrade our production site to 5.2.1 on July 5. If the fix for the Status field is not done by then, we are thinking we'll move forward with 5.2.1 and live without it as long as "More -> Cancel" works.

Unfortunately, it's tricky to test this on our staging site.

**Comment by KarinG** [comment]
Yes absolutely - Cancel has always been the best way to stop a recurring series from generating additional/new contributions. We just ran a test matrix on CiviCRM 5.2.2 and specifically confirmed Cancel is (still) working properly. 

Leaving this issue open as the show additional iATS fields is indeed no longer working.

**Comment by adixon** [comment]
Fixed with commit https://github.com/iATSPayments/com.iatspayments.civicrm/commit/7ab8a1a7dc6cde1b79b9020f68146b0f882573fb
Available in the next release.
