### ISSUE TITLE
Unable to edit credit/debit card using Card on File in CiviCRM 5.0.0

### ISSUE THREAD

**Issue by cmmadmin** [iATSPayments/com.iatspayments.civicrm#247]
We were unable to change credit/debit card information for recurring donations in CiviCRM 5.0.0. 

Below are the steps we normally take for this process and the results of those steps in CiviCRM 5.0.0:

1. Navigate to a contact in Civi with recurring Debit/Credit card contribution
2. Select "Contributions" from their top ribbon
3. Scroll to the bottom of the page
4. Select "View" on an active recurring contribution
5. Select "Edit" next to "Card on File"

Normally when we follow these steps we are redirected to a screen which allows us to update the contacts card information as shown below:

![picture 1](https://user-images.githubusercontent.com/6864440/41166472-e90e720e-6b05-11e8-9b5f-480ab8731370.JPG)

However, on CiviCRM 5.0.0 we are redirected to a blank screen and receive the warning message "Unable to retrieve card details from iATS. Error: The customer code doesn't exit!" as shown below:

![picture 2](https://user-images.githubusercontent.com/6864440/41166479-eed73996-6b05-11e8-99be-9954e9dbcb9f.JPG)

Note: Not sure if this is related, but we have 3 payment processors setup (1) iATS ACH (2) iATS CC (3) iATS CC. (1) and (2) use our first iATS account and are used for Contributions. (3) uses our second iATS account and is used for Events/Memberships.

CiviCRM 5.0.0, iATS 1.6.1

**Comment by KarinG** [comment]
Hi - we just updated my own iATS test/site from a 4.7.x to 5.2.0 - and I am able to update a credit card attached to a customer code - for a series that was generated with 4.7.x

Three thoughts: 
1. manually inspect the civicrm_iats_customer_codes table: look up the recur_id (recurring series id) - is there a customer_code?
2. log in on iATSPayments.com -> check the Virtual Terminal -> Customer Database
3. try updating a card for another series

Let me know what you find out.

**Comment by adixon** [comment]
My best guess is that the message you got is exactly the issue - i.e. that the corresponding client code was removed over at iATS. The other possibility is that the iATS extension isn't finding any corresponding client code, or for some reason is pulling up a wrong one.

**Comment by cmmadmin** [comment]
Thanks for your responses. I inspected recurring donations for two different donors on our staging site. Both produce the "customer code doesn't exist" error. Here's the results for Karin's questions:

Short answer: All data I've found appears valid in the db and iATS. Customer codes match in civicrm_iats_customer_codes table and Customer Database in iATS (in 1st account). The Customer Database in our 2nd iATS account is empty. Is it possible the extension is looking in the wrong iATS account?

======

Test case #1:

Donor Name: Danny V
Civi Contact ID: 167726
$240/mo
Contribution Recur ID: 7490

civicrm_iats_customer_codes table:

id: 2249
customer_code: xxxxxx824
cid: 1677206

iATS Customer Database:

xxxxxx824 exists with correct name in 1st iATS account (the one used for donations)
xxxxxx824 does not exist in 2nd iATS account (the one used for Events/Memberships) - in fact this customer database appears to be empty

======

Test case #2:

Donor Name: Maddie K
Civi Contact ID: 152541
$100/mo
Contribution Recur ID: 8065


civicrm_iats_customer_codes table:

id: 2803
customer_code: xxxxxx655
cid: 152541

iATS Customer Database:

xxxxxx655 exists with correct name in 1st iATS account (the one used for donations)
xxxxxx655 does not exist in 2nd iATS account (the one used for Events/Memberships) - in fact this customer database appears to be empty

=======

I also tried disabling the payment processor attached to the 2nd iATS account, and the error still exists.

=======

Are you able to test this with 2 credit card payment processors that point to different iATS accounts? Is it possible that is the cause of this issue?

This version of the website is on a staging server where we are testing. Our live site has not been updated yet.

We currently have CiviCRM 5.0.0 installed. Should I go to the effort to update to 5.2.0?

**Comment by KarinG** [comment]
Yes worth it to update to 5.2.x for other reasons;

First and Second iATS account -> are you referring to subaccounts or do you have separate main accounts? I've to TE4188, DEMO88, TEST88 on my test site (so three different main accounts) - and have recurring test series with all of them; 

Every customer code (token) is unique to the iATS account it belongs to;  When you look in your contribution_recur table -> are the correct series still hooked up to the correct iATS Accounts?

**Comment by cmmadmin** [comment]
I upgraded to CiviCRM 5.2.1 and tried this again. This time I disabled the old payment processors instead of deleting them. The payment processor ids were not changed in the `civicrm_payment_processor` table and the Edit link works now. 

I suspect that the issue occurred because I had set the new payment processor to default and then deleted the old ones. Or perhaps, because I set the name of the new payment processor to the same same as the Vanco payment processor that I had deleted ("Credit Card"). This time I used "Credit-Card" for the new payment processor name instead which is less ideal because it appears on the Registration form, but perhaps we can live with it the dash.

**Comment by KarinG** [comment]
Hi - I'm confused as to why you disable/delete payment processors when upgrading CiviCRM? There is no need to do so.

**Comment by cmmadmin** [comment]
Sorry for the confusion. In addition to upgrading CiviCRM, we are also switching the payment processor we use for Events & Memberships from Vanco to iATS.

Before the upgrade we used: iATS for contributions and Vanco for events & memberships.
After the upgrade we will use: iATS (1st account) for contributions and iATS (2nd account) for events & memberships.

**Comment by KarinG** [comment]
Ah I see. I would generally never delete payment processors - but simply stop using them (on the various contribution/event/webform_civicrm pages); eventually disable them. Do you have any Vanco recurring that you need to migrate over to iATS?

**Comment by cmmadmin** [comment]
Thanks. That's helpful. No, we do not need to migrate any recurring. We migrated all recurring from Vanco to iATS last year.
