### ISSUE TITLE
Recurring Contributions Skipped

### ISSUE THREAD

**Issue by cmmadmin** [iATSPayments/com.iatspayments.civicrm#250]
CiviCRM 5.2.1, iATS 1.6.1

Ever since we upgraded from CiviCRM 4.6 to 5.2.1 we have noticed that several recurring contributions are being skipped. We seeing some process a few days after the date in civicrm_contribution_recur:next_sched_contribution_date. Others are not processing at all (we have waited 7 days for some and they have not processed yet).

What information can we provide to help troubleshoot this issue?

You may recall we have 2 iATS accounts (one for events/memberships (CC only), and one for contributions (CC & ACH)).

We would greatly appreciate help with this urgent issue. Thank you.

**Comment by KarinG** [comment]
Hi - 1. please note you'll want to upgrade to CiviCRM 5.3.1 - as soon as possible - see https://civicrm.org/blog/dev-team/announcing-civicrm-531-and-4638-security-release - the most critical vulnerability is not in this PSA yet [announcement delayed so people have a time to upgrade/patch] - but 5.3.1 fixes it.

Having multiple iATS accounts is fine. We run test sites with 4 different iATS accounts operating at the same time. We also have a project that has 8 iATS Payments processors set up;

I suspect that something fails and interrupts the iATS Payment Recurring Contributions job.

Look for an issue with the the contribution prior to the one that looks skipped; hit Execute Now on iATS Payment Recurring Contributions - scheduled job and hit View Job log -> check the recurring series IDs that have been processed -> they are processed in that order -> what does the last one say? It should finish with a having created activity. 

Successfully processed recurring contribution in series id 401: OK: 678594:
Created activity record for contact id 5

Check to see if the activity for that Contact was indeed created successfully and/or if you see any corresponding notes in the CiviCRM log as well as the php log;

PS - we ran our entire TEST matrix two weeks ago on 5.2.2 - and all recurring contributions ACHEFT/CC all processed fine;

**Comment by cmmadmin** [comment]
Thanks for your response. It appears the 'iATS Payment Recurring Contributions' scheduled job is not completing. 

It did not complete on these dates:

7/6-8
7/10
7/12-19

It did complete on these dates:

7/9 
7/11

Last contribution processed on 7/9 :
"Successfully processed pending recurring contribution in series id 8459: OK: 555555
Created activity record for contact id 172377)"

*We confirmed this contribution processed completely in Civi and in iATS

7/11 Last one:
"Successfully processed recurring contribution in series id 8396: OK: 011975:Y
Created activity record for contact id 172101)"

*We confirmed this contribution processed completely in Civi and in iATS

**Comment by cmmadmin** [comment]
This error appears many times in our CiviCRM log:

Jul 20 09:46:15  [info] $backTrace = #0 /var/www/webadmin/data/www/secure.mydomain.org/sites/all/modules/civicrm/CRM/Core/Error.php(381): CRM_Core_Error::backtrace("backTrace", TRUE)
#1 /var/www/webadmin/data/www/secure.mydomain.org/sites/all/modules/civicrm/CRM/Core/Controller.php(833): CRM_Core_Error::fatal("We can't load the requested web page. This page requires cookies to be enable...")
#2 /var/www/webadmin/data/www/secure.mydomain.org/sites/all/modules/civicrm/CRM/Core/Controller.php(853): CRM_Core_Controller->invalidKeyCommon()
#3 /var/www/webadmin/data/www/secure.mydomain.org/sites/all/modules/civicrm/CRM/Contribute/Controller/Contribution.php(74): CRM_Core_Controller->invalidKeyRedirect()
#4 /var/www/webadmin/data/www/secure.mydomain.org/sites/all/modules/civicrm/CRM/Core/Controller.php(312): CRM_Contribute_Controller_Contribution->invalidKey()
#5 /var/www/webadmin/data/www/secure.mydomain.org/sites/all/modules/civicrm/CRM/Core/Controller.php(204): CRM_Core_Controller->key("CRM_Contribute_Controller_Contribution", TRUE, FALSE)
#6 /var/www/webadmin/data/www/secure.mydomain.org/sites/all/modules/civicrm/CRM/Contribute/Controller/Contribution.php(55): CRM_Core_Controller->__construct("CiviContribute", "null")
#7 /var/www/webadmin/data/www/secure.mydomain.org/sites/all/modules/civicrm/CRM/Core/Invoke.php(304): CRM_Contribute_Controller_Contribution->__construct("CiviContribute", TRUE, "null", NULL, "false")
#8 /var/www/webadmin/data/www/secure.mydomain.org/sites/all/modules/civicrm/CRM/Core/Invoke.php(84): CRM_Core_Invoke::runItem((Array:15))
#9 /var/www/webadmin/data/www/secure.mydomain.org/sites/all/modules/civicrm/CRM/Core/Invoke.php(52): CRM_Core_Invoke::_invoke((Array:3))
#10 /var/www/webadmin/data/www/secure.mydomain.org/sites/all/modules/civicrm/drupal/civicrm.module(445): CRM_Core_Invoke::invoke((Array:3))
#11 [internal function](): civicrm_invoke("contribute", "transact")
#12 /var/www/webadmin/data/www/secure.mydomain.org/includes/menu.inc(527): call_user_func_array("civicrm_invoke", (Array:2))
#13 /var/www/webadmin/data/www/secure.mydomain.org/index.php(21): menu_execute_active_handler()
#14 {main}


Jul 20 09:56:15  [info] $Fatal Error Details = Array
(
    [message] => We can't load the requested web page. This page requires cookies to be enabled in your browser settings. Please check this setting and enable cookies (if they are not enabled). Then try again. If this error persists, contact the site administrator for assistance.<br /><br />Site Administrators: This error may indicate that users are accessing this page using a domain or URL other than the configured Base URL. EXAMPLE: Base URL is http://example.org, but some users are accessing the page via http://www.example.org or a domain alias like http://myotherexample.org.<br /><br />Error type: Could not find a valid session key.
    [code] => 
)

Perhaps helpful on this error:
https://civicrm.stackexchange.com/questions/12323/how-do-i-debug-could-not-find-valid-value-for-ct-error-message
https://civicrm.stackexchange.com/questions/14377/this-page-requires-cookies-to-be-enabled


We have this in .htaccess. But nothing for domain redirects that I am aware of.

# Redirect all to HTTPS 
RewriteCond %{SERVER_PORT} 80 
RewriteRule ^(.*)$ https://secure.mydomain.org/$1 [R=301,L]

We currently have this option set to No.

Administer > System Settings > Resource URLs > "Force Secure URLs (SSL)"

**Comment by cmmadmin** [comment]
We updated to CiviCRM 5.2.1 on 7/5/2018. The next morning our scheduled job “iATS Payments Recurring Contributions” started to execute. 

<img width="876" alt="2018-07-20" src="https://user-images.githubusercontent.com/6864440/43015686-ab6050cc-8c15-11e8-8b14-38cbfd52a401.png">

However, there was no subsequent entry on the job log indicating the completion of the scheduled job. This pattern repeated on 7/7 and 7/8. 

On 7/9 the job log shows the “iATS Payments Recurring Contributions” started to execute and finished execution.

<img width="936" alt="2018-07-20 1" src="https://user-images.githubusercontent.com/6864440/43015703-bbe2966c-8c15-11e8-9a5b-3c8d48c916f5.png">

**Comment by KarinG** [comment]
I don’t think that log message is related.

Key is to hunt in the ‘did not complete’ logs and find out which series it choked on; then we can dig in why by setting it’s next scheduled date to yesterday and running the schedule job manually; we would expect it not to finish - and to produce an error message in one of the logs (could be ConfigAndLog or php log).

**Comment by cmmadmin** [comment]
By ‘did not complete’ logs, do you mean ConfigAndLog or php log?

I have not found any other errors in ConfigAndLog at the time the job runs.

I see these errors in our httpd-logs:

```
[Fri Jul 20 07:09:58.672838 2018] [:error] [pid 13674] [client 93.158.205.31:49924] PHP Fatal error:  Maximum execution time of 30 seconds exceeded in /var/www/webadmin/data/www/secure.mydomain.org/sites/all/modules/civicrm/CRM/Contact/BAO/Query.php on line 689
[Fri Jul 20 07:29:04.891792 2018] [:error] [pid 19578] [client 93.158.205.31:51349] PHP Fatal error:  Maximum execution time of 30 seconds exceeded in /var/www/webadmin/data/www/secure.mydomain.org/sites/all/modules/civicrm/CRM/Utils/Array.php on line 55
[Fri Jul 20 07:50:04.030745 2018] [:error] [pid 13118] [client 93.158.205.31:52956] PHP Fatal error:  Maximum execution time of 30 seconds exceeded in /var/www/webadmin/data/www/secure.mydomain.org/sites/all/modules/civicrm/CRM/Core/Component/Info.php on line 362
```

**Comment by KarinG** [comment]
Ah that's a good clue as we're looking into why a job does not finish. Let me check:

we're at 90 on one of our servers:
`max_execution_time = 90`

and at 3600 on a server that manages close to 10k recurring contributions /month:
`max_execution_time = 3600`

Bump it to 90 for now.

**Comment by cmmadmin** [comment]
Oh geez. I should have caught that. I increased max_execution_time and re-ran the job manually and it looks good so far. I'll let you know if we encounter any further issues.

Thank you!

**Comment by KarinG** [comment]
Ok fingers crossed that was it!

**Comment by KarinG** [comment]
And yes please do keep us posted and let us know if we can help you out.
