### ISSUE TITLE
Donations status missing values

### ISSUE THREAD

**Issue by cmmadmin** [iATSPayments/com.iatspayments.civicrm#251]
CiviCRM 5.3.1, iATS 1.6.1

We are unable to change a donations status from "Completed" to "Failed" and from "Failed" to "Completed".
We have attempted to do so by: 
1.	Navigating to a donors profile
2.	Selecting Contributions from the top ribbon
3.	Selecting "Edit" on the donation in question
4.	Select the drop down by "Contribution Status"
When we do this for a donation that is marked **completed** we are only able to select the following options 

- Canceled
- In Progress
- Overdue
- Refunded
- Chargeback

When we attempt to do this for a donation that is marked **failed** we are only able to select the following options 

- Overdue
- Partially Paid
- Pending Refund

We would like to have "Failed" in the first list and "Completed" in the second list.

**Comment by cmmadmin** [comment]
Status menu for Completed contribution (Failed is missing):

<img width="198" alt="2018-07-20 3" src="https://user-images.githubusercontent.com/6864440/43021747-75c3a27e-8c2a-11e8-8bf8-634f1e78d2fb.png">

Status menu for Failed contribution (Completed is missing):

<img width="201" alt="2018-07-20 4" src="https://user-images.githubusercontent.com/6864440/43021778-8e861c2e-8c2a-11e8-8f14-673c36a058bb.png">

**Comment by KarinG** [comment]
Right - that's Core preventing you from doing that; it's not us! Only remedy is do edit via the API Explorer or directly in the database mysql.
