### ISSUE TITLE
Issue with next_sched_contribution_date becoming 'stuck'

### ISSUE THREAD

**Issue by elizolivares** [iATSPayments/com.iatspayments.civicrm#254]
We have a client who uses iATS as their payment processor, and a few days ago they reported that a recurring contribution had gone through (and the individual was charged) 6 times over a two day period. When we investigated the issue, we found that there were a huge number of recurring contributions that are "stuck", as in their next_sched_contribution_date is in the past (7/23). Even if the contribution runs and gets a 'complete' status, the next_sched_contribution_date does not increment to the next month (in this case, recurring contributions are all set to monthly).

I attempted to manually run the iatsrecurringcontributions job from the command line, and was met with the following:

`/usr/local/bin/drush --user=1 civicrm-api job.iatsrecurringcontributions auth=0 -y 2>&1
PHP Fatal error:  Allowed memory size of 2097152000 bytes exhausted (tried to allocate 20480 bytes) in /var/www/website.org/sites/all/modules/civicrm/CRM/Contact/BAO/GroupContactCache.php on line 401
Drush command terminated abnormally due to an unrecoverable error.                                                                              [error]
Error: Allowed memory size of 2097152000 bytes exhausted (tried to allocate 20480 bytes) in
/var/www/website.org/sites/all/modules/civicrm/CRM/Contact/BAO/GroupContactCache.php, line 401`

I have attempted to set the memory_limit to 2000M just to test if the job will complete, but receive the fatal error. Not sure if something else on the system is getting in the way or what, but all other jobs complete without issue.

Do you have any suggestions for stopping recurring contributions that are "stuck" and initiating recurring contributions that aren't running?

Other Details:
CiviCRM 5.3.1
Drupal 7.59
Debian GNU/Linux 9
Apache/2.4.25 (Debian)
mysql  Ver 15.1 Distrib 10.1.26-MariaDB, for debian-linux-gnu (x86_64) using readline 5.2
PHP 7.0.30-0+deb9u1 (cli) (built: Jun 14 2018 13:50:25) ( NTS )

**Comment by KarinG** [comment]
Do you have any extensions or any code with any pre or post_contribution_hooks? It sounds like a black hole.

**Comment by elizolivares** [comment]
Yes! We did not build this, and it looks like there were a few custom extensions, one of which related to contributions. I disabled it, and the job ran without issues. Closing this, and thank  you!

**Comment by KarinG** [comment]
Excellent - happy I was able to help you out. Thanks for reaching out!

**Comment by adixon** [comment]
FWIW:
1. 2Gb is a lot more than you should need for a CiviCRM install, most small-medium should only need about 128Mb or 256Mb.
2. handling this kind of issue is in the pipeline - specifically, what happened to your install is that the recurring contribution generation script triggered the transaction but stopped before it could update the next scheduled contribution date. We've got the pieces for running a kind of audit against the iATS data so that all transactions can get pulled into CiviCRM, or at least those that should be.
