### ISSUE TITLE
iats ach/eft event confirmation screen showing credit card, not ACH Info

### ISSUE THREAD

**Issue by sandrajvillagenetwork** [iATSPayments/com.iatspayments.civicrm#255]
The Event page to review and confirm the information displays 'credit card info' field (blank) and does not show the EFT/ACH confirmation information. How can this be fixed? 

![image](https://user-images.githubusercontent.com/36458331/44278582-04e59300-a214-11e8-9f58-4a36bf09ce25.png)

**Comment by adixon** [comment]
Yeah, that's a good question. It's not an iATS payment processor-specific thing, though.

That part of that screen is controlled by this template in your civicrm codebase:

templates/CRM/Event/Form/Registration/Confirm.tpl

So as a short term solution you could replace it with a customized one.

Feel free to open an issue on CiviCRM for some help with a better/longer-term kind of solution.
