### ISSUE TITLE
Pending Recurring Contribution Status After Changing Billing Details

### ISSUE THREAD

**Issue by jursulak** [iATSPayments/com.iatspayments.civicrm#257]
Hi Alan,

We have a recurring monthly donor who called to change their credit card info.

Our finance team updated the card info in CiviCRM by clicking on **more**, and then selecting **Change Billing Details**. The status of the recurring contribution now says pending:
![image](https://user-images.githubusercontent.com/1134488/45042685-228e6700-b020-11e8-81e2-fef6f419b39a.png)
Will CiviCRM try to process the donation through iATS again on the next payment date?

Thanks for your help!

**Comment by adixon** [comment]
No, only "in progress" recurring payments get processed, though there is some pre-processing logic of recurring contributions that will deal with status values that are completed and shouldn't be and vice versa (according to the installments/date values). 

Short answer - pending won't get processed.

If you're not able to edit the status back to In Progress, then you likely need to update your version of CiviCRM (i.e. you're showing a symptom of 1.6.1 and previous versions on Civi 5.x and above).
