### ISSUE TITLE
Duplicate transactions

### ISSUE THREAD

**Issue by jamesgaede** [iATSPayments/com.iatspayments.civicrm#263]
Civicrm 5.4.0, tried with Iats built in and as an extension (v.1.6.2). 

Basically, every transaction is duplicated multiple times.  I believe what is happening is that Civicrm tells the user that the application failed to update the transaction in the database, and they then try again.  But all of the attempts actually get processed.  

Any suggestion on how I might troubleshoot what is happening here?  I had a similar problem years ago that was related to a development instance of my site on the same server, but that is not the case this time.  

James

**Comment by adixon** [comment]
Are you seeing duplicate transactions in CiviCRM, in the iATS interface, or both?

I'd look in the civicrm error log first, I expect there's something useful in there.

**Comment by jamesgaede** [comment]
Both. 

I looked through the log, not sure exactly what I'm looking for.  I do see a number of common errors around the times that duplicate transactions were made.    Here are what seem to be the worst ones:

---------------

$Fatal Error Details = array(3) {
  ["message"]=>
  string(40) "source_contact_id is not a valid integer"

---------------

$Geocoding failed. Message from Google: (OVER_QUERY_LIMIT) = Keyless access to Google Maps Platform is deprecated. Please use an API key with all your API calls to avoid service interruption. For further details please refer to http://g.co/dev/maps-no-account

----------------

$Fatal Error Details = Array
(
    [message] => We can't load the requested web page. This page requires cookies to be enabled in your browser settings. Please check this setting and enable cookies (if they are not enabled). Then try again. If this error persists, contact the site administrator for assistance.<br /><br />Site Administrators: This error may indicate that users are accessing this page using a domain or URL other than the configured Base URL. EXAMPLE: Base URL is http://example.org, but some users are accessing the page via http://www.example.org or a domain alias like http://myotherexample.org.<br /><br />Error type: Could not find a valid session key.

-----------------

I tried using the test contribution page and it worked fine.  Let me know if you need more details around any of those error messages.

Thanks for your prompt attention,
James

**Comment by adixon** [comment]
You probably want to review that geocoding one, though I doubt it's the problem.

The source contact id error is unusual, the lack of a valid session key is not interesting.

One kind of thing that can happen is:
1. Donor makes a donation (interaction w/ CiviCRM).
2. CiviCRM sends the trasaction request to iATS, iATS processes it, but is interupted before CiviCRM can get a response.
3. CiviCRM displays the error message (likely a 9002 unknown error type thing).
4. Donor retries, generating a second donation.

It might also happen if you've got javascript errors on your donation page that the js that discourages multiple attempts at the same donation before the first one is finished, is not working.

Wanna post the url of the donation page that is generating the multiple donations?

**Comment by jamesgaede** [comment]
I did take steps to kill the geocoding thing after seeing that, thanks!

Here is the url:

https://casid-acedi.ca/civicrm/contribute/transact?reset=1&id=1

**Comment by adixon** [comment]
The donation page looks okay ... any other clues (has it always hapenned? recently started after xyz? commonalities from when it does occur?).

**Comment by jamesgaede** [comment]
Was not occurring prior to Oct 12.  I am not sure what might have changed at that point, though I was looking at different email solutions earlier in the fall.  Is it possible that something in the civicrm communications system would be contributing to 'failing' transactions?

**Comment by adixon** [comment]
Ah, that's an angle I hadn't though of but should have! Yes, if your outgoing mail is broken, then the visitor will get a message to that effect that may make them think the contribution didn't go through (when CiviCRM tries to send them the email receipt).

**Comment by jamesgaede** [comment]
Hmm.  When I did the test transaction I still received an email just fine...But, some users have mentioned they did not receive a receipt, so perhaps it is broken.  

In any case,  I've now reverted the outgoing mail on Civicrm to the old config.  Hopefully that'll fix it.  I suppose we could close this if you'd like, at least until I receive more transactions to test if it worked or not. 

Thanks for your help!

**Comment by jamesgaede** [comment]
I know this is closed now, not sure if me commenting will reopen, but the problem has not gone away.  I've fixed the geolocation thing, and have ensured the outgoing mail works.  There are no error messages displaying in the log now, but still having duplicate transactions.

**Comment by jamesgaede** [comment]
Hi Alan, just confirming we are carrying on this discussion by email.

**Comment by adixon** [comment]
Yes!

**Comment by martinh-pw** [comment]
Hi, has there been any findings here? We are seeing a very similar issue. We're doing event registrations, civi 5.9.1 (I think.. version has changed since) on Drupal.

In general the user accounts seem to be along the lines of: filled out online registration, received an error message at the end, then staff saw a successful registration/contribution (civi admin) but with 2 payments being charged (iats admin).

Apache error log shows this:
[Mon Feb 25 09:27:55.372923 2019] [fastcgi:error] [pid 157915] [client 142.156.1.223:16391] FastCGI: comm with server "/usr/lib/cgi-bin/php7-fcgi" aborted: idle timeout (125 sec), referer: [siteroot]/civicrm/event/register?_qf_Confirm_display=true&qfKey=89724912769ba89b5306edff7e85bdf8_8334
[Mon Feb 25 09:27:55.373439 2019] [fastcgi:error] [pid 157915] [client 142.156.1.223:16391] FastCGI: incomplete headers (0 bytes) received from server "/usr/lib/cgi-bin/php7-fcgi", referer: [siteroot]/civicrm/event/register?_qf_Confirm_display=true&qfKey=89724912769ba89b5306edff7e85bdf8_8334

Civi log shows:
Feb 25 09:28:18  [info] $Fatal Error Details = Array
(
    [callback] => Array
        (
            [0] => CRM_Core_Error
            [1] => handle
        )

    [code] => -5
    [message] => DB Error: already exists
    [mode] => 16
    [debug_info] => INSERT INTO civicrm_line_item (entity_table , entity_id , contribution_id , price_field_id , label , qty , unit_price , line_total , participant_count , price_field_value_id , financial_type_id , non_deductible_amount ) VALUES ('civicrm_participant' ,  10100 ,  2758 ,  44 , 'Early Rate (4 weeks prior)' ,  1 ,  661.050000000 ,  661.05 ,  1 ,  95 ,  7 ,  0.00 )  [nativecode=1062 ** Duplicate entry 'civicrm_participant-10100-2758-95-44' for key 'UI_line_item_value']
    [type] => DB_Error
    [user_info] => INSERT INTO civicrm_line_item (entity_table , entity_id , contribution_id , price_field_id , label , qty , unit_price , line_total , participant_count , price_field_value_id , financial_type_id , non_deductible_amount ) VALUES ('civicrm_participant' ,  10100 ,  2758 ,  44 , 'Early Rate (4 weeks prior)' ,  1 ,  661.050000000 ,  661.05 ,  1 ,  95 ,  7 ,  0.00 )  [nativecode=1062 ** Duplicate entry 'civicrm_participant-10100-2758-95-44' for key 'UI_line_item_value']
    [to_string] => [db_error: message="DB Error: already exists" code=-5 mode=callback callback=CRM_Core_Error::handle prefix="" info="INSERT INTO civicrm_line_item (entity_table , entity_id , contribution_id , price_field_id , label , qty , unit_price , line_total , participant_count , price_field_value_id , financial_type_id , non_deductible_amount ) VALUES ('civicrm_participant' ,  10100 ,  2758 ,  44 , 'Early Rate (4 weeks prior)' ,  1 ,  661.050000000 ,  661.05 ,  1 ,  95 ,  7 ,  0.00 )  [nativecode=1062 ** Duplicate entry 'civicrm_participant-10100-2758-95-44' for key 'UI_line_item_value']"]
)

**Comment by adixon** [comment]
This looks like a separate issue, and not specifically iATS-related. The key question would be why you're getting that 125 second timeout - it could be the visitor double clicking, or it could be somewhere in the code that is getting stuck (e.g a mysql lock waiting). If this is a new issue on an existing install that has only recently started happening, then that's a useful clue. Is suspect the second line of the apache error log and the civilog error (which is 20 seconds later) are symptoms of the real problem that lies underneath that timeout.

As above - do check your mail system, there are some contribution pathways that rely on email operations completing in a timely way (so if it doesn't, the contribution won't complete properly, causing stuff like you see in the civi log).
