### ISSUE TITLE
Refactor when Next Scheduled Contribution Date is advanced

### ISSUE THREAD

**Issue by KarinG** [iATSPayments/com.iatspayments.civicrm#268]
Change the workflow. We occasionally get reports like e.g. https://github.com/iATSPayments/com.iatspayments.civicrm/issues/254 - and even though there is always an explanation - it would be safer to refactor when the next scheduled contribution date is advanced, i.e. do it much earlier in the sequence.

**Comment by adixon** [comment]
Done, ready for testing in the next release.
