### ISSUE TITLE
Add output of recurring contribution job to CiviCRM log

### ISSUE THREAD

**Issue by KarinG** [iATSPayments/com.iatspayments.civicrm#269]
When the scheduled job is executed - only some limited information (by CiviCRM itself) appears in the CiviCRM log. This issue is for the Recurring Contributions job itself to write more information to the CiviCRM log - for potential ad-hoc debugging purposes.

**Comment by adixon** [comment]
The recurring contribution job itself was pretty verbose in logging things, but it didn't have anything to log in cases of server failures, which should properly be logged within the soap handling iATS_Service_Request object. That logging was being done, but only when the debug option was enabled -  and serious server errors really should always be logged. Done as per https://github.com/iATSPayments/com.iatspayments.civicrm/commit/7ecbef62a4d8bf673e63abc782b333a21713518c
