### ISSUE TITLE
Remnants of civicrm_iats_customer_codes remain in codebase

### ISSUE THREAD

**Issue by ddoligalski** [iATSPayments/com.iatspayments.civicrm#291]
Running 1.7.0-beta2.

It appears that the table civicrm_iats_customer_codes was removed from use in a recent version.

However, there is still code that references the table, notably in CRM/Iats/Form/Report/Recur.php.

**Comment by KarinG** [comment]
Thanks for the heads up Dave.

**Comment by ddoligalski** [comment]
Actually, its more like a rabbit hole.  I note the code is commented out.

But we are getting an error.  Let me try to pull in the details.

**Comment by KarinG** [comment]
Yes please do let us know what you're getting. I just had a look on our master copy - and I'm not getting any error:

![image](https://user-images.githubusercontent.com/5340555/69091124-e23dbd80-0a06-11ea-947c-c0640694a65f.png)

**Comment by ddoligalski** [comment]
Found it.  The error is actually occurring on merge.

The hook iats_civicrm_merge() in iats.php still lists civicrm_iats_customer_codes as a table that needs to be handled when doing a merge. So when a merge runs and the table doesn't exist anymore.  Boom.

Presumably, just eliminating that line should fix things?

(Sorry for the earlier red herring.... a grep didn't show the code as commented.... dumb grep.)

-Dave

**Comment by KarinG** [comment]
No problem - not at all. It gave me a chance to test the report to make sure that was working ok :-).

Yes the tokens now live in a core table and should (therefore) be available on merge one would hope. Please kee us posted.

**Comment by adixon** [comment]
Done, thanks ddoligalski
