### ISSUE TITLE
Recurring contributions no longer showing Custom Fields in subsequent contributions

### ISSUE THREAD

**Issue by IowaBoy1** [iATSPayments/com.iatspayments.civicrm#296]
Drupal 7.69 CiviCRM 5.20.0 iATSPayments 1.7

Around the end of Nov 2019 we updated to Civi 5.20 and at the same time we moved to a new server. Since then our recurring series are not including the custom fields New recurring contributions have the custom data, but subsequent contributions do not include the custom field information. Would this be related to an improper cron setup after the server move or would it be related to the CiviCRM update? I think there was also an iATS extension update around that same time

**Comment by adixon** [comment]
Most likely the extension update and/or the Civi version.

I'll try reproducing, thanks for the report.

**Comment by IowaBoy1** [comment]
Have you been able to duplicate this or find anything on it?

**Comment by IowaBoy1** [comment]
This seems to be working again. Not sure when it came back.
We are now on Drupal 7.78 Civi 5.28.2 iATSPayments 1.7.3

**Comment by adixon** [comment]
Thanks for reporting this. It must have been specific to one or more of the CiviCRM versions, glad it's gone now.
