### ISSUE TITLE
Upgrade to 1.7.1 breaks payment forms with multiple processors

### ISSUE THREAD

**Issue by vandahm** [iATSPayments/com.iatspayments.civicrm#298]
### Preface ###
While I am the one who got drafted into investigating our CIviCRM issue, I was not the person who initially set up our site. I know that we're experiencing errors that are triggered by your extension, but I don't know if your extension, another extension, or some sort of problem on our part is the root cause.

### The Symptom ###
On our CiviCRM site, our payment form allows members to pay with credit cards (through iATS) and PayPal (obvious not through iATS). When we upgraded to the 1.7.1 version of your plugin, The option to select PayPal stopped working because the AJAX that swaps the processing forms back and forth started receiving HTTP 500 errors from the webserver.

### Details ###
Looking at our server logs, we find this message:

    PHP Fatal error:  Uncaught Error: Call to protected method CRM_Core_Payment::supportsFutureRecurStartDate() from context '' in /var/www/membership/wp-content/uploads/civicrm/ext/com.iatspayments.civicrm/iats.php:359

So, let's check out line 359 of `iats.php`. At the time I'm writing this bug report, it's part of the condition of an `if` statement:

    if (!empty($settings['enable_public_future_recurring_start'])
        && $form->_paymentObject->supportsFutureRecurStartDate()
    )

What's happening is this:  `CRM_Core_Payment::supportsFutureRecurStartDate` is indeed a protected method on my installation of CiviCRM:

    protected function supportsFutureRecurStartDate() {
        return FALSE;
    }

In `CRM_Core_Payment_iATSService`, which inherits from `CRM_Core_Payment`, you override the method, changing its visibility. If a CiviCRM site uses only iATS for payment, they will not encounter a problem. But it is unsafe to assume that every subclass of `CRM_Core_Payment` has overridden the base class method in the same way that you have.

I notice that, at the beginning of `iats_civicrm_buildForm_CRM_Financial_Form_Payment` you attempt to check for multiple payment processors and handle that scenario. I am not sure why that did not protect us from the error.

### Short-Term Fix ###
Whatever the ultimate cause of the problem is, I've put together PR #299 with the one-line change that got us rolling again. You're welcome to it, if you'd like.

**Comment by adixon** [comment]
Thank you. This issue fixed with release 1.7.2 as per my note on your PR.

**Comment by vandahm** [comment]
@adixon I want to thank you for looking into this and fixing it as quickly as you did. I'll try the new version when I get home from work tonight.
