### ISSUE TITLE
Better error reporting

### ISSUE THREAD

**Issue by adixon** [iATSPayments/com.iatspayments.civicrm#30]
As per issue #26 - generate more/better error messages when recurring payments fail.

**Comment by tamarmeir** [comment]
Hello,

We had the following request from a client that seems to be relevant to this issue:

It would be helpful to have a report that will indicate which credit cards are about to expire or have expired for iATS subscriptions - this report could either be generated by the extension and available within Civi and/or could also be developed for the general merchant interface and made available as a push report  (i.e one that will send a notification to the merchant contact).

Thanks!
Tamar

**Comment by fulltrucker** [comment]
IMBA would also be extremely interested in this.

**Comment by adixon** [comment]
The latest version comes with a report template that does exactly this. The reports framework will let you email the reports.

This issue is more about the automated behaviour in other cases.

**Comment by tamarmeir** [comment]
Hi Alan,

Just to clarify - by the latest version do you mean 1.4.1? I checked the GUI before I asked and couldn't find anything, but if there is some configuration to be done to enable it, could you send documentation? I'm not a programmer, but I play one on TV.

Thanks for the speedy response!

**Comment by adixon** [comment]
If you go to Reports -> Create Reports from templates and look for a report name with the word iATS in it in the list, it should be evident. No programming required. You might want to RTFM if you're desperate (even programmers have been known to do that ...).

1.4.1 is the latest version, yes.
