### ISSUE TITLE
Testing iATS Payments

### ISSUE THREAD

**Issue by cmmadmin** [iATSPayments/com.iatspayments.civicrm#300]
I am working on upgrading to CiviCRM 5.22.0 and iATS 1.7.2 with PHP 7.3. I have completed the upgrade on our staging server, but when I attempt to use these test credit card numbers:

VISA: 41111111111111111 security code = 123

I get: Payment Processor Error message :9002: General decline code.

Using a valid credit card works. What's the best way to test? I need to check the fix formatting on my Confirm and Thank You pages.

Thank you,
Malachi

**Comment by adixon** [comment]
Great question. It'll depend on whether you're using the legacy iATS processor or the new one, and in both cases, those are issues that the iATS support desk or documentation would help you with.

For the legacy processor, I think this is the right documentation: https://home.iatspayments.com/developer-info/testing-cards

I'll note that if this is what you're using with the TEST88 account, then the response will depend on the amount.

**Comment by KarinG** [comment]
I always use 4222222222222220 when using TEST88 b/c you can test any amount between $1 and $2000 (yes the fake VISA has a limit).

**Comment by KarinG** [comment]
PS - using the fake VISA when you've got your real payment processor setup will result in a 9002. fake VISA only works on TEST88.

**Comment by cmmadmin** [comment]
Thank you. Sorry to bother you here. I must have gotten my live and test pages mixed up. Changing to use TEST88 works for me now both with the live and test contribution pages.

**Comment by KarinG** [comment]
No problem
