### ISSUE TITLE
Future Recurring Start Date is reset when Payment Option is changed

### ISSUE THREAD

**Issue by cmmadmin** [iATSPayments/com.iatspayments.civicrm#302]
Drupal 7.69
CiviCRM 5.23.4
iATS 1.7.2

We have the "Enable public selection of future recurring start dates." option checked in the iATS Payments Settings.

Here's what happens:
1. User selects "I want to contribute this amount every month"
2. User selects a future date in the "You may select a later start date if you wish." menu.
3. User changes the Payment Option (Credit or Virtual Check).
4. The future date set in step 1 is changed to "Now" as the payment block is loaded.

Is there a way to stop the future date from getting reset? Our users are not noticing that it is being reset.

You can see this happening here:
https://secure.mobilization.org/civicrm/contribute/transact?id=56

**Comment by adixon** [comment]
I suspect not - switching the payment option means you're changing the payment processor and each payment processor has different capabilities so a fair amount of the billing fields will get reloaded (via ajax). Even though both of the ones you are switching from/to have the future recurring start dates enabled, there's no guarantee from the code's perspective.

If it's a big issue, maybe changing the default payment option would make it more useable? Or creating separate payment pages for the two options?

As a side note: including this option for the public is not a core feature, it's something the extension does. The field is actually included below the other fields and then moved up via javascript (included in the extension), so you could fairly easily hack that javascript to move the field after where they're choosing their payment option if it improves the UX.
