### ISSUE TITLE
IATSOneTimeCharge Error: "Unsupported processor class Payment_AuthorizeNet" and "Unexpected error getting payment processor information"

### ISSUE THREAD

**Issue by cmmadmin** [iATSPayments/com.iatspayments.civicrm#303]
Drupal 7.69
CiviCRM 5.24.5
iATS 1.7.2

We are getting an error on the IATSOneTimeCharge page when we select "Charge This Card". This used to work but started getting the error when we upgraded to 5.23.4 and also since we upgraded to 5.24.5.

At first we were getting this error:

Sorry, due to an error, we are unable to fulfill your request at the moment. You may want to contact your administrator or service provider with more details about what action you were performing when this occurred.
**Unsupported processor class Payment_AuthorizeNet**

We had several old Payment Processors left over from when we used to use Authorize.Net and Vanco (years ago). They were all Disabled, but I went ahead and Deleted all of the ones that had Processor Type = Authorize.NET

After that now, I get this error when we select "Charge This Card":

**Unexpected error getting payment processor information for recurring schedule id 10177**

On Edit Payment Processor page, I noticed "Accepted Credit Card Type(s)" had none selected so I selected:
Visa, MasterCard, Amex, Discover

Still get the same error.

Portions of each error from the CiviCRM log are below. Please let me know if I can provide anything else that would be helpful.
Appreciate your help. Thank you, Malachi

**AFTER REMOVED DISABLED PAYMENT Processors**

```
Apr 30 11:45:12  [error] 
$Fatal Error Details = array(3) {
  ["message"]=>
  string(86) "Unexpected error getting payment processor information for recurring schedule id 10177"
  ["code"]=>
  NULL
  ["exception"]=>
  object(Exception)#2583 (7) {
    ["message":protected]=>
    string(86) "Unexpected error getting payment processor information for recurring schedule id 10177"
    ["string":"Exception":private]=>
    string(0) ""
    ["code":protected]=>
    int(0)
    ["file":protected]=>
    string(150) "/var/www/webadmin/data/www/mydomain.org/sites/default/files/civicrm_extensions/com.iatspayments.civicrm/CRM/Iats/Form/IATSOneTimeCharge.php"
    ["line":protected]=>
    int(150)
    ["trace":"Exception":private]=>
    array(13) {
      [0]=>
      array(6) {
        ["file"]=>
        string(150) "/var/www/webadmin/data/www/mydomain.org/sites/default/files/civicrm_extensions/com.iatspayments.civicrm/CRM/Iats/Form/IATSOneTimeCharge.php"
        ["line"]=>
        int(253)
        ["function"]=>
        string(25) "processCreditCardCustomer"
        ["class"]=>
        string(31) "CRM_Iats_Form_IATSOneTimeCharge"
        ["type"]=>
        string(2) "->"
        ["args"]=>
        array(1) {
          [0]=>
          array(10) {
            ["qfKey"]=>
            string(37) "af1247c404656c1ee3ceac7cabe4a0f8_8137"
            ["entryURL"]=>
            string(168) "https://mydomain.org/civicrm/contact/iatsprocesslink?reset=1&amp;cid=187954&amp;customerCode=XXXXXXXXXX&amp;paymentProcessorId=13&amp;crid=10177&amp;is_test=0"
            ["cid"]=>
            string(6) "187954"
            ["crid"]=>
            string(5) "10177"
            ["customerCode"]=>
            string(9) "XXXXXXXXXX"
            ["paymentProcessorId"]=>
            string(2) "13"
            ["is_test"]=>
            string(1) "0"
            ["amount"]=>
            string(4) "1.54"
            ["_qf_default"]=>
            string(24) "IATSOneTimeCharge:submit"
            ["_qf_IATSOneTimeCharge_submit"]=>
            string(16) "Charge this card"
          }
        }
      }
```

 **REMOVED REST FROM HERE** 

```
Apr 30 11:45:12  [debug] $backTrace = #0 /var/www/webadmin/data/www/mydomain.org/sites/all/modules/civicrm/CRM/Core/Error.php(419): CRM_Core_Error::backtrace("backTrace", TRUE)
#1 /var/www/webadmin/data/www/mydomain.org/sites/all/modules/civicrm/CRM/Core/Invoke.php(39): CRM_Core_Error::handleUnhandledException(Object(Exception))
#2 /var/www/webadmin/data/www/mydomain.org/sites/all/modules/civicrm/drupal/civicrm.module(456): CRM_Core_Invoke::invoke((Array:3))
#3 /var/www/webadmin/data/www/mydomain.org/includes/menu.inc(527): civicrm_invoke("contact", "iatsprocesslink")
#4 /var/www/webadmin/data/www/mydomain.org/index.php(21): menu_execute_active_handler()
#5 {main}   
```      

**BEFORE REMOVED DISABLED PAYMENT Processors**

```
Apr 30 11:13:57  [info] $Unsupported processor class: = Payment_AuthorizeNet

Apr 30 11:13:57  [error] 
$Fatal Error Details = array(3) {
  ["message"]=>
  string(48) "Unsupported processor class Payment_AuthorizeNet"
  ["code"]=>
  NULL
  ["exception"]=>
  object(Exception)#2583 (7) {
    ["message":protected]=>
    string(48) "Unsupported processor class Payment_AuthorizeNet"
    ["string":"Exception":private]=>
    string(0) ""
    ["code":protected]=>
    int(0)
    ["file":protected]=>
    string(139) "/var/www/webadmin/data/www/mydomain.org/sites/default/files/civicrm_extensions/com.iatspayments.civicrm/CRM/Iats/Transaction.php"
    ["line":protected]=>
    int(292)
    ["trace":"Exception":private]=>
    array(15) {
      [0]=>
      array(6) {
        ["file"]=>
        string(139) "/var/www/webadmin/data/www/mydomain.org/sites/default/files/civicrm_extensions/com.iatspayments.civicrm/CRM/Iats/Transaction.php"
        ["line"]=>
        int(85)
        ["function"]=>
        string(15) "process_payment"
        ["class"]=>
        string(20) "CRM_Iats_Transaction"
        ["type"]=>
        string(2) "::"
        ["args"]=>
        array(3) {
          [0]=>
          array(15) {
            ["version"]=>
            int(3)
            ["contact_id"]=>
            string(6) "187954"
            ["receive_date"]=>
            string(14) "20200430111357"
            ["total_amount"]=>
            string(2) "10"
            ["contribution_recur_id"]=>
            string(5) "10177"
            ["invoice_id"]=>
            string(32) "27351bce9787b04b45c679a4cd54f8bd"
            ["contribution_status_id"]=>
            int(2)
            ["payment_processor"]=>
            string(2) "13"
            ["is_test"]=>
            string(1) "0"
            ["payment_instrument_id"]=>
            string(1) "8"
            ["currency"]=>
            string(3) "USD"
            ["financial_type_id"]=>
            string(2) "21"
            ["source"]=>
            string(48) "iATS Payments  Recurring Contribution (id=10177)"
            ["original_contribution_id"]=>
            string(6) "353881"
            ["is_email_receipt"]=>
            string(1) "0"
          }
          [1]=>
          array(16) {
            ["id"]=>
            string(1) "3"
            ["domain_id"]=>
            string(1) "1"
            ["name"]=>
            string(10) "Vanco Live"
            ["payment_processor_type_id"]=>
            string(1) "6"
            ["is_active"]=>
            string(1) "0"
            ["is_default"]=>
            string(1) "0"
            ["is_test"]=>
            string(1) "0"
            ["user_name"]=>
            string(8) "e19804ws"
            ["password"]=>
            string(32) "0f2a08e10acbd856cfa2ffb20950f661"
            ["url_site"]=>
            string(29) "https://www.vancoservices.com"
            ["url_api"]=>
            string(45) "https://www.vancoservices.com/cgi-bin/ws2.vps"
            ["class_name"]=>
            string(20) "Payment_AuthorizeNet"
            ["billing_mode"]=>
            string(1) "1"
            ["is_recur"]=>
            string(1) "1"
            ["payment_type"]=>
            string(1) "1"
            ["payment_instrument_id"]=>
            string(1) "1"
          }
```
          
 **REMOVED REST FROM HERE** 

```
  }
}


Apr 30 11:13:57  [debug] $backTrace = #0 /var/www/webadmin/data/www/mydomain.org/sites/all/modules/civicrm/CRM/Core/Error.php(419): CRM_Core_Error::backtrace("backTrace", TRUE)
#1 /var/www/webadmin/data/www/mydomain.org/sites/all/modules/civicrm/CRM/Core/Invoke.php(39): CRM_Core_Error::handleUnhandledException(Object(Exception))
#2 /var/www/webadmin/data/www/mydomain.org/sites/all/modules/civicrm/drupal/civicrm.module(456): CRM_Core_Invoke::invoke((Array:3))
#3 /var/www/webadmin/data/www/mydomain.org/includes/menu.inc(527): civicrm_invoke("contact", "iatsprocesslink")
#4 /var/www/webadmin/data/www/mydomain.org/index.php(21): menu_execute_active_handler()
#5 {main}    
```

**Comment by adixon** [comment]
That means that the iATS extension thinks you're trying to update the credit card of a recurring schedule that's attached to the authorize.net payment processor.

Is that possible? Or is recurring schedule 10177 really attached to your iats processor?

**Comment by cmmadmin** [comment]
Thanks for the response. We created the recurring contribution today using a contribution page that has a iATS Payments Credit Card payment processor selected (we named it "Credit" as you can see in the screenshots). At that time the "Credit" payment processor did not have anything checked for "Accepted Credit Card Type(s)" so I'm wondering if it defaulted to one of the Disabled payment processors somehow?

We get the same error on other recurring contributions. We just created this one today for a clean test case.

I could try to create a new donation now that the disabled payment processors are deleted and the "Accepted Credit Card Type(s)" options are checked, but that won't fix it for our existing recurring contributions.

![contribution-page-setting](https://user-images.githubusercontent.com/6864440/80744394-35528b00-8ae4-11ea-91d6-c3f1a645533a.jpg)
![payment-processors](https://user-images.githubusercontent.com/6864440/80744408-38e61200-8ae4-11ea-8c30-c006e9b05cdc.jpg)

**Comment by cmmadmin** [comment]
In CiviCRM Extensions we still have the Vanco Payments (vanco.directpayment.processor) extension installed, but it is disabled. I would like to uninstall it but have been nervous to do so in case it breaks anything.

![image](https://user-images.githubusercontent.com/6864440/80744992-31733880-8ae5-11ea-8a87-0eef0cb55d1b.png)

**Comment by cmmadmin** [comment]
This is what our Payment Processors look like now that I've deleted the disabled ones...

![image](https://user-images.githubusercontent.com/6864440/80745112-68494e80-8ae5-11ea-84bc-bee1f087f88f.png)

**Comment by cmmadmin** [comment]
This is our Payment Method Options. We still have a Vanco option in here that is disabled.

![image](https://user-images.githubusercontent.com/6864440/80745253-a3e41880-8ae5-11ea-9c77-29d003531dd3.png)

**Comment by cmmadmin** [comment]
Under Financial Accounts, we do still have one for Vanco that is disabled. Also would like to delete it but nervous to do so.

![image](https://user-images.githubusercontent.com/6864440/80745516-0a693680-8ae6-11ea-83d5-397b816b829f.png)

**Comment by cmmadmin** [comment]
In the civicrm_contribution_recur table, I see this record:

id = 10177
payment_processor_id = 13
payment_instrument_id = 8
financial_type_id = 21

In the civicrm_payment_processor table, it looks like id=13 is indeed the iATS payment processor (see screenshot).

![image](https://user-images.githubusercontent.com/6864440/80745955-b4e15980-8ae6-11ea-8a66-b8e0d24f9369.png)

**Comment by cmmadmin** [comment]
Just to be sure I just tried a new recurring contribution and got the error on a brand new contact that was created.

IATSOneTimeCharge page when we select "Charge This Card":
Unexpected error getting payment processor information for recurring schedule id 10179

**Comment by adixon** [comment]
Okay, thanks for the very thorough response! I'll have to review the iats extension code to figure out why it's picking the wrong processor.

**Comment by cmmadmin** [comment]
Thanks for looking into this issue. Can we provide anything else to help you reproduce the issue? Is there anything you can suggest as workaround in the meantime?

**Comment by cmmadmin** [comment]
Hello Alan, 

Our finance team is asking about how we can get this working. Is there anything I can do to help troubleshoot this issue?

Thank you.
-Malachi

**Comment by adixon** [comment]
Do try 1.7.3-beta, or just https://github.com/iATSPayments/com.iatspayments.civicrm/pull/318

**Comment by cmmadmin** [comment]
@adixon #318 did not fix this issue.

However, I did some debugging and discovered the error occurs on line 146 in IATSOneTimeCharge.php:

> $paymentProcessor = civicrm_api3('PaymentProcessor', 'getsingle', array('id' => 3)); 

_Exception has occurred.
CiviCRM_API3_Exception: Expected one PaymentProcessor but found 0_

_Exception has occurred.
Exception: Unexpected error getting payment processor information for recurring schedule id 10859_

As you can see in my comment on Apr 30, we do not have a payment processor with ID = 3. Is there a reason payment processor 3 is hard coded here? It seems the correct ID is 13 in our case.

**Perhaps line 146 should be replaced with the following?**

> $paymentProcessor = civicrm_api3('PaymentProcessor', 'getsingle', array('id' => **$payment_token['payment_processor_id']**)); 

      
This works is our case.

I can also confirm that an attempt to get payment processor 3 using the API Explorer with 'PaymentProcessor', 'getsingle' fails. See attached screenshot.
      
To give you some context, here's some results from the debugger:

line 99 $contribution = array(

> version:3
> contact_id:"151146"
> receive_date:"20200901135639"
> total_amount:"5"
> contribution_recur_id:"10859"
![APIcall](https://user-images.githubusercontent.com/6864440/91899924-7f4ea780-ec63-11ea-86de-dc92bdf4ff72.jpg)

> invoice_id:"e9b522c8554439fd2a9d94b1ba902b09"
> contribution_status_id:2
> payment_processor:"13"
> is_test:"0"

then these these elements are added in the foreach on lines 110-112:

> payment_instrument_id:"8"
> currency:"USD"
> financial_type_id:"282"

then these these elements are added on lines 114-116:

> // We'll use the repeattransaction if the total amount is the same
> source:"iATS Payments  Recurring Contribution (id=10859)"
> $original_contribution_id = 370152
> 
> $contribution_recur_id = 10859

On line 127, civicrm_api3('ContributionRecur', 'getsingle',.. returns:

> id:"10859"
> payment_token_id:"8964"

On line 134, civicrm_api3('PaymentToken', 'getsingle'... returns:

> id:"8964"
> contact_id:"151146"
> payment_processor_id:"13"
> token:"xxxxxxxxxx"
> created_date:"2020-08-31 16:30:45"
> created_id:"151146"
> expiry_date:"2024-08-01 00:00:00"
> email:"xxxxxxxxxxxxxx"
> ip_address:"xxxxxxxxxxxx"

**Comment by cmmadmin** [comment]
Just wanted to check to see if anyone has had a chance to look at this. Is there a reason payment processor 3 is hard coded on line 146 in IATSOneTimeCharge.php:

`$paymentProcessor = civicrm_api3('PaymentProcessor', 'getsingle', array('id' => 3));`

Would it be ok to change it to the following?

`$paymentProcessor = civicrm_api3('PaymentProcessor', 'getsingle', array('id' => $payment_token['payment_processor_id']));`

I'm hesitant to put this on our production server until I know it won't cause any regressions.

**Comment by adixon** [comment]
Nicely done. Yes, that looks like a terrible, no-good bug. Worse since it's very hard to notice in tests! Thanks for your code, we'll put it in our next release, coming soon. Thanks for pursuing this.

**Comment by adixon** [comment]
In fact, the payment_processor_id value is already available without finding it in the payment_token. Committed, thanks.

https://github.com/iATSPayments/com.iatspayments.civicrm/commit/e2ffb688d08189ee34730afce52cb0997ed11d6b
