### ISSUE TITLE
Payment Processor Error message :9002: Unexpected Server Error

### ISSUE THREAD

**Issue by nc3man** [iATSPayments/com.iatspayments.civicrm#306]
We are running iATS Payments 1.7.2 on CiviCRM 5.21.3 (ESR) on Wordpress 5.4.1 and all of a sudden our payments aren't going through. Is that message from the plugin or is there possibly a server error at iATS? I cannot get through to iATS on the weekend. We are in the last 24 hours of a Bike Month Campaign and donations cannot be processed. They show up under Contributions > iATS Payments Admin, but as failed, not as completed. At least the donations are recorded. Any idea how to get this up and running ASAP?

**Comment by adixon** [comment]
Not an iATS issue, but a big Internet issue (root certificate expiration), solutions here:
https://twitter.com/ChristianHeimes/status/1266800555978039296
https://www.agwa.name/blog/post/fixing_the_addtrust_root_expiration

**Comment by nc3man** [comment]
Thanks so much, but I'm not even sure how to proceed to fix this for our site. We have a Let's Encrypt SSL cert on our site, but that's about as far as my knowledge goes. Is there a full explanation on what to do? We have a VPS on Dreamhost. Should I contact Dreamhost support.

**Comment by nc3man** [comment]
I followed the second link's suggestion to test domains at  https://whatsmychaincert.com/ and entered our domain, sdbikecoalition.org. It checked out OK with the "correct chain." I'm guessing that iATS servers may have an issue as the chain has expired certificates for iatspayments.com. I have opened an issue with iATS as many other CiviCRM sites must be experiencing the same issue.

**Comment by MikeyMJCO** [comment]
So the real fix will be for iATS themselves to remove the expired root cert from their chain (definitely an iATS issue - they've had over a month's notice at this point that this cert was expiring!) Not an iATS extension issue however!

For now you should be able to work around it:

**Debian/Ubuntu:**

1. Edit `/etc/ca-certificates.conf` and put a bang/exclamation mark (!) before mozilla/AddTrust_External_Root.crt
1. Run `update-ca-certificates`

**Fedora/RHEL/CENTOS:**

1. run `trust dump --filter "pkcs11:id=%AD%BD%98%7A%34%B4%26%F7%FA%C4%26%54%EF%03%BD%E0%24%CB%54%1A;type=cert"  > /etc/pki/ca-trust/source/blacklist/addtrust-external-root.p11-kit`
2. Run `update-ca-trust extract`

**Comment by nc3man** [comment]
@adixon - Alan, I also checked OpenSSL version in my VPS shell at Dreamhost and got version 1.0f. Should I request that Dreamhost update that? This is not a VPS with full root control, so there are some things not available? Is there risk in that? Everything has been working so smoothly for about 4 years until this.

**Comment by MikeyMJCO** [comment]
I would definitely ask them to update that. 

I'm assuming you mean `1.1.0f` if it's `1.0.0f` change hosts. The entire `1.1.0` line is broken and insecure - it shouldn't be used. The `1.0.0` version is even worse! `1.1.1g`  is the current stable.

**Comment by nc3man** [comment]
Yup, I did mean 1.0.0f. At least that's at the shell, which isn't always
the same version used for serving the web. But thanks for the advice.
Something I never even thought to consider.
Karl

**Comment by MikeyMJCO** [comment]
> Yup, I did mean 1.0.0f. At least that's at the shell, which isn't always the same version used for serving the web. But thanks for the advice. Something I never even thought to consider. Karl

It's the kind of thing you'd assume a host was checking/updating. This kind of thing is why we switched to managing our own environments on Azure/AWS/GCP (Azure/AWS have generous non-profit credit offers that make it basically free for most needs, Azure gives you 25,000 sendgrid emails a month on top!) honestly since switching our clients to Azure (and a couple on AWS!) we're much more secure across the board - but it's a little more work!

**Comment by KarinG** [comment]
Just a quick note to let you know that the root cause of the issue has been fixed.

**Comment by nc3man** [comment]
Yes, it's all working again. Thanks for helping out! I have about $2,700
worth of donations in limbo that I need to contact the donors 👍
Karl

**Comment by nc3man** [comment]
Thanks for that suggestion. I had been thinking of setting up our own virtual server to also have full control and I do realize the extra work. I will keep Azure/AWS as an option. I assume you're using AWS for your CiviMail bulk mailing, too?

**Comment by MikeyMJCO** [comment]
> Thanks for that suggestion. I had been thinking of setting up our own virtual server to also have full control and I do realize the extra work. I will keep Azure/AWS as an option. I assume you're using AWS for your CiviMail bulk mailing, too?

We're using SendGrid on Azure mostly, depends on the volume.

**Comment by nc3man** [comment]
I realized that after. We are using Sparkpost and our volume is more like
$50K recipients/mo. Sparkpost actually works pretty well, $20/mo, but it is
not a dedicated IP. We have been looking at AWS, but will check out
Sendgrid, too. Is the bounce processing working with Sendgrid?
Karl

**Comment by KarinG** [comment]
Hey guys! I think the payment processing bits have been resolved :-) Issue is closed :-)

**Comment by adixon** [comment]
Yes, we're definitely off-track now.

But ... to be clear:

1. The issue arose due to a Internet-wide problem that affected many services, when accessed by "older clients". In this case, it seems to have mostly affected websites that use iATS payments, if they were using older php versions, but it wasn't specifically about php, it was related to the root certificates. It was not related to the https connection to sites using civicrm, it was related to the back-end connection from the civicrm site to iATS. Not a browser issue, for example.

2. The iats-specific part of the problem was "solved" by iATS between 5 pm and 6 pm on Sunday. It wasn't an error per se that they fixed, but an update to their infrastructure that prevented the problem from affecting these backend connections.

3. The symptom, if you were affected, was the inability to execute any transactions. A transaction requires that your civicrm server communicate in the backend with the iATS payment processor server to actually transfer the money, and that connection was being aborted before anything could happen. Visitors would have gotten a 9002 error when trying to make a payment which would have been fairly baffling.

**Comment by cmmadmin** [comment]
Drupal 7.69
CiviCRM 5.24.5
iATS 1.7.2

We were receiving this same error over the weekend. We thought it was fixed and asked our users to try again. As of 10:36am this morning we are continuing to registration payments rejected with this error. Here's what I see in Civi log:

```
Jun 01 10:36:06  [info] $SoapFault Code = HTTP

Jun 01 10:36:06  [info] $SoapFault String = Error Fetching http headers

Jun 01 10:36:06  [error] Payment processor exception: 9002: Unexpected Server Error, please see your logs

Jun 01 10:41:11  [error] Payment processor exception: 9002: Error : No information is returned from App Server.
```

This is an urgent issue because we have a large event starting tomorrow that participants are trying to register for. Thank you for your help.

**Comment by cmmadmin** [comment]
Here's additional information from the Civi Log for another time it happened about an hour ago. I have scrubbed the sensitive info.

```
Jun 01 11:00:41  [info] $SoapFault Code = HTTP

Jun 01 11:00:41  [info] $SoapFault String = Service Unavailable

Jun 01 11:00:41  [error] Payment processor exception: 9002: Unexpected Server Error, please see your logs

Jun 01 11:04:06  [error] Payment processor exception: 9002: Error : No information is returned from App Server.

Jun 01 11:06:16  [info] $SoapFault Exception = SoapFault Object
(
    [message:protected] => Error Fetching http headers
    [string:Exception:private] => 
    [code:protected] => 0
    [file:protected] => /var/www/webadmin/data/www/mydomain.org/sites/default/files/civicrm_extensions/com.iatspayments.civicrm/CRM/Iats/iATSServiceRequest.php
    [line:protected] => 206
    [trace:Exception:private] => Array
        (
            [0] => Array
                (
                    [function] => __doRequest
                    [class] => SoapClient
                    [type] => ->
                    [args] => Array
                        (
                            [0] => <?xml version="1.0" encoding="UTF-8"?>
<env:Envelope xmlns:env="http://www.w3.org/2003/05/soap-envelope" xmlns:ns1="https://www.iatspayments.com/NetGate/"><env:Body><ProcessCreditCard xmlns="https://www.iatspayments.com/NetGate/"><agentCode>3EEL80</agentCode><password>xxxxxxxxxxxxx</password><customerIPAddress>xx.xxx.xx.xxx</customerIPAddress><invoiceNum>xxxxxxxxxxxxxxx</invoiceNum><creditCardNum>xxxxxxxxx</creditCardNum><creditCardExpiry>05/21</creditCardExpiry><firstName>xxxxxx</firstName><lastName>xxxxxxx</lastName><address>xxxxxxxxx</address><city>xxxxxxx</city><state>xx</state><zipCode>xxxxx</zipCode><cvv2>xxx</cvv2><total>25.00</total><comment>CiviCRM: 5.24.5 + iATS Extension: 1.7.2</comment></ProcessCreditCard></env:Body></env:Envelope>

                            [1] => https://www.iatspayments.com/NetGate/ProcessLinkv2.asmx
                            [2] => https://www.iatspayments.com/NetGate/ProcessCreditCard
                            [3] => 2
                            [4] => 0
                        )

                )

            [1] => Array
                (
                    [file] => /var/www/webadmin/data/www/mydomain.org/sites/default/files/civicrm_extensions/com.iatspayments.civicrm/CRM/Iats/iATSServiceRequest.php
                    [line] => 206
                    [function] => __call
                    [class] => SoapClient
                    [type] => ->
                    [args] => Array
                        (
                            [0] => ProcessCreditCard
                            [1] => Array
                                (
                                    [0] => SoapVar Object
                                        (
                                            [enc_type] => 147
                                            [enc_value] => <ProcessCreditCard xmlns="https://www.iatspayments.com/NetGate/"><agentCode>xxxxx</agentCode><password>xxxxx</password><customerIPAddress>xx.xxx.xx.xxx</customerIPAddress><invoiceNum>xxxxxxxxxxxx</invoiceNum><creditCardNum>xxxxxxxxxx</creditCardNum><creditCardExpiry>05/21</creditCardExpiry><firstName>xxxx</firstName><lastName>xxxxxx</lastName><address>xxxxxx</address><city>xxxxxx</city><state>xx</state><zipCode>xxxxx</zipCode><cvv2>xxx</cvv2><total>25.00</total><comment>CiviCRM: 5.24.5 + iATS Extension: 1.7.2</comment></ProcessCreditCard>
                                        )

                                )

                        )

                )

            [2] => Array
                (
                    [file] => /var/www/webadmin/data/www/mydomain.org/sites/default/files/civicrm_extensions/com.iatspayments.civicrm/CRM/Core/Payment/iATSService.php
                    [line] => 149
                    [function] => request
                    [class] => CRM_Iats_iATSServiceRequest
                    [type] => ->
                    [args] => Array
                        (
                            [0] => Array
                                (
                                    [agentCode] => xxxxx
                                    [password] => xxxxx
                                )

                            [1] => Array
                                (
                                    [firstName] => xxxxxxx
                                    [lastName] => xxxxxxxxxx
                                    [address] => xxxxxxxxxx 
                                    [city] => xxxxxxxxx
                                    [state] => xx
                                    [zipCode] => xxxxx
                                    [country] => US
                                    [invoiceNum] => xxxxxxxxxxxxxxx
                                    [creditCardNum] => xxxxxxxxxxxxxxx
                                    [cvv2] => xxx
                                    [creditCardExpiry] => 05/21
                                    [total] => 25.00
                                    [mop] => VISA
                                    [customerIPAddress] => xx.xxx.xx.xxx
                                )

                        )

                )

            [3] => Array
                (
                    [file] => /var/www/webadmin/data/www/mydomain.org/sites/all/modules/civicrm/CRM/Core/Payment.php
                    [line] => 1314
                    [function] => doDirectPayment
                    [class] => CRM_Core_Payment_iATSService
                    [type] => ->
                    [args] => Array
                        (
                            [0] => Array
                                (
                                    [qfKey] => xxxxxxxxxxxxxxxxxx
                                    [entryURL] => https://mydomain.org/civicrm/event/register?reset=1&amp;id=696
```

**Comment by adixon** [comment]
Yeah, this looks like the same issue that has come back. I noticed something similar this morning on a test site and thought it was just an anomaly, but your evidence suggests that the iats server certficate issue has somehow recurred.

iATS really better fix this, but for your own benefit, I'd look into fixing it a your end (i.e. update your infrastructure/stack to avoid the problem). Feel free to contact me directly for help, here:
https://blackflysolutions.ca/contact

**Comment by KarinG** [comment]
@cmmadmin - It's the same error -  but it's not the same issue. There are no SSL errors and https://whatsmychaincert.com/?iatspayments.com shows correct/green. 

I just made a live donation with one of our clients clients - and everything is ok.
![image](https://user-images.githubusercontent.com/5340555/83438866-51a55880-a3ff-11ea-9889-7fa452d39e52.png)

I also checked another client and they are payment processing and all their recurring series processed fine last night.

Could this have been a temp/connectivity issue between your server and iATS?

**Comment by cmmadmin** [comment]
Other payments have been processed in the meantime but a few occasionally fail with this error.

**Comment by nc3man** [comment]
Just to check, I also make a live contribution without the 9002 server
error.
Karl Rudnick (nc3man)

**Comment by courtney-nielsen** [comment]
iATS experienced a brief outage this morning preventing payment apps from operating correctly. This issue has been resolved, and all processes are operational now.

**Comment by adixon** [comment]
Thanks Courtney!

**Comment by monishdeb** [comment]
@adixon @courtney-nielsen we have encountered this issue again on couple of our production sites, where the daily cron job for processing iATS recurring donation skipped on Dec 2nd and 3rd. Here's the job log report: 
```
Full message: 
Finished execution of iATS Payments Recurring Contributions with result: Success (1 contribution record(s) were processed.
Failed to process recurring contribution id 10: Error : No information is returned from App Server.
```
 
And on civicrm config log: 
```
Dec 01 02:09:09  [info] $SoapFault Code = HTTP

Dec 01 02:09:09  [info] $SoapFault String = Error Fetching http headers

Dec 04 12:16:21  [info] Contribution record updated successfully
```

In another site I was getting : 
```
Dec 01 21:37:13  [info] $SoapFault Code = HTTP

Dec 01 21:37:13  [info] $SoapFault String = Service Unavailable

Dec 07 12:16:21  [info] Contribution record updated successfully
```

which indicate the same issue about slow response from SOAP service. We really like know what has caused this, so we can prevent such issue in future.

**Comment by adixon** [comment]
I'm not sure there's a reliable answer to "prevent such issue in the future".

But for the extension to recover from an issue like this, it would just need to know that an error like that is likely to be transitory, and the dial-in to the iATS server should be tried again.

In your example, I believe the result is going to be a failed transaction and the extension will try that recurring contribution again the following day, is that right? And the date on the contribution would also be pushed forward unless you've got the catchup=1 parameter set in your recurring job.

If that behaviour isn't what you're looking for - e.g. if you want to try that recurring payment sooner, you can just manually rerun the recurring contribution job on the same day. In theory, you should be able to run that recurring job every hour if you want - it doesn't do that by default due to the risk of some rogue configuration generating multiple charges by mistake.

**Comment by KarinG** [comment]
@monishdeb - I grepped one of our clients for this time period: their Dec01-10 ConfigAndLog and I get no SoapFault messages - and 6737 successfully processed recurring contributions (in total - summed over this time period). I don't have any outage reports from any of our other recurring clients either. 

But connectivity issues are always possible [between your outgoing SOAP request and the response from iATS] and a daily recurring contribution job can catchup to help with issues. 

It's a bit odd that the job appears to have shifted by 10h and 15h?

**Comment by ddoligalski** [comment]
@monishdeb @adixon @courtney-nielsen   I have a client who is experiencing the same SoapFault exception, Error Fetching http headers issue.  This occurred on recurring txns on Nov 18th, and again yesterday on Dec 16th.  Both times at 2:30am central.

Noting that the txns missed (now in Pending status) were not processed in the next daily cycle.

Not sure where to go with this.

**Comment by adixon** [comment]
You probably want to create a new issue for this.

The short answer is: the extension started the transaction and failed upon trying to communicate with the iATS extension. Because it doesn't know whether the transaction actually went through at the time, it's left it for you to sort out. If you can confirm those transactions didn't happen, you'll want to update the next scheduled contribution and then it'll try it again.

My best guess is that your server has some kind of backup process or other maintenance going on at 2:30 am, I'd recommend you change your recurring payment job to a safer time for your server (see the wiki for instructions).
