### ISSUE TITLE
iATS settings page

### ISSUE THREAD

**Issue by rocxa** [iATSPayments/com.iatspayments.civicrm#320]
Which of these settings are used by which iATS payment gateway:

![image](https://user-images.githubusercontent.com/2385929/89783095-44e36600-db0e-11ea-8fff-6dd7a7db4526.png)

e.g. 'Enable self service updates....' is not enabled, but the links to do it are sent to the donor for a 'iATS - 1stPay Credit Card' gateway.  But the  links only work if an admin clicks them.

**Comment by adixon** [comment]
You are correct, the "enable self-serve options" is not working on 1st Pay.

I believe that all the other features are working on 1st Pay as suggested on that page.
