### ISSUE TITLE
JS error in console for contribution forms with 1stPay payment processors

### ISSUE THREAD

**Issue by Edzelopez** [iATSPayments/com.iatspayments.civicrm#326]
Hi,

We've noticed a JS error that appears in console when we use a payment processor set up with 1stPay. (1stPay ACH in this case, but we were able to replicate it with 1stPay credit cards as well).

Here is the error:

<img width="1675" alt="Screenshot 2020-08-19 at 3 39 28 PM" src="https://user-images.githubusercontent.com/1990869/91325041-5bf9a780-e7e0-11ea-85fb-e3bafb78ff87.png">

We traced it to an error in firstpay.cryptogram.js, where it is unable to find the iframe element for the payment fields. We can confirm that the iframe does indeed exist, with the right ID, so this may be the case that the JS is loaded before the iframe is constructed (just a guess). We also think that this does not impact functionality, but worth a shot to look at.

**Comment by adixon** [comment]
Yeah, I'd noticed this also and agree it's a distraction that would be nice to fix. Thanks for your ideas.

**Comment by yashodha** [comment]
Do we have a patch for this?

**Comment by adixon** [comment]
Turned out to be relatively easy - the js was being included at the right place, I'd just included it earlier as well, unnecessarily it turns out.

https://github.com/iATSPayments/com.iatspayments.civicrm/commit/e6c3e2392cd6b7e145d92453f0ba08d2dcca5356
