### ISSUE TITLE
ACH Category Text invalid

### ISSUE THREAD

**Issue by Edzelopez** [iATSPayments/com.iatspayments.civicrm#327]
Hi,

I keep getting the following error when using 1stPay ACH debit

"ACH Category Text invalid"

I can confirm that I set up an ACH company name, ACH category etc and that the extension is successfully matching what's provided with what is configured in the getCategories() function. 

I'm using a Sandbox account with ACH enabled, and the following test details
Bank Number: 123
Transit Number: 00000
Account Number: 123456

The page that I've set up is here: https://ch-dms.jmaconsulting.biz/civicrm/contribute/transact?reset=1&id=4 (Using test creds in live mode since test mode isn't working at all).

Any thoughts?

**Comment by adixon** [comment]
Any reason you didn't want the extension to generate and use the ACH category text? The ACH category text probably has some fairly narrow restrictions, it's purely an internal identifier and you probably shouldn't be manually setting it except for really specific reasons.

**Comment by Edzelopez** [comment]
Sorry, should have clarified. I let the extension create the category text, specified as CiviCRM ACH. That didn't seem to work either

**Comment by KarinG** [comment]
I just spoke with Matt from iATSPayments -> Canadian clients using ACH/EFT should still be going through iATS Legacy services (i.e. payment processor = iATS Payments ACH/EFT). Matt will email Joe w/ Agent code and Password for a legacy ACH/EFT you can use for CH. At this point only US clients can use iATS Payments 1stPay ACH.

**Comment by KarinG** [comment]
PS - Matt also noted that he would update CH/JMA when iATSPayments will be able to route ACH/EFT through the 1stPay/Paysafe gateway (that's the piece that's missing at this point).

**Comment by Edzelopez** [comment]
Thanks for the useful information @KarinG!
