### ISSUE TITLE
1st Pay Credit Card - recurring gift not working

### ISSUE THREAD

**Issue by rocxa** [iATSPayments/com.iatspayments.civicrm#328]
I have a test payment gateway set up to allow recurring payments monthly and yearly.

![image](https://user-images.githubusercontent.com/2385929/91962558-95607480-ed04-11ea-9435-993c28e81520.png)

I can successful place a test credit card one off or recurring payment, but the recurring settings are not saved/passed to iATS.

![image](https://user-images.githubusercontent.com/2385929/91959817-0f8efa00-ed01-11ea-9ee4-814fb3ab4d5c.png)

What is causing this? Is there something I have missed in the setup? or how this should work..

**Comment by KarinG** [comment]
This is correct!

CiviCRM initiates the recurring transaction acoording to the instructions (next scheduled date, frequency, amount) set in the recurring contribution in CiviCRM.

If you were to also switch ON recurring in the Transaction Centre- that would also be triggering Transactions from there resulting in a card getting charged twice.

**Comment by rocxa** [comment]
Do you know which of these methods are used to generate the token?

2.1.1 Token Generation
Token generation describes the process or method of creating a token. Common forms of token generation include but are not limited to:

- A mathematically reversible cryptographic function, based on a known strong cryptographic algorithm and strong cryptographic key (with a secure mode of operation and padding mechanism)

- A one-way non-reversible cryptographic function (e.g., a hash function with strong, secret salt)

- Assignment through an index function, sequence number or a randomly generated number (not mathematically derived from the PAN)

It is important due to this:

> Note: If a token is generated as a result of using a hash function, then it is relatively trivial effort
for a malicious individual to reconstruct original PAN data if they have access to both the
truncated and hashed version of the PAN. Where hashed and truncated versions of the same
PAN are present in the environment, additional controls should be in place to ensure that the
hashed and truncated versions cannot be correlated to reconstruct the original PAN.
Whichever generation method is used, the recovery of the original PAN must not be
computationally feasible knowing only the token or a number of tokens. This is true for both
single-use and multi-use tokens. Additionally, access to multiple token-to-PAN pairs should not
allow the ability to predict or determine other PAN values from knowledge of only tokens. Tokens
should have no value if compromised or stolen, and should be unusable to an attacker if a system
storing only tokens is compromised.
Note that where token generation is based on a reversible encryption method (where the token is
mathematically derived from the original PAN through the use of an encryption algorithm and
cryptographic key), the resultant token is an encrypted PAN, and may be subject to PCI DSS
considerations in addition to those included in this document. The PCI SSC is further evaluating
how these considerations may impact PCI DSS scope for reversible, encryption-based tokens.
Tokenization of sensitive authentication data (including magnetic stripe data or equivalent on a
chip, CAV2 / CVC2 / CVV2 / CID data, and PINs/PIN blocks) is not permitted per PCI DSS
Requirement 3.2.

**Comment by adixon** [comment]
That's a reasonable question and I'm not sure of the answer. The extension itself is not responsible for generating the token, it comes back as a result of an api call. In fact, the call to the tokenization is already a kind of tokenization of the card data which comes from the 1st pay server, though that's not really relevant (but makes the question and answer harder to explain).

If you really need to know, then the documentation says "For more information please contact your Solutions Delivery Consultant."

**Comment by adixon** [comment]
re: your original question, here's the documentation on how the recurring contributions are generated:
https://github.com/iATSPayments/com.iatspayments.civicrm/wiki/Recurring-Contribution-Job

and here's more detailed blog post about what makes the iATS extension somewhat different in terms of how recurring contributions work:
https://civicrm.org/blog/alan-dixon/recurring-payments-advanced-functions
