### ISSUE TITLE
SWIPE payment processor prevents other pp from being available

### ISSUE THREAD

**Issue by sgladstone** [iATSPayments/com.iatspayments.civicrm#33]
After enabling a new payment processor (of type iATS Payments SWIPE) I am prevented from using any other payment processor in the back office, even other iATS payment processors. (SWIPE is NOT the default processor)

**Comment by KarinG** [comment]
Closing this: iATS Swipe is working with 4.4.x and 4.5.x in backend as well as on public contributions pages (Donations, Donations-recurring, Membership, Events) [see the README.md file: a patch is needed to make iATS Swipe work on public pages].
