### ISSUE TITLE
Unexpected configuration options on new account

### ISSUE THREAD

**Issue by robbrandt** [iATSPayments/com.iatspayments.civicrm#330]
Hi.  We just signed up for iATS and I was directed here by our iATS rep to resolve this issue.

We were given a sheet with various account IDs and passwords but what's on the sheet doesn't align with the form we see in CiviCRM.

We are using CiviCRM v5.13.5 and iATS extension v1.7.2.  We are sort of stuck on this old version of CiviCRM because our server is still running php 5.6 and needs to be reconfigured to run multiple versions of php before we can upgrade to a newer version.

Peggah has told us that we should be choosing the 1stPay option, but that is not presented to us.  Note that it also asks for Agent Code for Processor Details, something that isn't listed on our account sheet from iATS.

![iATS](https://user-images.githubusercontent.com/354681/93368528-f4dd7a80-f802-11ea-8219-e65fdcd43a0e.png)

Thanks.

**Comment by KarinG** [comment]
Hi @robbrandt -> version iATS extension v1.7.2 -> when installed properly should show:

![image](https://user-images.githubusercontent.com/5340555/93369085-1131e500-f80c-11ea-8db1-46121033889f.png)

Did you see any notices / messages in the log file when you installed the Extension - something related to payment processors not being created?

**Comment by robbrandt** [comment]
No, I don't recall seeing anything like that.  Should I try uninstalling and reinstalling?

**Comment by KarinG** [comment]
Yes - try that. Are you positive you have iATS Extension version 1.7.2? The screen you show is what the 1.6.x version looked like.

**Comment by robbrandt** [comment]
No errors, and it's definitely 1.7.2.  But I can happily report that once reinstalled I get a completely different set of iATS options, including the expected "1st Pay Credit Card" option.  I will loop back to Peggah and finish the set up and let you know if there's any other issues.

**Comment by KarinG** [comment]
Happy dance! :-) Excellent. To ensure everything is set up properly -> push a $5 transaction through and follow it all the way into your bank account!
