### ISSUE TITLE
Processing card on file does not work

### ISSUE THREAD

**Issue by larssandergreen** [iATSPayments/com.iatspayments.civicrm#336]
We have noticed for a while now that processing a card on file doesn't work for us. We just get an immediate 503.

I'm pasting the error logged below.

**Comment by larssg-wildsight** [comment]
[error] 
$Fatal Error Details = array(3) {
  ["message"]=>
  string(627) "We can't load the requested web page. This page requires cookies to be enabled in your browser settings. Please check this setting and enable cookies (if they are not enabled). Then try again. If this error persists, contact the site administrator for assistance.

Site Administrators: This error may indicate that users are accessing this page using a domain or URL other than the configured Base URL. EXAMPLE: Base URL is http://example.org, but some users are accessing the page via http://www.example.org or a domain alias like http://myotherexample.org.

Error type: Could not find a valid session key."
  ["code"]=>
  NULL
  ["exception"]=>
  object(CRM_Core_Exception)#2328 (10) {
    ["errorData":"CRM_Core_Exception":private]=>
    array(1) {
      ["error_code"]=>
      int(0)
    }
    ["cause":protected]=>
    NULL
    ["_trace":"PEAR_Exception":private]=>
    NULL
    ["message":protected]=>
    string(627) "We can't load the requested web page. This page requires cookies to be enabled in your browser settings. Please check this setting and enable cookies (if they are not enabled). Then try again. If this error persists, contact the site administrator for assistance.

Site Administrators: This error may indicate that users are accessing this page using a domain or URL other than the configured Base URL. EXAMPLE: Base URL is http://example.org, but some users are accessing the page via http://www.example.org or a domain alias like http://myotherexample.org.

Error type: Could not find a valid session key."
    ["string":"Exception":private]=>
    string(0) ""
    ["code":protected]=>
    int(0)
    ["file":protected]=>
    string(63) "/var/www/html/sites/all/modules/civicrm/CRM/Core/Controller.php"
    ["line":protected]=>
    int(829)
    ["trace":"Exception":private]=>
    array(11) {
      [0]=>
      array(6) {
        ["file"]=>
        string(63) "/var/www/html/sites/all/modules/civicrm/CRM/Core/Controller.php"
        ["line"]=>
        int(824)
        ["function"]=>
        string(16) "invalidKeyCommon"
        ["class"]=>
        string(19) "CRM_Core_Controller"
        ["type"]=>
        string(2) "->"
        ["args"]=>
        array(0) {
        }
      }
      [1]=>
      array(6) {
        ["file"]=>
        string(63) "/var/www/html/sites/all/modules/civicrm/CRM/Core/Controller.php"
        ["line"]=>
        int(308)
        ["function"]=>
        string(10) "invalidKey"
        ["class"]=>
        string(19) "CRM_Core_Controller"
        ["type"]=>
        string(2) "->"
        ["args"]=>
        array(0) {
        }
      }
      [2]=>
      array(6) {
        ["file"]=>
        string(63) "/var/www/html/sites/all/modules/civicrm/CRM/Core/Controller.php"
        ["line"]=>
        int(190)
        ["function"]=>
        string(3) "key"
        ["class"]=>
        string(19) "CRM_Core_Controller"
        ["type"]=>
        string(2) "->"
        ["args"]=>
        array(3) {
          [0]=>
          string(31) "CRM_Iats_Form_IATSOneTimeCharge"
          [1]=>
          bool(true)
          [2]=>
          bool(false)
        }
      }
      [3]=>
      array(6) {
        ["file"]=>
        string(70) "/var/www/html/sites/all/modules/civicrm/CRM/Core/Controller/Simple.php"
        ["line"]=>
        int(50)
        ["function"]=>
        string(11) "__construct"
        ["class"]=>
        string(19) "CRM_Core_Controller"
        ["type"]=>
        string(2) "->"
        ["args"]=>
        array(6) {
          [0]=>
          string(17) "IATSOneTimeCharge"
          [1]=>
          bool(true)
          [2]=>
          NULL
          [3]=>
          string(31) "CRM_Iats_Form_IATSOneTimeCharge"
          [4]=>
          bool(true)
          [5]=>
          bool(false)
        }
      }
      [4]=>
      array(6) {
        ["file"]=>
        string(61) "/var/www/html/sites/all/modules/civicrm/CRM/Utils/Wrapper.php"
        ["line"]=>
        int(62)
        ["function"]=>
        string(11) "__construct"
        ["class"]=>
        string(26) "CRM_Core_Controller_Simple"
        ["type"]=>
        string(2) "->"
        ["args"]=>
        array(7) {
          [0]=>
          string(31) "CRM_Iats_Form_IATSOneTimeCharge"
          [1]=>
          string(17) "IATSOneTimeCharge"
          [2]=>
          NULL
          [3]=>
          bool(false)
          [4]=>
          bool(false)
          [5]=>
          bool(false)
          [6]=>
          bool(false)
        }
      }
      [5]=>
      array(6) {
        ["file"]=>
        string(59) "/var/www/html/sites/all/modules/civicrm/CRM/Core/Invoke.php"
        ["line"]=>
        int(285)
        ["function"]=>
        string(3) "run"
        ["class"]=>
        string(17) "CRM_Utils_Wrapper"
        ["type"]=>
        string(2) "->"
        ["args"]=>
        array(3) {
          [0]=>
          string(31) "CRM_Iats_Form_IATSOneTimeCharge"
          [1]=>
          string(17) "IATSOneTimeCharge"
          [2]=>
          array(0) {
          }
        }
      }
      [6]=>
      array(6) {
        ["file"]=>
        string(59) "/var/www/html/sites/all/modules/civicrm/CRM/Core/Invoke.php"
        ["line"]=>
        int(68)
        ["function"]=>
        string(7) "runItem"
        ["class"]=>
        string(15) "CRM_Core_Invoke"
        ["type"]=>
        string(2) "::"
        ["args"]=>
        array(1) {
          [0]=>
          array(13) {
            ["id"]=>
            string(3) "545"
            ["domain_id"]=>
            string(1) "1"
            ["path"]=>
            string(31) "civicrm/contact/iatsprocesslink"
            ["title"]=>
            string(17) "IATSOneTimeCharge"
            ["access_callback"]=>
            array(2) {
              [0]=>
              string(19) "CRM_Core_Permission"
              [1]=>
              string(9) "checkMenu"
            }
            ["access_arguments"]=>
            array(2) {
              [0]=>
              array(1) {
                [0]=>
                string(14) "access CiviCRM"
              }
              [1]=>
              string(3) "and"
            }
            ["page_callback"]=>
            string(31) "CRM_Iats_Form_IATSOneTimeCharge"
            ["breadcrumb"]=>
            array(1) {
              [0]=>
              array(2) {
                ["title"]=>
                string(7) "CiviCRM"
                ["url"]=>
                string(16) "/civicrm?reset=1"
              }
            }
            ["is_ssl"]=>
            string(1) "0"
            ["weight"]=>
            string(1) "1"
            ["type"]=>
            string(1) "1"
            ["page_type"]=>
            string(1) "0"
            ["page_arguments"]=>
            bool(false)
          }
        }
      }
      [7]=>
      array(6) {
        ["file"]=>
        string(59) "/var/www/html/sites/all/modules/civicrm/CRM/Core/Invoke.php"
        ["line"]=>
        int(36)
        ["function"]=>
        string(7) "_invoke"
        ["class"]=>
        string(15) "CRM_Core_Invoke"
        ["type"]=>
        string(2) "::"
        ["args"]=>
        array(1) {
          [0]=>
          array(3) {
            [0]=>
            string(7) "civicrm"
            [1]=>
            string(7) "contact"
            [2]=>
            string(15) "iatsprocesslink"
          }
        }
      }
      [8]=>
      array(6) {
        ["file"]=>
        string(61) "/var/www/html/sites/all/modules/civicrm/drupal/civicrm.module"
        ["line"]=>
        int(454)
        ["function"]=>
        string(6) "invoke"
        ["class"]=>
        string(15) "CRM_Core_Invoke"
        ["type"]=>
        string(2) "::"
        ["args"]=>
        array(1) {
          [0]=>
          array(3) {
            [0]=>
            string(7) "civicrm"
            [1]=>
            string(7) "contact"
            [2]=>
            string(15) "iatsprocesslink"
          }
        }
      }
      [9]=>
      array(4) {
        ["file"]=>
        string(31) "/var/www/html/includes/menu.inc"
        ["line"]=>
        int(527)
        ["function"]=>
        string(14) "civicrm_invoke"
        ["args"]=>
        array(2) {
          [0]=>
          string(7) "contact"
          [1]=>
          string(15) "iatsprocesslink"
        }
      }
      [10]=>
      array(4) {
        ["file"]=>
        string(23) "/var/www/html/index.php"
        ["line"]=>
        int(21)
        ["function"]=>
        string(27) "menu_execute_active_handler"
        ["args"]=>
        array(0) {
        }
      }
    }
    ["previous":"Exception":private]=>
    NULL
  }
}

**Comment by larssg-wildsight** [comment]
[debug] $backTrace = #0 /var/www/html/sites/all/modules/civicrm/CRM/Core/Error.php(433): CRM_Core_Error::backtrace("backTrace", TRUE)
#1 /var/www/html/sites/all/modules/civicrm/CRM/Core/Invoke.php(39): CRM_Core_Error::handleUnhandledException(Object(CRM_Core_Exception))
#2 /var/www/html/sites/all/modules/civicrm/drupal/civicrm.module(454): CRM_Core_Invoke::invoke((Array:3))
#3 /var/www/html/includes/menu.inc(527): civicrm_invoke("contact", "iatsprocesslink")
#4 /var/www/html/index.php(21): menu_execute_active_handler()
#5 {main}

**Comment by adixon** [comment]
Thanks for the report. I've tested this function with the about-to-be-released 1.7.3 and can't reproduce, so perhaps one of the other fixes has also fixed you here.

**Comment by larssandergreen** [comment]
Tested on 1.7.3. and seems to be working now at least for a test case, so let's hope that's done it. Thanks!

**Comment by adixon** [comment]
Hooray, and thanks again for the report and test.
