### ISSUE TITLE
Intermittent SOAP failure on recurring contribution

### ISSUE THREAD

**Issue by JoeMurray** [iATSPayments/com.iatspayments.civicrm#339]
We are wondering what to do about intermittent problems with a failed recurring payment. Here's a sample log entry:
![2020-10-30_14-14-52](https://user-images.githubusercontent.com/300943/97742427-a76b5300-1aba-11eb-871f-2690662c6543.png)

The previous payment was successful, nothing shows up in iATS, and the next payment proceeds after the regular interval, and the series stops after the right number of recurrences, which didn't count this failed transaction. 

This is D7, CiviCRM 5.29.1, iATS 1.7.2.

Should we be asking iATS about this, or reporting it to them? Is there further logging you can recommend? The client is concerned, but we haven't yet determined the frequency of the problem.

**Comment by adixon** [comment]
Yeah, sounds like one of those hard-to-trace network issues. You could ask iATS if they had any reported server issues at that time, but you probably won't get much back. It sounds like the extension did a good job of handling it anyway.

You could grep your civi log to figure out if there's a pattern.

**Comment by ddoligalski** [comment]
@JoeMurray Were you able to uncover anything on this issue??

**Comment by adixon** [comment]
@ddoligalski  were you also having similar issues? It would be useful if you can post some exact timing of similar issues, to see if it might be iATS server related. Most of the cases of this message will be specific to your host's server.
