### ISSUE TITLE
Regression -> the & is back!

### ISSUE THREAD

**Issue by KarinG** [iATSPayments/com.iatspayments.civicrm#340]
Looks like the & is again coming through -> iATS rejects & with REJ:23

`d86a32a04df4e4f3e85c416799a3352e | 10/30/2020 10:59:27 AM | 2CKY80 |   | VISA | Sheila andamp; Jeff - REJ:23
`

**Comment by adixon** [comment]
Fixed w/ https://github.com/iATSPayments/com.iatspayments.civicrm/commit/6d41cb867db3d361b854d99cb3df9bea83c72d14
