### ISSUE TITLE
Cannot cancel ACH recurring contributions

### ISSUE THREAD

**Issue by IowaBoy1** [iATSPayments/com.iatspayments.civicrm#341]
Drupal 7.73
Civicrm 5.28
iATSPayments 1.7.3

Since upgrade to 1.7.3--In the backend on the Contact profile we cannot cancel recurring contributions that are via ACH. If they are CC we can cancel them. The Cancel Button on the ACH seems dead--it does not do anything.

I looked at the iATS settings and I have:
Disable extra edit fields for Recurring Contributions  UNCHECKED

Enable self-service updates to recurring contribution Contact Billing Info.  UNCHECKED

Allow self-service updates to recurring contribution amount.  UNCHECKED

Enable self-service cancellation of a recurring contribution.  CHECKED

Under the Drupal Access Control
Our backend users have the ability:
CiviContribute: access CiviContributeRecord backend contributions (with edit contributions) and view all contributions (for visible contacts)
CiviContribute: edit contributionsRecord and update contributions

There are no error messages in the Civi or Drupal Log files

Not sure if this is directly related but it is since the update
Backend users can no longer update recurring payment information.
Cannot Adjust the # of installments
Cannot Adjust next process date

We no longer see an EDIT option with the recurring contribution, just View & Cancel
If we click View and scroll to the bottom of the pop-up we see edit and we can edit the CC expiry, ect.

**Comment by adixon** [comment]
Thanks for this. The new self-serve options made this functionality quite complicated and we don't have this in our testing grid apparently.

**Comment by adixon** [comment]
ACH/EFT now has cancel and editing links when enabled/for adequately authorized users, with this commit:

https://github.com/iATSPayments/com.iatspayments.civicrm/commit/a250198d6a83575c6441f848523dd02edbbf9e12
