### ISSUE TITLE
Can not Edit ACHEFT recurring series

### ISSUE THREAD

**Issue by KarinG** [iATSPayments/com.iatspayments.civicrm#344]
Admin has Edit on CC recurring series - but not for ACH:

<img width="1328" alt="image" src="https://user-images.githubusercontent.com/5340555/100931632-06e8c400-34a8-11eb-98f9-fc145e0992da.png">

**Comment by adixon** [comment]
Ah yes, because ACH/EFT 'self serve' options isn't implemented yet. Todo!

**Comment by KarinG** [comment]
I’m talking about edit Amount and Next Scheduled Date fields. Admin had an Edit for that in 1.6.x

**Comment by KarinG** [comment]
This is w/ 1.6.x -> 
![image](https://user-images.githubusercontent.com/5340555/101048075-95f4eb00-353f-11eb-86aa-a695c9604d96.png)

**Comment by adixon** [comment]
Understood. 1.7 isn't 1.6 though ...

Specifically, these functions were refactored recently and I haven't fully implemented the hooks.

**Comment by cmmadmin** [comment]
We just upgraded from 1.7.2 to 1.7.3 and now the Edit option for an Active Recurring Contribution is gone.

I do see it when logged as our administrator user (username=admin) which has the "administrator" Drupal role. But, have not been able to find a permission that will allow other users to see it. It does not even appear if I give another user the "administrator" Drupal role.

Here's what we see when logged with username=admin (which is consistent with what we saw with 1.7.2 for other users):

![edit-option](https://user-images.githubusercontent.com/6864440/110504457-cd38e200-80c2-11eb-9785-eee78a8408d0.jpg)

And here's what we see now with other users (NOTE: This is for a *Credit Card* recurring contribution):

![no-edit-option](https://user-images.githubusercontent.com/6864440/110504471-d0cc6900-80c2-11eb-8cb3-d226fab0d339.jpg)

This is a very important feature that our finance team uses often to edit recurring donations. Is there some way I can provide the edit feature for our finance team?

**Comment by adixon** [comment]
The short answer is: you can get that back by enabling the self-service of those features. Here's the relevant code (for cc, it's different for each CC/ACH and 1stpay/legacy combination).

https://github.com/iATSPayments/com.iatspayments.civicrm/blob/5a1a4e2db7573f914b4ae06abe961c48d1cf217d/CRM/Core/Payment/iATSService.php#L122

That code is supposed to allow access to the edit link for anyone with the 'Access CiviContribute' permission, and I believe it did with the civi version that we released 1.7.3 with, but it seems that code doesn't always work.

If you don't want to enable self-service, then you could try figuring out why that code doesn't work for the particular case you're looking at.

**Comment by KarinG** [comment]
@cmmadmin -> The issue Edit on recurring CC -> has been fixed -> https://github.com/iATSPayments/com.iatspayments.civicrm/commit/6bd647b945a0a4c515b4056d6117ddb1c25e5ac0

But that's not in a release yet. 

I'll talk to Alan about issuing a new release -> but in the mean time: take a look at the commit I referenced here 👆.

**Comment by adixon** [comment]
ACH/EFT recurring schedules are now editable as well with https://github.com/iATSPayments/com.iatspayments.civicrm/commit/a250198d6a83575c6441f848523dd02edbbf9e12

**Comment by larssandergreen** [comment]
Thanks for this @adixon!
Just wanted to note that I'm getting a warning when editing a recurring ACH/EFT that I have updated the contribution amount, even if I haven't updated the amount (or indeed done anything other than clicking edit and then save).

**Comment by adixon** [comment]
Agreed that this warning isn't very smart. All it knows is that you submitted something, it's not comparing against the previous values.
