### ISSUE TITLE
State is required even when non is present

### ISSUE THREAD

**Issue by shaneonabike** [iATSPayments/com.iatspayments.civicrm#346]
We discovered a bit of a issue with processing payments from Malta. Essentially, there are no provinces or states for this country, but unfortunately this field remains required. As a result, the payment cannot be processed for our users who are living and/or from there.

Is there a quick fix for this perhaps?

**Comment by adixon** [comment]
I'd try manually inserting a province of "Malta" for the country of Malta (in your civi database, some assembly required!).

If you're using the legacy processor, I don't think the address is always required, though I suspect that payments coming from a malta address are going to be scrutinized for card-tumbling.

You could talk to iATS and check what their actual backend-processing requirements might be.

**Comment by shaneonabike** [comment]
Perfect that seems to have worked. A quick solution that isn't great but it's somewhat an edge case. Thanks!
