### ISSUE TITLE
After upgrade Extension 1.6.2 to 1.7.3 It is showing Class not found 

### ISSUE THREAD

**Issue by jagjeetj** [iATSPayments/com.iatspayments.civicrm#347]
On submission the contribution it is showing  Error: Class 'CRM_Iats_iATSServiceRequest' not found in CRM_Core_Payment_iATSService->doPayment() (line 179 )
CiviCRM : 5.28.3
Drupal : 7

**Comment by adixon** [comment]
I'd recommend you update civicrm to 5.28.4, the latest patch release of that minor version.

But your error suggests that maybe you need to clear some caches. There were quite a few files renamed and moved around on the 1.7.x branch.

**Comment by jagjeetj** [comment]
Hi @adixon 
I have updated civicrm version 5.32.2 and also clear the caches with cv flush command. But issue is still same.
Error: Class 'CRM_Iats_iATSServiceRequest' not found in CRM_Core_Payment_iATSService->doPayment() (line 179 of /sites/all/custom_ext/com.iatspayments.civicrm/CRM/Core/Payment/iATSService.php).
CiviCRM : 5.32.2
Drupal : 7

**Comment by adixon** [comment]
I'm pretty confident this is not an issue with the iats extension code per se, but something about your installation, since finding classes is part of the civicrm code base, not something the extension is responsible for (yes, assuming things are named properly ...).
