### ISSUE TITLE
Stop using CRM_Core_Error::fatal() and throw exceptions instead

### ISSUE THREAD

**Issue by mattwire** [iATSPayments/com.iatspayments.civicrm#349]
The `CRM_Core_Error::fatal()` method is deprecated and should be replaced by throwing an exception.

**Comment by adixon** [comment]
Fixed with https://github.com/iATSPayments/com.iatspayments.civicrm/commit/73bd7ec9527e4690c0b61a841c5dbc53173d60d8

Thanks @mattwire
