### ISSUE TITLE
Suppress iATS Payments Administration link for 1stPay

### ISSUE THREAD

**Issue by yashodha** [iATSPayments/com.iatspayments.civicrm#353]
This link appears in the Contribution submenu :
https://mysite/civicrm/iATSAdmin

This should be suppresed for 1stPay

**Comment by adixon** [comment]
The extension provides this item to the navigation menu, not the individual payment processor (the extension provides multiple processors).

If you're not using one of the legacy processors, you can just disable the navigation menu item.
