### ISSUE TITLE
PHP Warning:  A non-numeric value encountered in com.iatspayments.civicrm-1.7.3/CRM/Core/Payment/iATSService.php on line 422

### ISSUE THREAD

**Issue by yurg** [iATSPayments/com.iatspayments.civicrm#354]
PHP version: 7.4.8
`PHP Warning:  A non-numeric value encountered in com.iatspayments.civicrm-1.7.3/CRM/Core/Payment/iATSService.php on line 422`

**Comment by adixon** [comment]
Thanks - the code has been implicitly casting strings to numbers, time to make the explicit.

**Comment by adixon** [comment]
Fixed w/ https://github.com/iATSPayments/com.iatspayments.civicrm/commit/1b29f1592a0c5f274457c59bf8901c1a217c70f5
