### ISSUE TITLE
Notice: Undefined index: price_field_value_id in CRM_Iats_Transaction::getContributionTemplate() (line 41 of /.../sites/default/files/civicrm/extensions/com.iatspayments.civicrm/CRM/Iats/Transaction.php).

### ISSUE THREAD

**Issue by IowaBoy1** [iATSPayments/com.iatspayments.civicrm#358]
Drupal 7.78
CiviCRM 5.35.1 (just updated from 5.28 last night)
iATS Payments 1.7.4

We updated Civi last night, today we are getting the following notice in the logs and it is not recording the correct amount in the line item table. 
Notice: Undefined index: price_field_value_id in CRM_Iats_Transaction::getContributionTemplate() (line 41 of /.../sites/default/files/civicrm/extensions/com.iatspayments.civicrm/CRM/Iats/Transaction.php).

We had a contribution for $750. In iATS and the contribution table we have 750. But the line item table shows $7 for the unit_price and line_total 
Another example is $130 and unit_price and line_total show $1.

But it does not seem to be happening on all donations.
An additional note:We do use Civi Webfrom Integration for our donation forms. It might be related to this instead of iATS because it is happening on the one form only. But since the notice pointed to iATS I started here.

**Comment by adixon** [comment]
When generating a recurring contribution in an existing sequence, the extension tries to properly handle line items by reproducing them on the new contribution, based on an appropriate candidate. Here's where that starts.

https://github.com/iATSPayments/com.iatspayments.civicrm/blob/1a41b7eea8d340ee3a7b17a1e8eeba12a006d229/CRM/Iats/Transaction.php#L29

What your notice is identifying is that your template contribution's line items are missing their "price field value id", which can happen with webform civicrm.

In cases like that, trying to reproduce the line item is tricky, though it's not clear to me why it should become an issue with the civi upgrade.

In any case, at this stage, the iATS extension is just making a best effort with what it has. If you have any ideas about improving it, I'm happy to reconsider.

**Comment by KarinG** [comment]
I think the solution is for me to fix this (once and for real) in webform civicrm. I've added it to our D8/9WFC ToDo list. Once we have it working there and secured with a test - then we can look at backporting it to D7.

**Comment by IowaBoy1** [comment]
These are first time contributions, not part of a recurring series. My scheduled recurring for today all processed correctly.
I had 5 event registrations that all look correct on the line item table.

But I had one new contribution (the only new contribution today) that did not record anything in the line item table.  The ones from yesterday recorded in the line item table but they only had the first digit of the contribution amount.

**Comment by adixon** [comment]
Hmm, that doesn't make sense. A one time contribution doesn't need to get a contribution template, nor does a first contribution in a sequence. Unless you've got an option for allowing future recurring enabled, that kind of changes all the flows.

**Comment by IowaBoy1** [comment]
I did have future recurring enabled. I have disabled that so we will see what happens now.

**Comment by KarinG** [comment]
"recorded in the line item table but they only had the first digit of the contribution amount" - that sounds really scary!

I've seen some reports like that: "[UNCONFIRMED REGRESSION] CiviCRM 5.35.1, truncation of money values where $1,000 donation is recorded as $1 which appears to be truncating at the thousand separator when using the Australian (AU) Locale"

This issue was reported by an AU partner who is not using iATS -> It's logged here: https://lab.civicrm.org/dev/core/-/issues/2493 - does that sound like what you're observing? Some recent changes in core re: Order API are suspected to have caused this.

**Comment by IowaBoy1** [comment]
I had not thought about it being a truncating at the thousands separator. In my original posting I had said the contributions were $750 and $130. But they were actually $7500 and $1300. So you might be on to something.

**Comment by IowaBoy1** [comment]
And the one today was under 1000 so maybe that is why it did not record anything

**Comment by KarinG** [comment]
If you can add your experience to that ticket with as many details as possible as this appears to be a difficult scenario to reproduce -> that would be helpful to the Core team: https://lab.civicrm.org/dev/core/-/issues/2493

**Comment by IowaBoy1** [comment]
Thanks, I posted there

**Comment by IowaBoy1** [comment]
This was fixed here https://lab.civicrm.org/dev/core/-/issues/2493
Thanks Karin
