### ISSUE TITLE
We want to put Financial Account into line item Description field

### ISSUE THREAD

**Issue by JoeMurray** [iATSPayments/com.iatspayments.civicrm#36]
Any objections to us providing a PR to post Financial Account information into the transaction so that it shows up on the IATS terminal when reviewing transactions? Could you provide a link to the version of the iATS API documentation that you are using? Thanks!

**Comment by JoeMurray** [comment]
Do you have an email for Stephen? The subaccount approach doesn't work when line items in the same transaction need to go to different revenue accounts.

**Comment by adixon** [comment]
Can you provide a bit more background here? Under what circumstances does CiviCRM's bookkeeping not work here? [I can guess, e.g. if you're using an iATS account with other software or a POS terminal, or whatever, but I'm just curious]. How would this bookkeeping information get used?

There is a reasonably robust way of matching up transactions between civicrm and iATS (both directions), so it should be possible to generate reports of what you want from CiviCRM, I think.

The key issue here is that we don't have any free fields in which to send additional data to iATS. There is a comment field we are now using as a kind of civicrm-version signature, which in theory could get some additional string content, but it's not available with all soap methods (yet).
