### ISSUE TITLE
Recurring contributions fail, nothing sent to iATS

### ISSUE THREAD

**Issue by SoundSailor1** [iATSPayments/com.iatspayments.civicrm#366]
CiviCRM 5.36.1 iATS 1.7.4 Drupal 7
Our recurring contributions are failing, all other contributions are being processed as expected. I've checked with iATS and we are confirmed as being set up for recurring payments. However, iATS hasn't received any payment request for these contributions. Nothing in the CiviCRM log that seems related to this (note since I don't have shell access on the server, the only log messages are what I can see through the CiviCRM Log Viewer extension). Also not showing up in Drupal logs.

At the Contributions console the contributions are listed as "Pending (Incomplete Transaction)". If you "View" the transaction, everything appears correct including a Invoice Reference, however, under payments it says: "No payments found for this record".

We're new to CiviCRM and the iATS extension so we've never had a successful recurring contribution. A possible set up problem, the url for regular and recurring payments is the same, is that correct. We are using the legacy processor.

**Comment by KarinG** [comment]
Hi @SoundSailor1 - can you please post some screenshots? For example -> CiviCRM Contribution page config + iATS Payments - Recurring Contributions Report - etc. That will help us figure out what may be missing in your config/set up.

**Comment by SoundSailor1** [comment]
Thanks KarinG for your quick response. After some more investigating, it appears that the two recurring contributions in question were not made with the iATS payment processor. They were made with PayPal Express which doesn't appear to report back to CiviCRM. I'll leave this open for a few days to do more testing, but it appears that the iATS processor is working as expected.

**Comment by KarinG** [comment]
Ah - excellent - glad you found an explanation! 🙂
