### ISSUE TITLE
Credit Card validation for backend forms when using SWIPE, CiviCRM 4.4+

### ISSUE THREAD

**Issue by adixon** [iATSPayments/com.iatspayments.civicrm#38]
The SWIPE processor works by putting an encrypted credit card string into the credit card field and then clears the credit card type field. This works for 4.3.

But the strategy is broken for civicrm 4.4+ (since this commit: https://github.com/civicrm/civicrm-core/pull/1730), because the validateCreditCard code now generates an error if the credit card type field is empty.

Since core is being reasonable, I think we need a different strategy - the overloading of the use of the credit card field is not very future-safe anyway.

Instead, I think we need to work with core to allow payment processors to provide their own validation logic - for swipe, we probably don't want any validation to happen, but perhaps there is some that we do, at least to prevent sql injection type hack attempts and or to prevent too many bad calls to iATS servers.

Still thinking about what an appropriate core patch might look like in the interim to allow this payment processor to work for the admin pages.

**Comment by KarinG** [comment]
For the time being a small patch to CiviCRM core is required if you'd like to use SWIPE on Public Contribution pages. On Backend pages this is not necessary. You can find iATS_4.4.10.diff and iATS_4.5.4.diff in the repository.

Alan has worked on a patch to fix this permanently in CiviCRM Core:
https://github.com/civicrm/civicrm-core/pull/4766
