### ISSUE TITLE
Donors cannot update credit card info with iATSPayments (July 2022)

### ISSUE THREAD

**Issue by IowaBoy1** [iATSPayments/com.iatspayments.civicrm#390]
CiviCRM 5.51.1 iATSPayments 1.7.4

Our donors do not have the ability to update their credit card on file. They have the "View" link but not the edit.

I checked the settings in /civicrm/admin/contribute/iatssettings and the 3 enable self-service boxes are checked. I looked at the Drupal permissions. The CiviContribute: edit contributions was not enabled for Donors. I checked that box, flushed cache, but they still do not see the Edit link.

I tried several urls but get access denied messages [https://secure.radiusinternational.org/civicrm/contact/edit/iatscustomerlink?reset=1&cid=11482&customerCode={iATS](https://secure.radiusinternational.org/civicrm/contact/edit/iatscustomerlink?reset=1&cid=11482&customerCode=%7BiATS) Code}&paymentProcessorId=3&is_test=0

This one gives me a hard fail [https://secure.radiusinternational.org/civicrm/contribute/updatebilling?reset=1&crid=964&cs={contact.checksum}](https://secure.radiusinternational.org/civicrm/contribute/updatebilling?reset=1&crid=964&cs=%7Bcontact.checksum%7D)

**Comment by adixon** [comment]
In my tests, I'm not seeing any issues with this functionality. Even with the 'edit contributions' not checked and only the first self-service option "Enable self-service updates to recurring contribution Contact Billing Info." checked.

I'm able to edit the cc info when authenticated with no other permissions and following the link in the dashboard.

It looks like this: 

/civicrm/contribute/updatebilling?reset=1&crid=87

I'm also able to edit the cc info when not authenticated and just following the link sent in the invoice.

In that case, it looks like this:

/civicrm/contribute/updatebilling?reset=1&coid=1158&cs=8768e44e268932759a6b17481e588c97_1659724452_inf

The first url you're showing is an admin-only form, not one you'd use for client self-service updates.

The second one I suspect is being generated incorrectly - it appears that the anonymous one with the contact checksum uses a different other parameter now (i.e. not the id of the recurring contribution, but what appears to be the lastest contribution id in the sequence).

**Comment by IowaBoy1** [comment]
I am sorry. I did not test the receipt urls. I thought our office was saying the receipt links do not work. I just tested them and they work great.
