### ISSUE TITLE
Recurring transactions are not bringing back Credit Card Type i.e. "Visa", "MasterCard", "Discover"

### ISSUE THREAD

**Issue by elisseck** [iATSPayments/com.iatspayments.civicrm#392]
I don't know if this is even possible to get from iATS when they run a card for the second, third, etc time. I'm not really sure what the mechanism is that the CiviCRM form uses to fill this in the first place either. Issue symptom looks like this:

![iats_recurring](https://user-images.githubusercontent.com/12917373/189385917-6d57cad3-dfd2-45b4-abaf-d03857179059.png)

If a user configures credit card reconciliation reporting that filters on "credit card type", any recurring transaction after the first one is missing from the report, causing some amount of confusion.

Normally, I'd be happy to contribute a fix, but I'm just not at all set up for testing recurring transactions with iATS. Low priority, however!

(Tested in the wild only on iATS v1.7.4 w/CiviCRM v5.49.5)

**Comment by adixon** [comment]
Yeah, interesting point. The card type (and last 4 digits) are stored by civicrm core by grabbing them with javascript and saving them during form submission. It's not an extension function.

Subsequent payments in a recurring sequence use the card information stored in iATS - i.e. during that transaction, there's no access to the card number or card type.

In general, the extension could make a reasonable guess that the card type and last four digits are the same as the initial contribution in a sequence, but it sounds like an issue that wouldn't be unique to iATS and might be a useful functionality to include in the new 'contribution template' functionality.

**Comment by elisseck** [comment]
Oh interesting I'm not yet familiar with the new "contribution template" functionality.

Good to have this somewhat documented here, but it sounds like there isn't much to be done here and this can be closed and moved to a civicrm-core issue if the more reasonable fix is beyond the scope of the processor itself.
