### ISSUE TITLE
Recurring payment token is not being set

### ISSUE THREAD

**Issue by shaneonabike** [iATSPayments/com.iatspayments.civicrm#397]
## Problem

I have a strange issue with someone I work causes the following issue. What I find odd is that this isn't happening on other sites so is this like an iATS configuration on their end or some communication issue between Civi and iATS?

+ Payment goes through
+ No recurring payment token setup

## How to reproduce

1. Go to a membership page
2. Select a membership type
3. Choose recurring
4. Add credit card details
5. Process
6. View in the iATS report that the payment went through but no payment token id is set

## Suggestions

Maybe we could add error messages into the log is the payment token id is not returned _and_ a person has set recurring. I noticed in the code that no message is being sent out so it might help to debug.

If anyone has insight I'm all ears.!

**Comment by adixon** [comment]
Interesting, and yes, anything with money needs extra debugging/logging.

The "recurring payment token setup" is a few things, I wonder which one you're talking about?

There are two "transactions" with iATS when starting a new recurring sequence. The first one sets up a 'customer' record at iATS, and links it to a token in the civi system, and then the second bit does the transaction with that token.

Are you able to see if the customer record is setup? When you say "no recurring payment token setup", what exactly are you looking at? Or do you mean that no schedule is setup?

**Comment by shaneonabike** [comment]
Hey,

Sorry you're right I was being vague because I hadn't completely debugged the situation, but I got it... and it's a funny one. This might need to be reported upstream but I'm going to start here.

## Recreate

1. Create a Membership Contribution page
  + Check-off _Contribution Amounts section enabled_
  + Don't set recurring for the Contribution Amounts (although another interesting testing scenario)
  + Add a Membership with the option to renew
  + Check off Separate Membership payment_ <== this is the key
3. Use this form (test or live)
4. Choose not to add an additional contribution
5. Choose your membership and check-off auto-renew
6. Process the form
7. No client code is returned, client is set as auto-renew but there is no payment token setup

![Selection_001](https://user-images.githubusercontent.com/1126026/201234614-daaba710-a38d-4628-a843-951a2152dcf8.png)

## Debugging

```
nov. 10 19:06:12  [warning] params array (
  'qfKey' => 'cut',
  'entryURL' => 'cut',
  'email-Primary' => 'cut',
  'first_name' => 'Administrateur',
  'last_name' => 'SymbioTIC',
  'street_address-1' => '312312',
  'city-1' => '312',
  'postal_code-1' => '312',
  'country-1' => '1039',
  'state_province-1' => '1110',
  'phone-Primary-1' => '321312',
  'preferred_language' => 'fr_CA',
  0 => '',
  1 => '',
  'group' => 
  array (
    2 => '',
    3 => '',
  ),
  'custom_11' => 'test',
  'contact_sub_type_hidden' => 'Membre_ami',
  'hidden_processor' => '1',
  'credit_card_number' => 'testcc',
  'cvv2' => '123',
  'credit_card_exp_date' => 
  array (
    'm' => '5',
    'Y' => '2032',
  ),
  'credit_card_type' => 'Visa',
  'billing_first_name' => 'Administrateur',
  'billing_middle_name' => '',
  'billing_last_name' => 'SymbioTIC',
  'billing_street_address-5' => '312312',
  'billing_city-5' => '312',
  'billing_state_province_id-5' => '1110',
  'billing_postal_code-5' => '312',
  'billing_country_id-5' => '1039',
  'payment_processor_id' => '4',
  'auto_renew' => true,
  'priceSetId' => '9',
  'price_16' => '60',
  'price_18' => '-1',
  'selectProduct' => '',
  'MAX_FILE_SIZE' => '83886080',
  'ip_address' => 'cut',
  'amount' => '30.000000000',
  'amount_level' => 'null',
  'selectMembership' => '4',
  'year' => '2032',
  'month' => '5',
  'card_type_id' => 1,
  'pan_truncation' => '2220',
  'currencyID' => 'CAD',
  'is_pay_later' => 0,
  'is_recur' => 1,
  'frequency_interval' => '1',
  'frequency_unit' => 'year',
  'invoiceID' => 'cut',
  'is_quick_config' => 1,
  'email-5' => 'cut',
  'description' => 'Contribution en ligne: Adhésion Membre Ami',
  'accountingCode' => NULL,
  'is_test' => 1,
  'campaign_id' => NULL,
  'middle_name' => '',
  'email' => 'cut',
  'street_address' => '312312',
  'city' => '312',
  'state_province' => 'QC',
  'postal_code' => '312',
  'country' => 'CA',
  'cms_contactID' => '2',
  'skipLineItem' => 1,
  'total_amount' => '30.000000000',
  'tax_amount' => 0.0,
  'contactID' => '2',
  'financialTypeID' => '2',
  'trxn_id' => NULL,
  'contributionID' => 384,
)

nov. 10 19:06:12  [warning] is_recur: false
```
In our case (at least), I tracked down the problem to this [line](https://github.com/iATSPayments/com.iatspayments.civicrm/blob/4f618152547fc9f958ab26e5a10808046e7c9715/CRM/Core/Payment/iATSService.php#L180) of code. Essentially, it is checking to see if ```is_recur``` is set (which it is), and also if there is a ```contributionRecurID```. 

Ironically, if I _don't_ separate the actual Contribution and Membership charges all goes through like butter on bread. So my bigger question is how does this value get set in the ```$params```, and how can we fix it? I figure this is fairly major issue, but perhaps hasn't come up for other b/c memberships with extra contributions aren't that common :shrug: 

cc @adixon

**Comment by shaneonabike** [comment]
> Are you able to see if the customer record is setup? When you say "no recurring payment token setup", what exactly are you looking at? Or do you mean that no schedule is setup?

Just to be definitely clear to answer your question. In my case, the ```is_recur``` is failing from what I can tell and therefore assumes it's a normal transaction and processes it as such. So basically, the issue lies in why the ```contributionRecurID``` is not set but I wasn't sure if that was a core process or not?

**Comment by adixon** [comment]
Yeah, think the 'separate membership payment' is going to be the key here, I'm not really sure how that works in core, it's not something that payment processor code handles specifically.

In theory, it should be asking for a one-time as well as a separate recurring contribution, or else for two separate recurring contributions, right? But it's not.

It really is difficult to implement all the features that civicontribute claims to support, particularly with abstracting out the payment processing into processors that work in different ways and support different features [currency! recurring! cc vs. ach/eft!]. And a single form that gives you an option to choose different processors!

I recall having grief with the 'separate membership payment' in the past and I now avoid it, I'll be you can find some discussion about it, maybe on stackexchange.

**Comment by shaneonabike** [comment]
Hey,

I think that's fair. I spoke to my team after discovering the issue and they also reported having the same issue (long after I figured it out :rofl: ). I don't mind if we don't find a solution, but could I propose two solutions.

+ Add something in the README/Wiki to reflect that situation
+ Add maybe a debug message indicating that ```is_recr``` is set but there is a missing ```contributionRecurID``` and then allude to the fact that it could be due to Seperate option. I think it's just going to help others in the future since this is kind of obscure.

Thoughts?

**Comment by adixon** [comment]
Well, if it doesn't actually have anything to do with the extension, that best to raise it as a core issue, no?

**Comment by shaneonabike** [comment]
Yes and no. I guess what I was waiting from you was to understand if ```contributionRecurID``` was coming from core or not. I take it from your response it is. So I am happy to report this upstream.

I _still_ wholeheartedly think that a little warning on the README might alter people until this is fixed. And I also think a little error message could be good do, because truly the combo of ```is_recur``` and no ```contributionRecurID``` is odd and probably should be reported.

This way we ensure that people see there is something off, and if there is some bug in the future in core than you are catching it directly in your extension. :)

**Comment by adixon** [comment]
The doPayment function is where core hands off processing to the payment processor extension, so the core bug you've identified is that it's passing in is_recur without a contributionRecurID value. Those "params" are the POST values from the form, at least historically, and still, as you can see, mostly. Though I suspect core is getting more sophisticated with its handling at this stage.

The simple recommendation to core would be to not send a doPayment function that has is_recur if it doesn't have a contribution recur id - core should stop before sending it to the extension. Maybe it makes sense for there to be a static doPayment function that does some sanity checks before invoking the extension-specific doPayment.

Unfortunately, it looks like doPayment is scattered all over the place.

The specific problem you've identified appears to be from near this code:

https://github.com/civicrm/civicrm-core/blob/d6a6364a87aa97a26a4aee0d8561e30c885e0e8f/CRM/Contribute/Form/Contribution/Confirm.php#L1711

**Comment by adixon** [comment]
I think it's fair to error instead of silently ignoring bad arguments to doPayment, so I've updated all the doPayments to error instead.
https://github.com/iATSPayments/com.iatspayments.civicrm/pull/401
https://github.com/iATSPayments/com.iatspayments.civicrm/pull/402

**Comment by shaneonabike** [comment]
Awesome! Thanks for doing that. I agree that it should just fail also since it's confusing and is just leading to issues. Plus if something breaks upstream then you are accounting for that here.

I also reported an [issue upstream](https://lab.civicrm.org/dev/core/-/issues/4019) because clearly the issues starts there!

Have a great weekend!
