### ISSUE TITLE
All recurring contributions process 2Xs

### ISSUE THREAD

**Issue by IowaBoy1** [iATSPayments/com.iatspayments.civicrm#408]
This started for us last week on the the Jan 18th. All recurring contributions process 2Xs 10 minutes apart.
There is no record of the duplicate in Civi, no errors in Drupal or Civi, Civi logs show the first set but not the second set. The donor record only shows the first contribution.

In iATS portal, we can see both times. The odd thing is that if a donor changed their recurring amount, it processes first at the new amount and the second time at the old amount. 

I talked with iATS and they say that Civi is triggering this twice. 

In our Civi data base looking at log_civicrm_iats_journal, I see 2 entries for the day. It is one for each time. However, in the previous months (when it was processing correctly) there are 5 entries for the day.  All 5 of these entries have the same Invoice number and time whereas the 2 entries since the problem have different Invoice numbers and the time is 10 minutes apart just as we see in iATS.

Some additional information, on the 18th I was notified by clients that our website was down. If you went to our website you got a message that our account was suspended. Apparently our host was moving servers or something--without letting us know that there would down time ;(  Anyway, when we found this issue, I asked what they did that would have caused this issue and they responded with the following: 
Re: the DNS change, I actually haven't made any changes to your DNS settings. In fact, nothing really changed at all. Here's what happened:
The current data center was purchased
The new data center started doing a bunch of migrations before they said they would
They suspended your account on server "a" and migrated it to server "b", then sent us an email to change the IP address
Instead, we unsuspended your account and have been preparing a migration away from that data center entirely
So, technically, there were no record changes on our end. I'm not sure how any downtime would cause what you're describing, but it's software, so anything is possible.

Any ideas what would cause the breakdown in communication between Civi and iATS?

**Comment by KarinG** [comment]
Ok that really sounds like you have two active civicrm instances each running cron (and thus creating/processing the recurring contributions).

**Comment by KarinG** [comment]
Re: `The odd thing is that if a donor changed their recurring amount, it processes first at the new amount and the second time at the old amount.` 

-> two CiviCRM instances.

**Comment by adixon** [comment]
Yes, I'd strongly confirm Karin's diagnosis - particularly with the "moving the data center" note.

The journal table is pulling data from iATS, that's why it shows the second/duplicate transaction.

If you want to see what transactions were initiated from the instance you're looking at, then these two tables have them:

civicrm_iats_request_log
civicrm_iats_response_log

**Comment by IowaBoy1** [comment]
Thanks guys! I am pretty sure this must be it. I checked out the civicrm_iats_request_log in the database that I have and I can see the first request but not the second request.
I have asked our host to find the second instance. In the mean time, I am turning off our recurring cron.

**Comment by IowaBoy1** [comment]
Thanks Karin & Allen, our host had 2 instances running. They shut down the extra one and I re-enabled our recurring cron on our side and it only ran one time. Thanks!
