### ISSUE TITLE
ACH: Error dialog for missing Transit Number, Bank Number, etc

### ISSUE THREAD

**Issue by shaneonabike** [iATSPayments/com.iatspayments.civicrm#410]
## Issue

I discovered a strange scenario whereby if you are in the Transit Number field and click on another one of the ACH fields then you get an infinite number of warning dialogues. The only way to get out of this is to click to another browser or window.

I think the issue stems from perhaps the JS checking to see if the field the person is leaving has been completed, but I'm not sure. Ironically, if I am in the Transit Number and click up to a Price Set to modify something I get one error and that's it.

## How to reproduce

1. Create a new Event
2. Attach a Price Set
3. Add an ACH processor
4. Click on the Transit Number field
5. Click on the Bank Number field
6. Receive an error dialog for both that continues

## What did you expect

The dialog would appear perhaps for the active field that the person is clicking out of, but not others. I think in this situation because the warning dialog appears it's removing the focus and thus firing the warning for the other field that I also clicked on.

**Comment by adixon** [comment]
Okay, minor update to js, now in master. Could be in a new release shortly!

Thanks again for the report.

**Comment by shaneonabike** [comment]
Thanks!
