### ISSUE TITLE
Support recurring price change for membership renewal workflow

### ISSUE THREAD

**Issue by elisseck** [iATSPayments/com.iatspayments.civicrm#417]
**Description:**
The payment processor supports changing recurring payment amount from the CiviCRM side (neat!), but right now it will not correctly find a contribution template to update the membership if the price has changed.

**Expected:**
An admin updates the recurring contribution price (civicrm_contribution_recur) in one of many ways. The next iteration of this recurring contribution processes at the new rate, a membership payment entity is created to link the membership, and the membership is then renewed.

**Actual:**
An admin updates the recurring contribution price (civicrm_contribution_recur) in one of many ways. The next iteration of this recurring contribution processes at the new rate properly, BUT no membership payment entity is created to link the membership, and the membership is not renewed.

**Technical:**
[Here is where extension would attempt to get this contribution template](https://github.com/iATSPayments/com.iatspayments.civicrm/blob/451e686c8f1e32a1b1392d083827399eb9649657/api/v3/Job/Iatsrecurringcontributions.php#L123) ([and fail since we've changed the amount based on this code](https://github.com/iATSPayments/com.iatspayments.civicrm/blob/451e686c8f1e32a1b1392d083827399eb9649657/CRM/Iats/Transaction.php#L20))

[Since the template will be empty it will ignore membership here](https://github.com/iATSPayments/com.iatspayments.civicrm/blob/451e686c8f1e32a1b1392d083827399eb9649657/api/v3/Job/Iatsrecurringcontributions.php#L219). No membership will be updated in this situation.

**Proposal:**
Open to ideas here, there are a bunch of slightly different ways one could go about supporting this. I will submit a tentative PR for what is probably the less "big picture" but also smallest impact change, which is once you're trying to process a membership and you've failed to get a `contribution_template`, just check again quickly to see if you can find one without using an "amount" filter because we've changed the price.

Proposal PR: https://github.com/iATSPayments/com.iatspayments.civicrm/pull/418

**Comment by adixon** [comment]
Your diagnosis is good, but the code here is a bit more complicated than you might expect or want.

The new contribution (with it's corresponding membership link) can get created, preferably, using the repeat transaction api, here:

https://github.com/iATSPayments/com.iatspayments.civicrm/blob/451e686c8f1e32a1b1392d083827399eb9649657/CRM/Iats/Transaction.php#L139

There are a number of cases where that path is not followed (e.g. if it's the first of a future-start recurring sequence, where the contribution has already been created), or in various cases of failure, and it's only then that the path you're looking at will be followed.

Conclusion: your PR might be relevant, but it might actually be core code that needs an update. Try putting a debug line just before the line referenced above to see whether the iats extension is creating the new contribution or whether it's getting generated by the repeat transaction api.

**Comment by elisseck** [comment]
@adixon thanks for your comment. I'm a little stumped on where the repeat transaction api in core will touch a membership payment - [are you suggesting that this bit is having the exact same "get the template based on id AND amount" problem in core that I noted above](https://github.com/civicrm/civicrm-core/blob/522bbe426f4f8b5741ac3283efe772a166301e28/CRM/Contribute/BAO/Contribution.php#L2200)?

I'd think if this were the case we'd see this type of failure with other payment processors as well, but maybe they're not using this api - I am unfamiliar with it.

This particular fix was tested by a third party and does work for the workflow I describe above but I agree that could just be coincidence that we need a membershippayment record one way or another and this got it done... but since it's working I am now on volunteer time for this and setting up a new test box connected to iATS to prove this will be slow. At least we have recorded a problem :).

**Comment by adixon** [comment]
Okay, I'll dig into the code again and see. My guess that it was core code doing this was based on not having seen this before with iATS, but it's also possible that ... it's complicated.

It is certainly true that changing recurring membership amounts is going to be tricky, and maybe the right answer is that the extension should not (and maybe isn't) relying on the repeattransaction api.

**Comment by adixon** [comment]
FWIW, I'm pretty sure you're right about all this - I have a client who started experiencing this issue recently.

**Comment by adixon** [comment]
I've just put in a commit that implements your suggestion in a slightly different way, thank you!

https://github.com/iATSPayments/com.iatspayments.civicrm/commit/deca62605fb06383c1a3dbd8ed2697812d894629

**Comment by elisseck** [comment]
@adixon sounds good to me! Thank you for coming back to this!

**Comment by adixon** [comment]
I just ran through a test scenario of updating membership pricing and corresponding recurring contribution amounts and confirmed that a new contribution in a recurring sequence will correctly apply to the membership.

This is about to be included in an RC, hope to make a full release shortly.

**Comment by shaneonabike** [comment]
Sorry to jump onto this one. I am curious when you indicate changing the ```corresponding recurring contribution amounts``` that would mean we would need to modify the upcoming recurring amounts for everyone who signed of for ABC membership which had a hike right? It doesn't just do that automatically with a price hike on a membership. Just wanted to be sure here.

**Comment by adixon** [comment]
Correct - the recurring schedules are a thing apart from the membership amount configuration. If you just increase the membership amount, then the existing recurring schedules don't change and the amount charged is the old amount, and that amount fails to renew the membership. So you want to increase (or decrease!) the schedules and membership amounts in parallel.
