### ISSUE TITLE
[removed in PHP 9.0] Function strftime() is deprecated since PHP 8.1

### ISSUE THREAD

**Issue by jofranz** [iATSPayments/com.iatspayments.civicrm#423]
>Using strftime / gmstrftime functions result in a deprecation notice in PHP 8.1 and later. These functions will be removed in PHP 9.0.

https://php.watch/versions/8.1/strftime-gmstrftime-deprecated#replacements

**Comment by seamuslee001** [comment]
@adixon this can be closed now as your commit here resolves the problem in 1.8.0 https://github.com/iATSPayments/com.iatspayments.civicrm/commit/000544efc34c11ec6b9695690ad89f1aabd1c72a

**Comment by adixon** [comment]
Resolved as per @seamuslee001 comment
