### ISSUE TITLE
Direct Debit UI rewording & organizing

### ISSUE THREAD

**Issue by shaneonabike** [iATSPayments/com.iatspayments.civicrm#426]
One of my clients has recently setup Direct Debit, and have been experiencing about 60% fail rate on Direct Debit. After reviewing the UI a bit with them we realized that there might be an opportunity for some reworkings potentially (?). I also got a bit tripped up on some of the elements.

I could provide a patch if you like to help, and I'm merely proposing that we change some wording and ordering.

+ Either change ```Transit Number``` label to Transit No. or vic versa (in the image)
+ Either change ```Bank Number``` label to Bank No. or vic versa (in the image)
+ Move Bank Account Number just below ```Bank Number```
+ Change the label ```Bank Account Number``` to ```Account No.``` (to be consistant with the image). I also think for ESL (and even myself) this could be confused with Bank Number
+ Move ```Account Holder``` just above ```Bank Name```

![Selection_005](https://github.com/iATSPayments/com.iatspayments.civicrm/assets/1126026/c1dd1f5a-37a8-445a-be59-5c7909b36905)

Let me know what you think

**Comment by KarinG** [comment]
60% fail rate sounds excessive. My first thought would be to check that there are no JS errors on the page that interferes with checking that the transit number is 5 digits and the bank number is 3 digits.

The cheque images (both CAD and USD) were supplied by iATS Payments - they were already using them in their other payment processing gateways/applications.

If you want to change 
Transit Number -> Transit No
Bank Number -> Bank No
Bank Account Number -> Account No

and/or re-arrange the elements, in both the labels as well as the JS check for # digits (example below) -> that would be ok with me. 

<img width="1037" alt="image" src="https://github.com/iATSPayments/com.iatspayments.civicrm/assets/5340555/44c3ef14-3714-4635-bfe6-aafacc37e379">

**Comment by shaneonabike** [comment]
Hi @KarinG 

Yes I checked for general errors, but there really isn't any. I'll have a second look again just to be absolutely sure though.

This client is primarily dealing with ESL (English as a second language), and other folks that might have different limitations and/or struggles. I agree that it's high and I might have misquoted the percentage, but I do think re-organizing would eliminate some confusion.

I'm super stoked you are into that. Let me fix that up and send out a PR request.

**Comment by adixon** [comment]
Resolved, will be in the next release.
