### ISSUE TITLE
Iatsverify scheduled job -  Failed to complete transaction: Expected one Membership but found 3

### ISSUE THREAD

**Issue by yurg** [iATSPayments/com.iatspayments.civicrm#428]
Happens for a contact with inactive memberships. After inactive memberships deletion all works as intended. Perhaps "is_active" check is missing somewhere (  $select_params  https://github.com/iATSPayments/com.iatspayments.civicrm/blob/aef234581146c2bd276d5f6769c83d082f392d13/api/v3/Job/Iatsverify.php#L83 ? )

**Comment by KarinG** [comment]
This extension only handles the contribution side of things. CiviCRM Core is responsible for the consequences of a Completed (or Failed) Contribution in terms of what should happen to the Membership record.

**Comment by adixon** [comment]
I couldn't find that error message, so it must be coming up from CiviCRM core. Can you figure out on what line the error is occuring? My assumption would be that it's during the  completetransaction call, but it could be somewhere else.

Also, please supply your versions and CMS.

**Comment by yurg** [comment]
@adixon Right, sorry, should have put more effort. It is WordPress 6.3 /  CiviCRM 5.63.2 

While trying to reproduce the issue and prepare some meaningful response I found the `civicrm_api3('Membership', 'getsingle', [  'contact_id' => $contactId ]);  ` call in a custom extension  **hook_civicrm_pre**  which caused the **Job.iatsverify** log message.  

So it's so to say my fault - had to add `"active_only" => 1` check. Still not sure why the message in subject appeared in **Job.iatsverify**  logs and not in some other place across the system. 

And this is how the full message looks like: 

`[info] $Failed to complete transaction with = Array
(
    [version] => 3
    [id] => XXXXXX
    [trxn_id] => AF72XXXX:1111111111
    [receive_date] => 2023-08-10 16:31:26
)`
  
 So sorry for the noise - on the other hand,  this worked perfectly as duck debugging ;-)

**Comment by adixon** [comment]
Happy to hear! It would have appeared in the job.iatsverify log message because the error was triggered by the completion of a contribution, which brought in your extension hook, which presumably didn't catch the error so it got passed down to the iatsverify job which did catch it.

Moral of the story, always assume your civicrm api calls might generate fatal errors, and catch them.
