### ISSUE TITLE
Crytogram not being validated on 1stpay

### ISSUE THREAD

**Issue by seamuslee001** [iATSPayments/com.iatspayments.civicrm#433]
We have a client that uses 1st pay processor and we found that on their front end contribution form we were regularly getting back from First Pay error of 

```
Cryptogram: invalid
```

We confirmed that a new cryptogram was being passed every time we submitted the contribution form. We ended up setting the disable cryptogram setting and that allowed the front end form to work

System settings:

Webserver Apache2
PHP version: 8.0
CiviCRM version 5.65.0
CMS: Drupal 9

any thoughts on this @KarinG @adixon ?

**Comment by adixon** [comment]
I recall trying out FirstPay with php8.x on my own site and having issues, here: https://github.com/iATSPayments/com.iatspayments.civicrm/issues/409

I don't think that the corresponding fix (https://github.com/iATSPayments/com.iatspayments.civicrm/pull/416) is in the latest release, so I guess that's another good reason to push it forward.

**Comment by adixon** [comment]
> I don't think that the corresponding fix (#416) is in the latest release, so I guess that's another good reason to push it forward.

I'm wrong, that was in the 1.7.5 release, and it's been running well for me since then, though with php 8.1, not 8.0 (also with apache2, and currently on Drupal 9 and civicrm 5.65.0).

In any case, I've just released 1.8.0.

re: cryptogram, I have seen that error message causing confusion in cases where fields are filled out very quickly. Are you saying that your users are seeing that message but getting the cryptogram successfully set and payment being made?

**Comment by seamuslee001** [comment]
@adixon sorry if I wasn't clear what I was trying to say is this

I added logging to the payment params being sent to iats and with the cryptogram enabled, I was seeing the cryptogram value being sent to the server and for every request it was a different value as you would expect but we were only ever getting Cryptogram: invalid back and therefor the payment was marked as failed

When we changed the setting to disable the cryptogram payments were able to be made

**Comment by adixon** [comment]
Well, I might be learning something new wrt to "disable cryptogram", I don't understand what that might look like. Does that mean the cc fields are being handled by the iATS extension (i.e. a slightly worse PCI exposure)? That would be cool if it worked! And where would you do that?

re: your experience with the cryptogram - the only thing I can imagine would be some kind of configuration setup where the cryptogram is being invalidly generated, e.g. via a test server at FirstPay, or maybe with a different account?

Is this experience limited to one specific install? Can I blame Microsoft or some other server technology here?

**Comment by seamuslee001** [comment]
@adixon I presume so, it seemed to make it behave more like non first pay and the setting I am referring to this one https://github.com/iATSPayments/com.iatspayments.civicrm/blob/master/CRM/Iats/Form/Settings.php#L49 

re account maybe, I think this might be our only main iats client that uses first pay (others use the other credit card option)

In terms of server it is standard Linux php8.0 server as far as I am aware

**Comment by adixon** [comment]
Okay, I think the conclusion here is:
1. There may be cases where the cryptogram doesn't work, for whatever reason, hard to diagnose.
2. There is indeed a mechanism to turn off the crytogram in such cases (and expose yourself as a card merchant to a harder PCI compliance).

**Comment by adixon** [comment]
Hey @seamuslee001  - I wonder if you were being affected by [this issue](https://github.com/iATSPayments/com.iatspayments.civicrm/issues/480)?

I figured out my example by looking in the civi error log, where I saw the address (St. John's) appearing converted with the htmlspecialchars function, which generates a semi-colon, which gets rejected.
