### ISSUE TITLE
Remove use of _paymentObject in contribution form

### ISSUE THREAD

**Issue by adixon** [iATSPayments/com.iatspayments.civicrm#438]
As per https://github.com/civicrm/civicrm-core/pull/28011

Use of _paymentObject in contribution forms is deprecated and will be removed, use the getPaymentProcessorObject() method instead.

**Comment by eileenmcnaughton** [comment]
Just noting that `$this->_paymentProcessor['object']` may be a better alternative in the short-term as we ensure all form support the function

**Comment by adixon** [comment]
This was committed to master on Nov 8
