### ISSUE TITLE
Recurring Contributions (DirectDebit) lose the line item data/records 

### ISSUE THREAD

**Issue by sgladstone** [iATSPayments/com.iatspayments.civicrm#44]
When a automatic recurring contribution (via DirectDebit/ACH) is created using a priceset, the first contribution looks good: All the line item records exist with the expected financial types for each line item.  

HOWEVER, NONE of the following recurring contributions related to that schedule have ANY line item records. 

For example: recurring Direct Debit contribution schedule is created with the following: 
Contribution financial type is "--split--" . The priceset used results in 3 line items:
$25 for financial type "tuition"
$50 for financial type "dues"
$20 for financial type "donation" 

(Total contribution amount is $95) 

The first automatic recurring contrib. looks fine.   However, all the later recurring contribs show total amount $95, all of it for financial type "--split--". There are NO line item records for tuition, dues or donation!

This is only impacting the Direct Debit contributions, thankfully not credit card contributions.

**Comment by KarinG** [comment]
I strongly encourage you to make your Payment Processor Helper extension an ad-hoc post-transaction extension. Let payment processor extensions do what they do - do not make any code edits - then run a post-recurring-bookkeeping extension that distributes the total amount over the applicable line items ad-hoc.
