### ISSUE TITLE
Variable Data - online giving form

### ISSUE THREAD

**Issue by MDMmelroy** [iATSPayments/com.iatspayments.civicrm#442]
Does anyone know of a way, using an online giving form and personalized URL, to track giving based on donorid?

For instance, instead of simply typing in their name and hopeing to find a match, we might have a QR code with a link that looks something like:

https://giving.givenow.com/donate?donorid=12345&campaign=mycampaign

 (where the email/qr code is customized with variable data)

Thanks!

**Comment by KarinG** [comment]
That is not an iatspayments nor a civicrm question (civicrm does not use donorid).
