### ISSUE TITLE
Notification email configuration for recurring payment failures not found

### ISSUE THREAD

**Issue by nc3man** [iATSPayments/com.iatspayments.civicrm#447]
The documentation at https://github.com/iATSPayments/com.iatspayments.civicrm/wiki/Recurring-Contribution-Failure-Handling for this extension says

`You can set an email address in the iATS configuration page to generate an automated email on every job run that includes any of these failures, and which sends a list of those failures.`

We are running iATS 1.80 on CiviCRM 5.69.5 (ESR) and I just don't see how to set that email address.

**Comment by KarinG** [comment]
It's in the iATS Payments Settings -> 

<img width="1497" alt="image" src="https://github.com/iATSPayments/com.iatspayments.civicrm/assets/5340555/b1f6d5a1-58ee-439f-b225-dba66115f7c2">

**Comment by nc3man** [comment]
Thank you so much - that was buried down in a place I wasn't expecting.
Perhaps a more explicit explanation on the wiki page would help. Lovely
extension btw. We've been using it for 7+ years.
-- Karl Rudnick
