### ISSUE TITLE
Creation of dynamic property CRM_Core_Payment_iATSServiceACHEFT::$_profile is deprecated (PHP 8.2/8.3)

### ISSUE THREAD

**Issue by arminpkathrein** [iATSPayments/com.iatspayments.civicrm#454]
From 8.2 or 8.3 (can't recall) this is not compatible anymore.
I've included a potential fix that worked for me
```use Civi\Payment\Exception\PaymentProcessorException;

/**
 *
 */
class CRM_Core_Payment_iATSServiceACHEFT extends CRM_Core_Payment_iATSService
{
   /**
    * We only need one instance of this object. So we use the singleton
    * pattern and cache the instance in this variable.
    *
    * @var object
    * @static
    */
   private static $_singleton = null;

   /**
    * @var array
    */
   private $_profile;

   /**
    * @var array
    */
   protected $_paymentProcessor;

   /**
    * Constructor.
    *
    * @param string $mode
    *   the mode of operation: live or test.
    * @param array $paymentProcessor
    */```

**Comment by adixon** [comment]
Can you be more specific about what is not compatible? And what your fix is?

**Comment by arminpkathrein** [comment]
Dynamic properties are not allowed/supported anymore from PHP8.2 and higher. 
"In PHP 8.2 and later, setting a value to an undeclared class property is deprecated, and emits a deprecation notice the first time the property is set during the lifetime of the application execution."
https://php.watch/versions/8.2/dynamic-properties-deprecated

My fix is adding this to the class:
``` /**
    * @var array
    */
   private $_profile;

   /**
    * @var array
    */
   protected $_paymentProcessor;
```

**Comment by adixon** [comment]
This is a subclass of CRM_Core_Payment_iATSService which should have those in if necessary.

Can you include the error you're seeing in your log?

**Comment by arminpkathrein** [comment]
This was the error in the log: ```Creation of dynamic property CRM_Core_Payment_iATSServiceACHEFT::$_profile is deprecated```.

**Comment by adixon** [comment]
Thank you. [PR here](https://github.com/iATSPayments/com.iatspayments.civicrm/pull/455) has been merged.

This just adds the _profile, not the _paymentProcessor (and in the parent class).
