### ISSUE TITLE
PHP 8.2.25 - notice

### ISSUE THREAD

**Issue by KarinG** [iATSPayments/com.iatspayments.civicrm#469]
Just logging this here for now - this is iATS Extension 1.9.2

```
root@9bc000c201d6:/var/www/drupal/web/sites/default/files/civicrm/ext# sudo -u www-data -E cv ext:upgrade-db
WARNING: "ext:upgrade-db" is deprecated. Use the main "updb" command instead.
Applying database upgrades from extensions
[PHP Warning] Trying to access array offset on value of type null at /var/www/drupal/web/sites/default/files/civicrm/ext/com.iatspayments.civicrm/CRM/Iats/Utils.php:43
```

**Comment by adixon** [comment]
Yup, but not a civi extension issue, that's a change to cv. Maybe documentation issue?

**Comment by KarinG** [comment]
Last line says :-)
`[PHP Warning] Trying to access array offset on value of type null at /var/www/drupal/web/sites/default/files/civicrm/ext/com.iatspayments.civicrm/CRM/Iats/Utils.php:43`

**Comment by adixon** [comment]
What, you're expecting me to pay attention on Monday?

But in other good news, I can blame seamus for that and note that it's a migration of settings one-time thingy.

So I can really kick it down my priority list, right?

**Comment by adixon** [comment]
Resolved with https://github.com/iATSPayments/com.iatspayments.civicrm/pull/470
