### ISSUE TITLE
v1.3

### ISSUE THREAD

**Issue by brucew2013** [iATSPayments/com.iatspayments.civicrm#54]
In CiviCRM Extensions panel, this plug-n shows an update to 1.3 but fails to install due to "unable to extract...ZIP"

Please advise.

**Comment by adixon** [comment]
Sounds like a server permissions problem. Are you maybe mixing web and ssh access?

If you have server permissions, check your web server and/or php log for deails.

**Comment by brucew2013** [comment]
This is the issue. It is apparent in 4.5.5 despite the patch being implemented. Waiting for response from Civi developers.
