### ISSUE TITLE
Upgrade to version 1.3.1 fails with SQL error

### ISSUE THREAD

**Issue by sgladstone** [iATSPayments/com.iatspayments.civicrm#55]
I am getting the following SQL error and stack trace during the upgrade:

CREATE TABLE `civicrm_iats_ukdd_validate` ( `id` int unsigned NOT NULL AUTO_INCREMENT COMMENT 'UK DirectDebit validation Id', `customer_code` varchar(255) NOT NULL COMMENT 'Customer code returned from iATS', `acheft_reference_num` varchar(255) NOT NULL COMMENT 'Reference number returned from iATS', `cid` int(10) unsigned DEFAULT '0' COMMENT 'CiviCRM contact id', `recur_id` int(10) unsigned DEFAULT '0' COMMENT 'CiviCRM recurring_contribution table id', `validated` int(10) unsigned DEFAULT '0' COMMENT 'Status id of 0 or 1 (after validation)', `validated_datetime` datetime COMMENT 'Date time of validation', `xml` longtext COMMENT 'XML response to initial validation request', PRIMARY KEY ( `id` ), KEY (`customer_code`), KEY (`acheft_reference_num`), KEY (`cid`), KEY (`recur_id`) ) ENGINE=InnoDB DEFAULT CHARSET=utf8 COLLATE=utf8_unicode_ci COMMENT='Table to store UK Direct Debit validation information' [nativecode=1050 ** Table 'civicrm_iats_ukdd_validate' already exists]

#	Function	Location
0	CRM_Core_Error::exceptionHandler(Object(DB_Error))	unknown:unknown
1	call_user_func(Array, Object(DB_Error))	/home/london/public_html/sites/all/modules/civicrm/packages/PEAR.php:931
2	PEAR_Error->PEAR_Error('DB Error: alread…', -5, 16, Array, 'CREATE TABLE `ci…')	/home/london/public_html/sites/all/modules/civicrm/packages/DB.php:969
3	DB_Error->DB_Error(-5, 16, Array, 'CREATE TABLE `ci…')	/home/london/public_html/sites/all/modules/civicrm/packages/PEAR.php:564
4	PEAR->raiseError(null, -5, null, null, 'CREATE TABLE `ci…', 'DB_Error', true)	/home/london/public_html/sites/all/modules/civicrm/packages/DB/common.php:1905
5	DB_common->raiseError(-5, null, null, null, '1050 ** Table 'c…')	/home/london/public_html/sites/all/modules/civicrm/packages/DB/mysql.php:898
6	DB_mysql->mysqlRaiseError()	/home/london/public_html/sites/all/modules/civicrm/packages/DB/mysql.php:327
7	DB_mysql->simpleQuery('CREATE TABLE `ci…')	/home/london/public_html/sites/all/modules/civicrm/packages/DB/common.php:1216
8	DB_common->query('CREATE TABLE `ci…')	/home/london/public_html/sites/all/modules/civicrm/CRM/Utils/File.php:284
9	CRM_Utils_File::sourceSQLFile('mysql://london_m…', '/home/london/pub…')	/home/london/public_html/pogstone_extensions/com.iatspayments.civicrm/CRM/iATS/Upgrader/Base.php:109
10	CRM_iATS_Upgrader_Base->executeSqlFile('sql/upgrade_1_3_…')	/home/london/public_html/pogstone_extensions/com.iatspayments.civicrm/CRM/iATS/Upgrader.php:54
11	CRM_iATS_Upgrader->upgrade_1_3_001()	unknown:unknown
12	call_user_func_array(Array, Array)	/home/london/public_html/pogstone_extensions/com.iatspayments.civicrm/CRM/iATS/Upgrader/Base.php:65
13	CRM_iATS_Upgrader_Base::_queueAdapter(Object(CRM_Queue_TaskContext), 'upgrade_1_3_001')	unknown:unknown
14	call_user_func_array(Array, Array)	/home/london/public_html/sites/all/modules/civicrm/CRM/Queue/Task.php:79
15	CRM_Queue_Task->run(Object(CRM_Queue_TaskContext))	/home/london/public_html/sites/all/modules/civicrm/CRM/Queue/Runner.php:186
16	CRM_Queue_Runner->runNext(true)	/home/london/public_html/sites/all/modules/civicrm/CRM/Queue/Page/AJAX.php:44
17	{closure}()	/home/london/public_html/sites/all/modules/civicrm/CRM/Queue/ErrorPolicy.php:80
18	CRM_Queue_ErrorPolicy->call(Object(Closure))	/home/london/public_html/sites/all/modules/civicrm/CRM/Queue/Page/AJAX.php:47
19	CRM_Queue_Page_AJAX::runNext(Array)	unknown:unknown
20	call_user_func(Array, Array)	/home/london/public_html/sites/all/modules/civicrm/CRM/Core/Invoke.php:289
21	CRM_Core_Invoke::runItem(Array)	/home/london/public_html/sites/all/modules/civicrm/CRM/Core/Invoke.php:72
22	CRM_Core_Invoke::_invoke(Array)	/home/london/public_html/sites/all/modules/civicrm/CRM/Core/Invoke.php:52
23	CRM_Core_Invoke::invoke(Array)	/home/london/public_html/sites/all/modules/civicrm/drupal/civicrm.module:456
24	civicrm_invoke('queue', 'ajax', 'runNext')	unknown:unknown
25	call_user_func_array('civicrm_invoke', Array)	/home/london/public_html/includes/menu.inc:517
26	menu_execute_active_handler()	/home/london/public_html/index.php:21
27	{main}

**Comment by KarinG** [comment]
I just upgraded on of our live projects from 1.2.x to 1.3.1 and all is well. 

Perhaps you try run the upgrade twice or perhaps you already had a pre-release version of code (master at some point) before upgrading to 1.3.1 - (sql/upgrade_1_3_001.sql) is expecting it needs to be created (below). So try drop civicrm_iats_ukdd_validate and try again.

CREATE TABLE `civicrm_iats_ukdd_validate` (
`id` int unsigned NOT NULL AUTO_INCREMENT COMMENT 'UK DirectDebit validation Id',
`customer_code` varchar(255) NOT NULL COMMENT 'Customer code returned from iATS',
`acheft_reference_num` varchar(255) NOT NULL COMMENT 'Reference number returned from iATS',
`cid` int(10) unsigned DEFAULT '0' COMMENT 'CiviCRM contact id',
`recur_id` int(10) unsigned DEFAULT '0' COMMENT 'CiviCRM recurring_contribution table id',
`validated` int(10) unsigned DEFAULT '0' COMMENT 'Status id of 0 or 1 (after validation)',
`validated_datetime` datetime COMMENT 'Date time of validation',
`xml` longtext COMMENT 'XML response to initial validation request',
PRIMARY KEY ( `id` ),
KEY (`customer_code`),
KEY (`acheft_reference_num`),
KEY (`cid`),
KEY (`recur_id`)
) ENGINE=InnoDB DEFAULT CHARSET=utf8 COLLATE=utf8_unicode_ci COMMENT='Table to store UK Direct Debit validation information';

**Comment by sgladstone** [comment]
I uninstalled the extension, then dropped the table "civicrm_iats_ukdd_validate" manually.  Then I reinstalled the extension and did not get any error messages during the installation.

**Comment by KarinG** [comment]
Ok be careful uninstalling things - as that will also drop your other tables [which may have data in them]:
DROP TABLE IF EXISTS `civicrm_iats_customer_codes`;
DROP TABLE IF EXISTS `civicrm_iats_request_log`;
DROP TABLE IF EXISTS `civicrm_iats_response_log`;
DROP TABLE IF EXISTS `civicrm_iats_verify`;

Will close this - we verified upgrade to 1.3.1 on 2 different sites today.
