### ISSUE TITLE
When installing extension, database tables aren't being created

### ISSUE THREAD

**Issue by herbdool** [iATSPayments/com.iatspayments.civicrm#56]
I installed v 1.3.1 on a Drupal 7 / CiviCRM 4.4.5 site. When I run a test payment it throws an error "Table 'mydatabase.civicrm_iats_request_log' doesn't exist".

I ended up just running the install.sql manually.

**Comment by KarinG** [comment]
I just installed 1.3.1 (new site) via the CiviCRM GUI (4.4.10) and all tables installed properly:
civicrm_iats_customer_codes  
civicrm_iats_request_log   
civicrm_iats_response_log
civicrm_iats_ukdd_validate
civicrm_iats_verify

**Comment by adixon** [comment]
Herb - can you check your logs? Either the table didn't get created because civicrm already thought it was there (e.g. it thought it was a reinstall), or else your mysql permissions didn't allow it.

**Comment by herbdool** [comment]
Alan, should have done that soon after. But I wonder if it had anything to do with me pushing it via git instead of using the extension gui. Do the same actions get triggered either way?

**Comment by adixon** [comment]
Shouldn't make a difference, I use both install methods on a variety of sites.
