### ISSUE TITLE
What is the purpose of the 4.4.10 / 4.5.6 patch

### ISSUE THREAD

**Issue by eileenmcnaughton** [iATSPayments/com.iatspayments.civicrm#63]
I'm looking at this extension for a customer but want to maintain our CiviCRM so that it works with IATS and other extensions. Looking at the diff what I understand is that it makes it so that 

1) IATS direct debit (or any other direct debit) won't load on a back-office membership or participant payment form. In terms of 'could I add this to fuzion repo' - we don't use any other direct payment systems with our customers yet although Authorize.net is being investigated. However, do you know if this can be generically assumed for direct Debit processors -ie. that they can't work on these backoffice forms.

2) in general you have completely removed credit card validation. If someone is using a non-IATS as well this will apply to both. This issue goes away with 4.6 - so I think i'll figure out the best way to work around that for us

**Comment by KarinG** [comment]
ad 2) this is only necessary if you'd like to use encrypted SWIPE on front-end contribution pages. If you don't use SWIPE or if you only use SWIPE on backend pages (Core does not invoke credit card validation there) - then you don't need this 'patch'. As you know Alan wrote a patch for 4.6 that's a lot more elegant than just taking out the credit card validation. 

leaving ad 1) for Alan to comment on.

**Comment by eileenmcnaughton** [comment]
Thanks Karin - yes 4.6 is a much happier place for payment processor integration :-)

**Comment by KarinG** [comment]
Yes - thank you - thank you - thank you :-)

**Comment by eileenmcnaughton** [comment]
Alan too!

**Comment by adixon** [comment]
re: 1) yes, this is a generic patch that should be in core, but hasn't made it yet (mea culpa).

The issue is that the backend forms don't reload when you switch payment processors, so whichever payment processor gets loaded first is determining the billing fields. It's kind of a big deal if you've got any ach/eft processors, depending on how they get ordered.

**Comment by joemcl** [comment]
So right now we're using Authorize for direct debit and credit cards. We're going to continue to use it for at least the near future while we test iATS for ACH/EFT at least,  and probably continue to use Authorize unless/until we switch credit/debit processing to iATS, which will be gradual. We don't use Swipe. We're on 4.4.10. 

We've finally gotten set up with our iATS account. We have SOAP running as well. 

Based on the above, are we good to go to live test using iATS with the latest extension update just for ACH/EFT?

**Comment by adixon** [comment]
Yes, we've got ACH/EFT working on a number of live sites. You do want use at least 1.3.10 (latest as of today I think), the patches installed for 4.4 and noting that ACH/EFT is only for Canada and US.

There is a learning curve for ACH/EFT due to the nature of the beast (e.g. it isn't actually approved or really looked at for a while, until it goes through some financial pipes and comes back approved).

**Comment by joemcl** [comment]
Alan, Karin wrote above: "If you don't use SWIPE or if you only use SWIPE on backend pages (Core does not invoke credit card validation there) - then you don't need this 'patch'." Eileen wrote re the patch,above: "2) in general you have completely removed credit card validation. If someone is using a non-IATS as well this will apply to both.". So if we don't use Swipe, and definitely don't want to remove credit card validation, we don't need to install the patch to use the extension version 1.3.10 on Civi 4.4.10. Is that right?

**Comment by KarinG** [comment]
Hi Joe - I was referring to the ad 2) portion of the patch - the one re: credit card validation - you don't need that if you don't use SWIPE. However the  ad 1) portion affects direct debit -> ACH/EFT -> so you want that (as Alan outline above). Hope that clarifies,

**Comment by eileenmcnaughton** [comment]
Alan - since you said the patch belongs in core for number 1 I've added a ticket - https://issues.civicrm.org/jira/browse/CRM-16045 - can you check it.

I'm still not 100% sure the patch is going to always be OK (but I will patch Fuzion repo with it as it will always be OK for our customers - who don't use other EFT solutions at this stage)

**Comment by joemcl** [comment]
Karin, thanks for clarifying. Karin, Eileen, Alan - thanks! With Eileen's patch to the Fuzion repo, moving ahead now with live test for ACH/EFT.
