### ISSUE TITLE
How to enter an ACH/EFT as a New Contribution directly in Civi?

### ISSUE THREAD

**Issue by joemcl** [iATSPayments/com.iatspayments.civicrm#67]
Alan, Karin - I'm unclear on how to enter a new ACH/EFT as a New Contribution directly in Civi (or an existing ACH/EFT monthly contribution that we want to start using Civi and iATS for) via 
https://[a Civi page]/civicrm/contribute/add?reset=1&action=add&context=standalone 
for example. 

From that page, I can submit a new credit card contribution - but don't see a link for a new ACH/EFT contribution. 

We're just setting up to use iATS for ACH/EFT, testing that, still using Authorize for credit/debit cards while we test iATS and figure out how to transition from Authorize to iATS for credit/debit card contributions/monthly sustainers. 

Thanks. 

UPDATE: To be clearer, I hope, I want to enter a new ACH/EFT similar to a new credit/debit card for starting a monthly sustaining contribution via ACH/EFT, as at this page - https://[A Civi installation.org]/civicrm/contact/view/contribution?reset=1&action=add&cid=123456&context=contribution&mode=live

**Comment by adixon** [comment]
The issue is that civicrm core does not support backend ACH/EFT. My work around is: create a front end contribution page that has ACH/EFT as it's only payment processor - a contact's contribution tab will now include a link to it (auto-linking that contact). You'll see a little note to this effect in the readme.

**Comment by joemcl** [comment]
OK seeing this note (probably again) " 'Backend' ACH/EFT is not supported by CiviCRM core. Having an enabled ACH/EFT payment processor broke the backend live credit card payment page in core (until it was fixed here https://issues.civicrm.org/jira/browse/CRM-14442), so this module fixes that if it's an issue, and also provides links to easily allow administrators to input ACH/EFT on behalf of constituents. A similar problem existings for backend membership and event payments, and this has not been fixed in core."

So any movement on getting backend ACH/EFT into core? Was this one of the issues that you and Eileen addressed for 4.6?

**Comment by adixon** [comment]
No progress, no. It's a kind of messy issue really.
