### ISSUE TITLE
Completed iATS ACH/EFT transaction still shows as Pending (Pay Later) in Civi Contributions

### ISSUE THREAD

**Issue by joemcl** [iATSPayments/com.iatspayments.civicrm#71]
So I set up a test contribution page for ACH/EFT contributions in Civi. I started a $1 daily recurring contribution yesterday. The transaction was processed overnight successfully by iATS - I see a OK:BankAccept in the Journal entry for that first $1 transaction in my iATS account page. 

This morning between 6am and 7am, the hourly Scheduled Job  "iATS Payments Verification (Hourly)" ran successfully. I also re-ran the hourly Scheduled Job this afternoon, same result in the log. The log entry from this morning is below:

Parameters parsed (and passed to API method): 
a:1:{s:7:"version";i:3;}
Full message: 
Finished execution of iATS Payments Verification with result: Success (Completed with 0 errors.
Processed 0 approvals from today, 1 approval and 0 rejection records from the previous 30 days.
)

However, in the CiviCRM Contribution record, the transaction still shows as Pending (Pay Later) when it should appear as Completed. I haven't yet gone into the back end MySQL tables to see what additional info appears in the iATS transaction table for the transaction. 

We're on Civi 4.4.13 and hoping to move soon to 4.5.9/4.6 . Testing out 4.6 on our staging site in the next couple of days. But I want to get iATS processing working successfully on Civi 4.4.13 as soon as possible.

**Comment by KarinG** [comment]
Hi Joe - run the approval job tomorrow: iATS pushes approved/rejected ACH in a box journal overnight. We pull that into CiviCRM to update pending transactions accordingly. So today's box journal includes transactions that were approved up to and including yesterday. Your transaction from yesterday; was approved today; will be in the box journal (and thus visible to CiviCRM) tomorrow.

**Comment by joemcl** [comment]
Karin, thanks, but I'm a little confused. The Scheduled Job "iATS Payments Verification (Hourly)" runs hourly. The log from the job running this morning shows as:
"Parameters parsed (and passed to API method): a:1:{s:7:"version";i:3;}
Full message: Finished execution of iATS Payments Verification with result: Success (Completed with 0 errors.Processed 0 approvals from today, 1 approval and 0 rejection records from the previous 30 days.)"
That 1 approval from the previous 30 days is my first transaction. Why should there be a one-day delay in that approval appearing in Civi as a Completed transaction? Civi has received all the info it needs back from iATS.

**Comment by KarinG** [comment]
Sorry - read over the 1 earlier (thought you were reporting all zeros - and were wondering about the delay between seeing the approval in iATS and in CiviCRM. Will check in later.

**Comment by KarinG** [comment]
So what this tell us is that is processed the approval but it couldn't find the [matching] transaction to update the status. You're saying the status = Pending (Pay Later)? The ACH/EFT verify job will examine and match up contributions with status = Pending (Incomplete Transaction). How did you initiate the ACH/EFT transaction? What is the URL to your test page contribution page?

**Comment by KarinG** [comment]
a) Though all Pending status-es should work - I'm curious how you got to status = Pending (Pay Later). 
b) Note the job is also not verifying CiviCRM Tests - as you can simply run a test using TEST88 as agent code for a real live test environment. 

$select = 'SELECT id, trxn_id, invoice_id, contact_id, contribution_recur_id
FROM civicrm_contribution
WHERE
contribution_status_id = 2
AND payment_instrument_id = 2
AND receive_date > %1
AND is_test = 0';

**Comment by joemcl** [comment]
Here's the link to the live page that I'm using to test live transactions - 
https://my.citizenactionny.org/civicrm/contribute/transact?reset=1&id=17 

I'll check the form settings re status update settings.

**Comment by joemcl** [comment]
There is a check box to allow a Pay later option under Amounts in the CiviCRM contribution page set up, but I haven't checked that box. 
I'm getting an error on the live page about a missing required field that has not been filled in, but that isn't the case. 
Also, at the bottom of the page, a message appears about "Input error: k: Format of site key was invalid" which seems to have to do with a missing Captcha, but there is no Captcha set up option in CiviCRM contribution pages.

**Comment by KarinG** [comment]
I just verified that ACH/EFT verify script is working for 4.4.13 - one that I had in Pending status - just completed. 

If you submitted a new ACH/EFT just now [or ran your recurring scheduled job] -> iATS will send that to the Bank @3pm PT tomorrow [then it goes from Tobesent to Pending in iATSPayments.com]. It's possible it will get a OK:BankAccept or OK:BankReject later tomorrow afternoon - but it's also quite possible it will take till Monday. It will definitively take until Monday to be updated in the Box Journal - so run ACH/EFT verify scheduled job on Monday. If things don't verify then we can dig in further.

**Comment by joemcl** [comment]
OK, Karin, so here's an update. 

I had run the Scheduled Job iATS Payments Recurring Contributions (Daily) at 1:51pm today. The second $1 contribution that was Pending: Incomplete Transaction referenced in the earlier comment was processed successfully by iATS (OK:BankAccept) at 2:54PM (which I think means 5:54PM Eastern time, as iATS is in Vancouver and on Pacific time). At 7:42PM my time, the Scheduled Job 
iATS Payments Verification (Hourly) ran and the following appears in the log:
Parameters parsed (and passed to API method): 
a:1:{s:7:"version";i:3;}
Full message: 
Finished execution of iATS Payments Verification with result: Success (Completed with 0 errors.
Processed 1 approvals from today, 1 approval and 0 rejection records from the previous 30 days.
For 1 pending ACH/EFT contributions, 0 non-recuring and 1 recurring contribution results applied.
Verified iATS Payments ACH/EFT contribution id [XXXXX, not the actual value]  for contact id [XXXXX , my ID])

That second contribution now shows in Civi as Completed, the correct status. 

So there might just be an issue with the first transaction in a recurring series getting stuck as a Pending (Pay Later). I went in and changed that first contribution status to Completed from Pending (Pay Later) after writing my previous comment. 

I also tweaked the live test form ( at https://my.citizenactionny.org/civicrm/contribute/transact?reset=1&id=17 ) to make it an explicit Membership sign up form and used another Profile. With those changes the error about a missing required field and "Input error: k: Format of site key was invalid" did not reappear.

**Comment by KarinG** [comment]
Excellent - you've got your first one verified: if a transaction date is today + if it is approved today -> then it will appear in the 1 approvals from today (that's the day journal we're retrieving). 

I'm puzzled how you ended up with Pending (Pay Later) - status of ACH/EFT Recurring contributions (even the first in a series) immediately upon submission to iATS are Pending (Incomplete) in CiviCRM. With a Pending (Pay Later) -> there likely is no transaction ID, right? Transaction ID is key in matching the approved contribution from iATS. Looks like there is some old logic from other payment processors interfering here. Many do go to Pay Later - not getting a transaction ID right away. 

reCaptchas in CiviCRM are by profile (look in a profile's advanced settings). So you likely swapped to a profile that didn't have a recaptcha configured

**Comment by KarinG** [comment]
PS - on Membership and recurring -> please see: https://issues.civicrm.org/jira/browse/CRM-16044 - This was observed in credit card payments: "initial payment gets created as pending even if it was successful and the membership is also pending". iATS e.g. returns the contribution status id - but other old logic in core appears to be overriding this - in the specific case of Membership + Recurring.

**Comment by KarinG** [comment]
This com.iatspayments.civicrm transaction currently supports 20 different types of transactions in CiviCRM + 1 additional one in beta status (UK Direct Debit). In the wiki you can see a summary/overview:
https://github.com/iATSPayments/com.iatspayments.civicrm/wiki/Documentation [note that Membership + Recurring is not in there yet - I will include it once issues like CRM-16044 get fixed].

**Comment by joemcl** [comment]
Karin, thanks. Recurring memberships via ACH/EFT using iATS is the reason we signed up for iATS in the first place. This is aggravating. Do you think you, Alan, Eileen could help Lola fix the issue ID'd in https://issues.civicrm.org/jira/browse/CRM-16044 ? So we can then get monthly recurring memberships via ACH/EFT working with the iATS extension?

**Comment by KarinG** [comment]
To be honest - I think it's time to stop (small) patching CiviCRM core - and look at the bigger picture: it's time for a larger refactoring. It's not the iATS extension that doesn't allow recurring membership payments. iATS just transacts the monies - it doesn't care if these monies are for a Contribution or a Membership or a Donation. That 'consequences' logic should all live and be handled in CiviCRM core.

Try to get your initial membership recurring contributions working by filling in the bits that don't get passed on into the contribution record - yourself: e.g. look up the transaction ID in iATSpayments.com -> and add :unixtimestamp [look at the transaction id of the ACH/EFT that did validate to see what that looks like]. Then run the verify script again and see if it can then match (and thus complete) your transaction. Let me know - you may need to fill in more bits. 

Depending on the size of your project the above may work to get that initial one going (the recurring ones as you've seen are fine - as the extension [not core] is generating those contribution records). If you have a larger project - then you may need a more automated solution: in one of my projects we recalculate end date ourselves in code based on last date of contribution (recurring or not). That's because end date must be +1y from last contribution date [which is different] - but it also effectively bypasses any issues that currently exist. 

I hope this helps - a bit.

**Comment by joemcl** [comment]
Karin, thanks, and I will try that. That's similar to a fix for the same/similar issue with monthly recurring credit/debit card contributions using Authorize getting stuck. The manual fix and rerunning is a major time suck when you have hundreds of monthly recurrings as we do, many of which we need to re-do often when cards change, new cards get issued because of bank hacks, etc. Not nearly as much of an issue when using ACH/EFT, because bank accounts change much less often than credit/debit card numbers, but still a pain in the butt.  

I hope that Eileen and Alan made some progress towards fixes for recurrings - whether by ACH/EFT or credit/debit cards, or through Authorize or iATS  or whatever payment processor - in Civi 4.6.    

Is Alan going to engage on this issue thread?

**Comment by joemcl** [comment]
So all of my recurring iATS ACH/EFT contributions - $1 a day for two series - finally show as Completed in Civi, on the production site using 4.4.13. What's annoying is that the four from Saturday and Sunday each completed on the correct day, and show in iATS as such, but did not appear as Completed in Civi until today, probably based on the overnight run. For the first series, starting March 11, I had to go and manually mark the first as Completed, which it was in iATS, but showing as Pending (Pay Later) in Civi. I did not do that for the second series that started on March 12.

Eileen, you asked - "does IATS use IPNs / postbacks to notify the outcome?" I have no idea yet, will put that to Alan/Karin.

**Comment by KarinG** [comment]
In ACH/EFT - there are many dates: the date the transaction is submitted; the date the transaction is sent to the bank; the date the transaction is approved; the date the transaction gets into the iATS box journals [could be the same as transaction date - but not necessarily so] - so there is no 'correct' date - and yes that's perhaps annoying - but ACH/EFT by nature takes days if you're expecting a live sync at all times - you will be disappointed. Again, ACH/EFT recurring contributions work well with the iATS extension - I just re-verified this in 4.4.13 - The issue with the status is of the initiating contribution is a CiviCRM membership issue (which belongs in JIRA) - not an iATS one - closing this one.

**Comment by joemcl** [comment]
Karin, thanks so much for the info.
