### ISSUE TITLE
ACH Payment 

### ISSUE THREAD

**Issue by globeseek** [iATSPayments/com.iatspayments.civicrm#75]
Maybe I am missing something - 
ACH Seems to be working in submission -  The contribution is put in pending awaiting the approval - when I go look at the two IATS cron job - this is what I get --  Summary
Finished execution of iATS Payments Verification with result: Failure, Error message: API (Job, IatsACHEFTVerify) does not exist (join the API team and implement it!)

How does the ACH contribution status ever go from Pending to completed if I need to join the API team to get it done ? 

Thanks

**Comment by adixon** [comment]
Yeah, that looks borked. What version of civicrm are you using?

**Comment by globeseek** [comment]
civi 4.4.14

**Comment by globeseek** [comment]
Any Idea ... otherwise this is not a really viable payment option

**Comment by KarinG** [comment]
I just ran a complete 4.4.14 and 4.5.8 test grid - and the ACH verify job worked well for all ACH contributions. I believe you're on Joomla - if I'm not mistaken? Could the this be an issue with scheduled jobs on joomla?

**Comment by globeseek** [comment]
It could be but all other jobs that I am running like email and bounce processing work fine

-----
Josh
Sent from my phone

----- Reply message -----

**Comment by adixon** [comment]
You could try forum.civicrm.org, it's an issue with your setup, not with the iATS extension.

The key is this message:

"Finished execution of iATS Payments Verification with result: Failure, Error message: API (Job, IatsACHEFTVerify) does not exist (join the API team and implement it!)"

In other words: your civicrm has paid attention to the extension's inclusion of the job as an option, but has lost knowledge of the job itself, which is in a file in the same directory. That's not the fault of the extension ...

You could try just clearing your caches, but it also might be something related to the api and joomla that I don't understand. My guess is that whatever is causing this would cause issues with other extensions as well.

**Comment by globeseek** [comment]
As it turned out clearing the cash was the magic bullet .. thanks..
Alan Dixon <mailto:notifications@github.com>

**Comment by adixon** [comment]
Great. I wish I could clear some cash as well.
