### ISSUE TITLE
Allow management of recurring donations?

### ISSUE THREAD

**Issue by mattbaylor** [iATSPayments/com.iatspayments.civicrm#76]
I haven't found any documentation on how to enable people who have established a recurring donation to be able to change, or delete that recurring donation. Did I miss it somewhere?

**Comment by adixon** [comment]
Yeah, that's a good question. I think the standard messages in civicrm suggest that such a thing is enabled by default, so in theory that functionality is provided by civicrm core. The extension does implement a method that tells civicrm that recurring contributions can be modified within civicrm (i.e. the cancelSubscription and changeSubscriptionAmount), so assuming core provides the support, it should be possible. Here are the relevant issues:

https://issues.civicrm.org/jira/browse/CRM-10076
https://issues.civicrm.org/jira/browse/CRM-10089

I suspect that they just need better documentation.

**Comment by KarinG** [comment]
Hi Matt - you can currently do a little bit of this with CiviCRM core:
In a Contact Summary -> hit Contributions tab -> scroll down to Recurring Contributions [could be quite a ways down] -> hit Edit on any of them and you'll see: 

![recur](https://cloud.githubusercontent.com/assets/5340555/6931460/b1c75dbe-d7ca-11e4-9152-d63c886d5244.png)

Direct URL is something like:
/civicrm/contribute/updaterecur?reset=1&action=update&crid=76&cid=2&context=contribution

**Comment by lolas-freeform** [comment]
Note that this is currently not allowed for recurring contributions related to memberships.
This is probably to simplify because the logic would have to be different for memberships
