### ISSUE TITLE
iats.php doesn't test whether  send_cancel_request element exists before attempting to remove it

### ISSUE THREAD

**Issue by lolas-freeform** [iATSPayments/com.iatspayments.civicrm#77]
On one install I have a situation in which the "send_cancel_request' checkbox doesn't exist before iats.php attempts to remove it in buildForm. This results in a fatal error.

I believe in this case it is due to a customer setup error or mixup after changing/disabling payment processors. However this could also happen due to another extension modifying the form.

I suggest replacing:
```
    function iats_civicrm_buildForm_CRM_Contribute_Form_CancelSubscription(&$form) {
       $form->removeElement('send_cancel_request');
    }
```
with
```
    function iats_civicrm_buildForm_CRM_Contribute_Form_CancelSubscription(&$form) {
      if ($form->elementExists('send_cancel_request')) {
        $form->removeElement('send_cancel_request');
      }
    }
```

**Comment by adixon** [comment]
Thanks, done.
https://github.com/iATSPayments/com.iatspayments.civicrm/commit/348d5d65158f705cc7904a835048342ebc5c9c8e
