### ISSUE TITLE
Emails not being delivered for recurring transactions

### ISSUE THREAD

**Issue by mattbaylor** [iATSPayments/com.iatspayments.civicrm#79]
Any idea where I could start looking to diagnose why email confirmations of the recurring transactions aren't being sent? Emails for one time are being sent exactly as expected.

**Comment by adixon** [comment]
That's not part of the functionality of this extension, for sure. I'd guess you have a similar issue for other mass/automated mail? Recurring transactions don't automatically get notified as far as I know.

**Comment by mattbaylor** [comment]
Sorry for the delayed response on this, but I have a hunch. First of all, Core Civi has all kinds of notifications of email receipts being delivered when a recurring donation is processed, so I know the core has that functionality. 

As to my hunch, I'm thinking that something, somewhere might be erroring out preventing the completion of all of the code for processing the recurring donation. I know that the recurring donation is being processed (the money is leaving my credit card account...) and is showing in Civi. Could you point me to the exit processing of the iATS processing so that I can embed some logging in the process and see if I can catch it failing? Thanks for any pointers you might have!

**Comment by adixon** [comment]
The recurring donation notifications that you've seen would be perhaps in the IPN callback? The recurring contributions for iATS are being created by a job, so it's in api/v3/Job/ of the extension.

You could relatively easily build your own notifications with rules and eileens civi-rules integration, if you're using Drupal.

**Comment by lolas-freeform** [comment]
@mattbaylor I am not sure if you are using memberships on those donation pages but if you are there are open issues for CiviCRM leaving payments pending and not sending receipts. https://issues.civicrm.org/jira/browse/CRM-16169 and https://issues.civicrm.org/jira/browse/CRM-16044

**Comment by mattbaylor** [comment]
@lolas-freeform Thank you for replying, but no we are not using Memberships, these are pure donations. I think @adixon hit the nail on the head (after pouring through the code last night) the IPN callback kicks off the receipting process. iATS has no IPN callback functionality (and it's not needed to complete the donation). I'm looking into writing a monitor job on the iats_response_log table to look for completed recurring donations and then kick the receipting process off from that.

**Comment by mattbaylor** [comment]
Sorry to keep beating a dead horse, but after what I believe to be a thorough examination of iATS payment processor code, Authorize.net processor code and PayPal processor code I can confirm that the IPN does indeed trigger the recurring notifications. The function called to send recurring notification is CRM_Contribute_BAO_ContributionPage::recurringNotify.

Since iATS does not use the IPN, no recurring notifications are being sent. Every other payment processor supports the recurring notifications through their customized IPN handler. The IPN handlers all do significantly more than just send recurring notifications. Most of that functionality for the iATS payment processor has been handled in the actual iATSService. It seems to make sense that the recurring payments job would also trigger the recurring notifications since there is no IPN to trigger it.

So I'm now thinking that the best way to solve this problem would be to modify the IatsRecurringContributions job (api/v3/job/IatsRecurringContributions.php) around line 272 to both instantiate CRM_Contribute_BAO_ContributionPage and call recurringNotify with the proper parameters:
$type = civicrm_financial_type
$contactID = civicrm_contact
$pageID = none
$recur = civicrm_contribution_recur
$autoRenewMembership = FALSE

Does this line of thinking make sense? Amy I missing something? Thanks in advance!

**Comment by adixon** [comment]
Thanks for digging here. There's a separate dangling issue for the iats job to call the new api version of the ipn handler, to manage the creation of proper accounting (which now makes more sense to me, since for old-style recurring contributions, it's only the IPN which confirms a contribution).

Now that I can see how the IPN isn't just an extra complication for old-style recurring payment processing, I think I'm ready to pay more attention to that issue.

If you're ambitious check it out here:

https://github.com/iATSPayments/com.iatspayments.civicrm/issues/65
