### ISSUE TITLE
Update associated memberships + event registrations until Order API is out (4.7)

### ISSUE THREAD

**Issue by KarinG** [iATSPayments/com.iatspayments.civicrm#82]
in iATSACHEFTVerify.php after:
            $result = civicrm_api('contribution', 'create', $contribution);

**Comment by KarinG** [comment]
Eileen will verify this: membership - ACH/EFT - recurring - when status updated to pending - verify that the membership gets extended. If not update ourselves - for 4.6

**Comment by adixon** [comment]
This was done in the 1.4.x series, using the completetransaction function of the contribution api.
