### ISSUE TITLE
Confirm page - ACH/EFT transaction - reference to Credit Card

### ISSUE THREAD

**Issue by KarinG** [iATSPayments/com.iatspayments.civicrm#83]
![unnamed](https://cloud.githubusercontent.com/assets/5340555/7381923/2379fdca-edc6-11e4-8a37-4cd9e1f2a38c.png)

**Comment by adixon** [comment]
If this is still an issue, we should move it to CiviCRM core.

**Comment by KarinG** [comment]
Yes - is still an issue - will move it to JIRA.

**Comment by KarinG** [comment]
https://issues.civicrm.org/jira/browse/CRM-19032 - started work on this
