### ISSUE TITLE
back-office paid participant registration form is broken with this extension

### ISSUE THREAD

**Issue by sgladstone** [iATSPayments/com.iatspayments.civicrm#84]
When attempting to register someone for a paid event in the back office, the form does not allow for payment by credit card. To reproduce the issue:

1) Click "Create New ... Event Registration (Credit Card)

2) In the list of events, choose a paid event.

3) Fill in pricing choices ( such as Adult meal = $50 ) that are listed for this event. 

There are NO credit card fields for filling in credit card number, expiration date, and CVV. (Instead I see a section heading labeled "Direct Debit Information"  but it only contains fields for billing name and billing address.

Version info:
CiviCRM 4.4.7
iATS extension 1.3.2
core Authorize.net payment processor is configured (and is set as the default payment processor) 

The only other payment processor type  that is configured is the iATS ACH/DirectDebit processor. (In this situation, iATS is only used for ACH)

This issue is impacting all paid events. There is no way for a back-office user to register a participant for any paid event.

**Comment by adixon** [comment]
Yes, you need the core patch that removes direct debit payment processors from the allowed options.
In this file:
CRM/Event/Form/Participant.php
change:
-      $processors = CRM_Core_PseudoConstant::paymentProcessor(FALSE, FALSE, "billing_mode IN ( 1, 3 )");
+      $processors = CRM_Core_PseudoConstant::paymentProcessor(FALSE, FALSE, "billing_mode IN ( 1, 3 ) AND payment_type = 1");

It's in the patch file of the iats extension iATS_4.4.14.diff

Not specific to iATS, this is a core bug related to any non-credit card payment processors (that have different billing fields).

**Comment by KarinG** [comment]
Confirming that non-iATS processors play nicely with others in 4.4.14 - w/ iATS diff patch:

![iats_event_backend](https://cloud.githubusercontent.com/assets/5340555/7398745/31e1372c-ee6e-11e4-87b7-5c7d23c0ed4b.png)

**Comment by sgladstone** [comment]
In what version of CiviCRM core will that patch be included?

**Comment by KarinG** [comment]
Kurund and I worked through 1.3.2 with the 4.6.x branch yesterday and everything is in [passed all tests].

**Comment by sgladstone** [comment]
I had the same issue in the back office with "Create New ... Membership (Credit Card)".   To solve that, I changed the CiviCRM core file "sites/all/modules/civicrm/CRM/Member/Form/Membership.php"

I changed the line 
* $processors = CRM_Core_PseudoConstant::paymentProcessor(FALSE, FALSE, 'billing_mode IN ( 1, 3 )  ');

TO:

* $processors = CRM_Core_PseudoConstant::paymentProcessor(FALSE, FALSE, 'billing_mode IN ( 1, 3 ) AND payment_type = 1 ');

**Comment by adixon** [comment]
Yes, that's in the same iATS patch.
