### ISSUE TITLE
Strict warning singleton() compatibility

### ISSUE THREAD

**Issue by ttrezren** [iATSPayments/com.iatspayments.civicrm#85]
On fresh install of drupal 7.37 and civicrm 4.6.3, after migrating civicrm data and upgrading iatspayments to 1.3.2 I'm getting this warning:

Strict warning: Declaration of CRM_Core_Payment_iATSService::singleton() should be compatible with & CRM_Core_Payment::singleton($mode, &$paymentProcessor, &$paymentForm = NULL, $force = false) in Civi\Payment\System::getByProcessor() (line 52 of /home/user/public_html/sites/all/modules/civicrm/Civi/Payment/System.php).

**Comment by adixon** [comment]
Thanks, this is already fixed, will be included in the next release.
