### ISSUE TITLE
Scheduled jobs failed

### ISSUE THREAD

**Issue by eidoander** [iATSPayments/com.iatspayments.civicrm#86]
Help! I am getting this:
Parameters parsed (and passed to API method): 
a:1:{s:7:"version";i:3;}

Full message: 
Finished execution of iATS Payments Recurring Contributions with result: Failure, Error message: API (Job, iatsrecurringcontributions) does not exist (join the API team and implement it!)

I am on the latest version of civicrm (4.6.3) and the latest iats extension on Drupal 7. I get this message for both the iatsrecurringcontributions and the payments verifications cron jobs. Any thoughts?

Is it a problem with the parameters?

**Comment by adixon** [comment]
Sounds like your extensions configuration is bad. It's not a parameters problem, it's just not finding the extension code that defines the job itself.

**Comment by eidoander** [comment]
can I give you a screen shot of my directories and resource urls? Would you do a quick inspect? Don't understand how the paths could have gotten screwed up. all the extensions seem to be in the right place and the directores and urls configured properly in the admin for civicrm.

**Comment by adixon** [comment]
Sure post away ... I'm assuming none of your other extensions are working either?

**Comment by eidoander** [comment]
No! They are working! Even iatspayments is working EXCEPT for recurring payments because that are not triggered by the cron job. One-time payments are working!

History: We upgraded to 4.6.3 first week of May and that seems to be when the failures started occurring. I noticed that there was an upgrade for iats so I tried to upgrade through the extensions manager. Got a failure that said something was wrong with directories and couldn't upgrade. So I manually installed 1.3.2 into extensions, unzipped, ran the db update. It now shows I am running 1.3.2 in the extensions manager, but still no recurring. So that's when I looked at the cron jobs and discovered that they were failing with error message above in my initial post.

Thoughts? I know that the directory structure and the configuration for extensions was correct in the past, and still is. But I agree, there must be some reason why the new install of the extension is not able to find the cron jobs.

**Comment by eidoander** [comment]
When I try to upgrade the extensions through the Extension Manager in Civicrm admin I get this: 

[WARNING: The downloader may be unable to download files which require HTTP redirection. This may be a configuration issue with PHP's open_basedir or safe_mode.]

and this:

[Extension Upgrade Failed
Download failed - ZIP file is unavailable or malformed]

**Comment by adixon** [comment]
Ahhh, so i guess open_basedir or safe_mode is preventing access to the job.

You're right that if it works for one-time contributions, it's not your directories/paths that are messed up, it's because the php running the cron is different from the regular web php and has different file path restrictions. There's probably an exception you need to put in somewhere to allow cli php to look in your extensions folder, wherever that is.

**Comment by eidoander** [comment]
" There's probably an exception you need to put in somewhere to allow cli php to look in your extensions folder, wherever that is."

I know where my extensions are, but where are the php files you mention ("regular web php" and the "php running the cron"). What would their names be? I'm afraid I don't know where to start looking.

**Comment by adixon** [comment]
You might need to talk to your system administrator, it depends on the distro (assuming this is a linux flavour) and in any case I avoid open_basedir and safe_mode, so I don't really know how they are configured. You can start with php.ini, but it might be in a php.d directory, and there should be different ones for the cli vs. the web version. cli is the command-line-interface version of php that's running, and can be given different .ini parameters. I'm assuming you're running your civi cron that way ...

**Comment by eidoander** [comment]
K. thx. I'll check with Hershel at CiviHost. I appreciate your help!

**Comment by eidoander** [comment]
Hey Alan, still haven't fixed this issue. The open_basedir and safe_mode are set properly, undefined and off.

Can you think of any reason why the scheduled job would not be found when cron is executed? Up until this past month everything was working properly (civicrm 4.5.6 and iatspayments-1.2.11). When I upgraged to Civicrm 4.6.2, the scheduled jobs failed.

Right now, I am running iatspayments-1.3.2 on Drupal 7 with civicrm 4.6.3. I manually installed the IATS upgrade (the directory name is "com.iatspayments.civicrm" no version number; I had to change it from "com.iatspayments.civicrm-1.3.2" which is how it unpacked, so I just renamed it). The two scheduled jobs simply won't fire. The error message says they don't exist. My directories are configured properly and the settings seem to work except for these two scheduled jobs.

Any thoughts would be greatly appreciated. We are losing buckets of money each month from recurring payments (we really rely on this at my organization).

Thanks!

**Comment by adixon** [comment]
What are you using to fire your scheduled jobs? Drush?

**Comment by eidoander** [comment]
Nope. Just using the "Execute Now" link in the Scheduled Jobs admin (system settings=>scheduled jobs=>more=>execute now). I've never used Drush.

**Comment by adixon** [comment]
So you're manually triggering all your scheduled jobs?

**Comment by eidoander** [comment]
Okay. No. Sorry. I just meant that when I want to test the iatspayments jobs I manually trigger using Execute Now.

Generally, jobs are triggered by the cron.php file in the root directory of the D7 installation. It is supposed to handle incoming requests to fire. I think it's working because other jobs fire according to schedule. In fact, up until mid last month my iats jobs seemed to fire properly. Here is the message from the log last time it fired and actually processed some records:

0
Summary
Finished execution of Call Job.IatsRecurringContributions API with result: Failure, Error message: Completed, but with 1 errors. 1 records processed.
Details

Parameters parsed (and passed to API method): 
a:1:{s:7:"version";i:3;}

Full message: 
Finished execution of Call Job.IatsRecurringContributions API with result: Failure, Error message: Completed, but with 1 errors. 1 records processed.



That was May 13. After that, the next time it fired, May 14, I got this:


Entity: Job Action: IatsRecurringContributions
Summary
Finished execution of Call Job.IatsRecurringContributions API with result: Failure, Error message: API (Job, iatsrecurringcontributions) does not exist (join the API team and implement it!)
Details

Parameters parsed (and passed to API method): 
a:1:{s:7:"version";i:3;}

Full message: 
Finished execution of Call Job.IatsRecurringContributions API with result: Failure, Error message: API (Job, iatsrecurringcontributions) does not exist (join the API team and implement it!)


And it has failed with the "does not exist" message ever since.

**Comment by eidoander** [comment]
So now I'm confused. (I don't know much about this stuff) Anyway, there is another cron file "civicron.sh" in a private directory outside the web root. And another one at /sites/all/modules/civicrm/bin/cron.php

I don't really know what is triggering the scheduled jobs. I always thought it was the one in the D7 root.

**Comment by eidoander** [comment]
Here is discussion about my issue over at Stack Exchange:
http://civicrm.stackexchange.com/questions/3070/extension-manager-fails-and-so-do-certain-scheduled-jobs?noredirect=1#comment2115_3070

should I install the master?

**Comment by eidoander** [comment]
Tim Otten is right. Two issues. I have a workaround for the Extensions Manager issue, but I must find a solution to the IATS problem. I'm stuck. I have over 100 people who are currently doing scheduled payments to my organization. I have already lost a month of contributions.

How about just installing the scheduled jobs from the master? Would that help?

**Comment by KarinG** [comment]
Ok - I'll add-on to SE.

**Comment by KarinG** [comment]
But quickly: do not upgrade to master

**Comment by eidoander** [comment]
K. No problem.

**Comment by adixon** [comment]
I just tested the recurring payment scheduled job on D6/4.6.2 and get the same error, so clearly we didn't get far enough in our 4.6 testing, i.e. we're not ready for 4.6. I'll see if I can roll you a patch to keep you going in the interim.

**Comment by eidoander** [comment]
Wow. That would be a lifesaver if you could get a quick patch to fix!

**Comment by KarinG** [comment]
See SE

**Comment by adixon** [comment]
I believe this is resolved here:
http://civicrm.stackexchange.com/a/3117/233
