### ISSUE TITLE
Contributions not created/updated in Civi 4.6.6/iATS 1.4

### ISSUE THREAD

**Issue by fulltrucker** [iATSPayments/com.iatspayments.civicrm#87]
We use the iATS payments extension, and we just upgraded Civi to 4.6.6 and the extension to 1.4. We also switched all contribution pages that were previously using the core iATS payment processor to use the extension, although there weren't many of them. We experienced an issue where all CC transactions were successfully processed by iATS, but are not being added to Civi after they're approved. The error we see on the page is:

Failed to update contribution in database

Reverting/reinstalling iATS Payments 1.3.2 has cleared up this issue for us. Additional info: this was all in the front end. Staff was still able to take credit card contributions in the back office of Civi with no issues—iATS processed cards fine and contributions were created as expected.

I have also brought this to the attention of our primary Civi dev partner, in case the issue is not with Civi/iATS Payments but with a conflict of another extension we are using.

**Comment by fulltrucker** [comment]
Additional info: this was all in the front end. Staff was still able to take credit card contributions in the back office of Civi with no issues—iATS processed cards fine and contributions were created as expected.

**Comment by eileenmcnaughton** [comment]
Karin, Alan, I'm taking a look at this now - I'm guessing the contributions are being double-completed. This is on membership contribution pages

**Comment by KarinG** [comment]
We think this may be related to some mix up in patches on this specific repo - won't affect core CiviCRM.
