### ISSUE TITLE
Bank routing number field not appearing on public page

### ISSUE THREAD

**Issue by joemcl** [iATSPayments/com.iatspayments.civicrm#90]
The bank routing number field for EFTs does not appear on a public page we have created using the iATS template. The issue appears to be line 16  -      $('.bank_identification_number-section').hide(); - 
in  ~/extensions/com.iatspayments.civicrm/js/dd_acheft.js . We've removed it from our  local repo and that seemed to do the trick. Will do a proper PR later tonight if I have time.

**Comment by adixon** [comment]
Sorry about that - that's CAD-currency-only functionality, shouldn't be in that js as you note. I've moved it where it belongs, not to worry about a PR.

But, glad to see you testing it for US acounts. The latest version that'll come out after some more QA next week will include some extra code to remove non-numeric stuff from those account fields.

**Comment by joemcl** [comment]
Alan, thanks so much. Canadian banks don't use routing numbers?

**Comment by mikekim85** [comment]
Canadian banks don't use routing numbers. They use bank, transit, and account numbers.

**Comment by adixon** [comment]
They do, but the interface hides that field and provides a bank number and transit number which are glued together to generate the bank routing number in the background.

**Comment by joemcl** [comment]
OK. So the next version of the extension (out next week?) will have fields on the form for bank name, routing number and account number for a US version? Bank number, transit number and account number fields for the Canadian version?

**Comment by adixon** [comment]
The cdn version is actually working in the existing 1.4.0, but we've added some extra validation and auto-fill features in the new version (1.4.1) coming out next week. If you want to pull it from master here on git and run your own tests, you're welcome to do that, it should be 

The only change to the us version is the fix you've noted, we're no longer hiding the 'routing' number (internally, it's called the 'bank information number').

The bank name and account number are common to both forms.
