### ISSUE TITLE
Recurring Emails Still Not Sending 

### ISSUE THREAD

**Issue by stevekessler** [iATSPayments/com.iatspayments.civicrm#91]
We have installed the 1.4.1 extension  and 4.6.8. We are still not getting the email from the iATS system when a new recurring contribution is created.  We have tested this several times and made sure that we have checked the check box on the new admin screen (admin/contribute/iatssettings).

Thanks,
Steve

**Comment by KarinG** [comment]
There is the 
1) email notification for initiating a recurring contribution (logic for this is embedded in CiviCRM core). 
2) email notification when the iATS extension recurring contributions job creates a subsequent recurring contributions (logic for this is embedded in the extension - that is now handled with a switch on the iatssettings page). 

I suspect your case is 1)? And what type of payment?

**Comment by fulltrucker** [comment]
I am doing quite a bit of testing on this extension right now as well, so I'll be chiming in where appropriate. I just tested the email functionality on recurring payments, and it worked as expected for me. I have the box checked at the page admin/contribute/iatssettings and recieved an email for both the intial contribution and the first of the recurring contributions.

My question is why is the enable email receipting for recurring contribution checkbox on a different screen than the rest of the admin functionality? Shouldn't the following two pages just be on one?

civicrm/admin/contribute/iatssettings
civicrm/iATSAdmin

Please excuse if I should make this comment / suggestion somewhere else.

**Comment by KarinG** [comment]
Hi Evan - thanks for testing/verifying this - appreciated. We are slowly moving iATSAdmin into reports (it's more of a log). Have you looked at the new reporting yet -> for recurring contributions: 
civicrm/report/com.iatspayments.com/recur?reset=1 [under create report from templates]
Give it a try and let me know if you think it's useful. I have a few more updates to do on it. 
Settings really belong in admin/contribute - so that will stay there.

**Comment by KarinG** [comment]
I'll close this issue - as we've had confirmation the email recurring switch is working. Open a new issue for the report if you have any feedback for me.

**Comment by adixon** [comment]
Hey Evan:

The difference between the admin page and configuration settings is important - the configuration settings are rarely changed and have significant implications. The admin page should be monitored frequently and can have different access permissions.

**Comment by fulltrucker** [comment]
Hi Alan, Thanks for the clarification.

Karin, I'll take a look at the report.
