### ISSUE TITLE
First recurring contribution fails with CVV2 required error

### ISSUE THREAD

**Issue by fulltrucker** [iATSPayments/com.iatspayments.civicrm#92]
We use price sets for our membership pages, and have been testing auto-renewing memberships on our dev server, using the test iATS payment processor, with good success.

Since auto-renewing memberships using the iATS test processor were going great and completing successfully, I decided to test this on a single membership signup page on our live server using the live iATS processor for our account. The initial contribution was successful, and a membership was created correctly. When the day came to auto-renew the membership, Civi sent off the contribution to iATS for processing but it failed with a "iATS Payments Recurring Contribution (id=16) CVV2 required" error.

I also tested a recurring donation with no membership associated and no price set, and observed the same behavior: the intital contribution was processed succesfully but the first (and now second) recurring contributions failed at iATS with a "iATS Payments Recurring Contribution (id=17) CVV2 required" error.

Is something not set up correctly? I looked through the documentation but didn't see anything that popped out at me.

I also got no email notification (either as an admin or as the user who submitted the card) that the card was declined for either of these transactions.

The recurring contributions continue to attempt processing and have a status of "In Progress" — shouldn't they cancel or discontinue if they fail?

Edit to add: the CVV2 was captured on both transactions, it's part of the payment form. These were both front-end forms.

**Comment by stephenbiats** [comment]
Hi.  It seems that you are using the wrong iATS subcode for your recurring transactions.  iATS provides free subcodes for reconciliation purposes, but you need to specify which subcodes you want to do recurring transactions on.  Contact the iATS customer care and check if the subcode (the last 2 numbers on your account) that you are using in Civi has the recurring flag on.

**Comment by adixon** [comment]
You probably want to be clear with the iATS customer care that you're not using the iATS-server-recurring-transactions, that's not the permission you need. It's the ability to charge a card using the customer token that you need. But yes, sounds like a subcode permissions issue. You could test it by switching the subcode temporarily to 01.

You will also like want to manually crank back the next recurring payment dates for the failures - by default it'll just skip the failed payment and try again next month. You can use this module 

https://github.com/adixon/ca.civicrm.contributionrecur

if you're not comfortable mangling the civicrm_contribution_recur table (the next_sched_contribution_date field).

**Comment by fulltrucker** [comment]
Thanks Alan,

Cna you comment on why an email would not have been sent when the contributiuon failed? My expectation would be that if the recurring contribution failed, an email would be sent to the contact letting them know their CC didn't run, and the reason. I'm particularly worried about when expiration dates on a CC are invalid.

Also, I believe Eileen did some work surrounding memberships/recurring contributions in core and that seems to be working in our test environment. Will the extension referenced above play nicely with that work? I can ping her as well. Otherwise, I've just been adjusting dates directly in the civicrm_contribution_recur table.

Cheers,
Evan

**Comment by adixon** [comment]
Yes, better handling of failures in this extension is on our roadmap, hopefully for the next release.

For now, it's important, especially when first setting up, to monitor the iATS admin page, which gives you a nice sense of how things are going.

Expiry dates are also due for some more sophisticated handling. For now we recommend you use the new iATS report templates to set up a report of upcoming expiry dates so you can be proactive about them.

Recurring memberships w/ 4.6.8 should be working as you would expect, assuming you have reasonable expectations (i.e. auto-renewing payments and memberships). That recurring contribution extension I linked to above has a scheduled job that can handle more complex use cases and deal with older code bases.

**Comment by adixon** [comment]
Better handling of failures is now in place, including emails and the ability to modify cc information:
https://github.com/iATSPayments/com.iatspayments.civicrm/wiki/Recurring-Contribution-Failure-Handling
