### ISSUE TITLE
Recurring Subscription Behavior Inconsistencies

### ISSUE THREAD

**Issue by tamarmeir** [iATSPayments/com.iatspayments.civicrm#93]
Hi all,

The following is closely related to the issues reported in #24 and #27, and has to do with more consistent handling of recurring subscriptions in accordance with other payment processor subscription handling (e.g. authorize.net) - again, as I am not a programmer, I am not sure what lies exactly where (i.e. iATS extension vs. core), so your guidance would be appreciated where needed.

iATS v1.4.1
CiviCRM v4.6.7
Drupal v7.34

I ran several test recurring subscriptions (both ACH and CC) and observed the behaviors as detailed in the attached screenshot (tried to upload .xls, .csv and since not supported - screen shot was faster for me) - I compared my observations to current authorize.net behavior, and I would like to point out two of the more critical items when it comes to ACH recurring subscriptions:

1. When initial installment fails, subscription status is "In Progress" as opposed to being marked as "Failed"
2. When additional installments fail, subscription status can be marked as "Completed" once all installments have processed (regardless of their failure status) as opposed to being marked as "In Progress"

![iat_recurring_behavior](https://cloud.githubusercontent.com/assets/14094020/10124790/5a55f7e6-651b-11e5-8d8f-06a9b258b4e5.jpg)

Thanks in advance for your time and for any input you can provide on this to a non-programmer,

Tamar

**Comment by adixon** [comment]
There is certainly a lot of grey areas and potential improvements when it comes to handling failures, you'll see a few issues hanging on this challenge.

A couple of short notes to your observations, which are much appreciated.

1. By default, the subscription status stays as "In progress" until it's cancelled manually or the number of contributions equals or exceeds the number configured (unless of course it's zero). Although that seems like a bad idea in many cases, it's the only reasonable default, as far as I can figure. For example, if the initial contribution fails as a temporary issue (e.g. credit over limit on the card), then you really do want that status to stay in progress.

On the other hand, some more sophisticated error handling should be able to identify cases where a failure is permanent (e.g. 'stolen card' or 'expired'). In those cases, yes, we should be switching to cancelled.

2. I'm not sure if I understand this one - are you saying that failed transactions are counting towards a subscription being completed? Or that they are not but should be? I'd think they shouldn't be, and if they are then yes, that's not good. Although it's not always clear - for example, if someone signs up for a year of donations, and one doesn't go through, they might still reasonably expect that the subscription stop after one year anyway.

In any case, thanks for your notes here, and apologies for the delay in response.

**Comment by tamarmeir** [comment]
Hi Alan,

Any my apologies for the delay in my follow up response. I offer the following to clarify your questions and provide a little more logic that might help justify some changes:

1) Speaking of just the first installment of a subscription and using your example of a failed credit card because of exceeding credit limit - one would think that the donor would be contacted for an alternative means of payment (i.e. a different credit card) - iATS does not support update of payment details through Civi, so the organization's user would have to cancel and create a new subscription anyway, so marking the subscription as "Failed" would still be logical and would save the user from the need to cancel one subscription in addition to creating a new one. To strengthen this logic:
2)  In my testing, I created a subscription for 2 installments, both of which failed - the subscription status changed from "In Progress" to "Completed", meaning failed transactions ARE indeed counted together with completed transactions towards the number of installments and subscriptions are being prematurely marked as "Completed" (hence my indication that this post is closely related to #24 and #27), and my comment here was to say that if a subscription was "In Progress" when any but the initial installment fails, it should remain in the status of "In Progress" until the number of successfully "Completed" contributions = the number of installments, but all of this brings me to another question (and I googled all over the place and was up and down iatspayments.com but couldn't find TFM to R): 
3) Let's say that instead of providing a different credit card for payment when a transaction is declined because the limit was exceeded, the donor pays off the balance and tells the organization to try again - the only place I can see where to manipulate the installment date or the failure retry date is under the hood, directly in civicrmcontribution_recur - this is something that our end users do not have access to for obvious reasons - if I am wrong and/or if this is explained somewhere in a manual that I could not find, the link to that documentation would be greatly appreciated (I won't need encouragement to read it, I promise) - if there is no place to do this in the GUI, then again, the status of "Failed" would still prevent the need for the user to cancel the subscription in addition to creating a new one and my previous indication of using the status of "In Progress" when any but the initial installment fails is no longer valid.

Thanks again for your time and I look forward to your response - and I am always happy to help out with the logic on this further.

Tamar

**Comment by KarinG** [comment]
Creating its own issue for this one: "failed transactions are being counted together with completed transactions and subscriptions are being prematurely marked completed"

**Comment by adixon** [comment]
There are a few issues in here, most of them addressed in the latest release, documented here:
https://github.com/iATSPayments/com.iatspayments.civicrm/wiki/Recurring-Contribution-Failure-Handling
Please do open a new issue if you want to improve this further.
